// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Medidata.RBT.Features.Rave.Features.EDC
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class _8Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "564QueryRefiringLogic8.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "8", "As a Rave user\r\nI want to change data\r\nSo I can see refired queries", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "8")))
            {
                Medidata.RBT.Features.Rave.Features.EDC._8Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 23
#line 25
    testRunner.Given("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void Test()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("test", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 45
 testRunner.And("I select Study \"Edit Check Study 3\" and Site \"Edit Check Site 3\"");
#line 46
 testRunner.And("I select a Subject \"sub315\"");
#line 47
 testRunner.And("I select Form \"Concomitant Medications\" in Folder \"Screening\"");
#line 48
 testRunner.And("I open log line 1");
#line 49
 testRunner.And("I answer the only Query on Field \"Start Date\" with \"bla\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.1.1 As an EDC user, Data setup and verification for query re-firing. Folder " +
            "\"Screening\" enter and save data on forms \"Informed Consent\" and \"Concomitant Med" +
            "ications\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_1_1AsAnEDCUserDataSetupAndVerificationForQueryRe_Firing_FolderScreeningEnterAndSaveDataOnFormsInformedConsentAndConcomitantMedications()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.1.1 As an EDC user, Data setup and verification for query re-firing. Folder " +
                    "\"Screening\" enter and save data on forms \"Informed Consent\" and \"Concomitant Med" +
                    "ications\"", new string[] {
                        "release_564_Patch11",
                        "PB_8.1.1",
                        "Draft"});
#line 55
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 57
 testRunner.And("I navigate to \"DDE\"");
#line 58
 testRunner.And("I select \"First Pass\"");
#line 59
 testRunner.And("I select \"New Batch\"");
#line 60
 testRunner.And("I choose \"Edit Check Study 3\" from \"Study\"");
#line 61
 testRunner.And("I choose \"Prod\" from \"Environment\"");
#line 62
 testRunner.And("I choose \"Edit Check Site 8\" from \"Site\"");
#line 63
 testRunner.And("I type \"sub {RndNum<num1>(5)}\" in \"Subject\"");
#line 64
 testRunner.And("I choose \"Subject Identification\" from \"Form\"");
#line 65
 testRunner.And("I click button \"Locate\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table1.AddRow(new string[] {
                        "Subject Number",
                        "{Var(num1)}"});
            table1.AddRow(new string[] {
                        "Subject Initials",
                        "sub"});
#line 66
 testRunner.And("I enter data in DDE and save", ((string)(null)), table1);
#line 70
 testRunner.And("I choose \"Screening\" from \"Folder\"");
#line 71
 testRunner.And("I choose \"Informed Consent\" from \"Form\"");
#line 72
 testRunner.And("I click button \"Locate\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table2.AddRow(new string[] {
                        "Date Informed Consent Signed",
                        "09 Jan 2000"});
            table2.AddRow(new string[] {
                        "End Date",
                        "10 Jan 2000"});
            table2.AddRow(new string[] {
                        "Original Distribution Number",
                        "10"});
            table2.AddRow(new string[] {
                        "Current Distribution Number",
                        "19"});
#line 73
 testRunner.And("I enter data in DDE and save", ((string)(null)), table2);
#line 79
 testRunner.And("I choose \"Concomitant Medications\" from \"Form\"");
#line 80
 testRunner.And("I click button \"Locate\"");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table3.AddRow(new string[] {
                        "Start Date",
                        "08 Jan 2000"});
            table3.AddRow(new string[] {
                        "End Date",
                        "11 Jan 2000"});
            table3.AddRow(new string[] {
                        "Original Axis Number",
                        "10"});
            table3.AddRow(new string[] {
                        "Current Axis Number",
                        "20"});
#line 81
 testRunner.And("I enter data in DDE log line 1 and save", ((string)(null)), table3);
#line 88
 testRunner.And("I am logged in to Rave with username \"coderimport\" and password \"password\"");
#line 89
 testRunner.And("I navigate to \"DDE\"");
#line 90
 testRunner.And("I select \"Second Pass\"");
#line 91
 testRunner.And("I choose \"Edit Check Study 3\" from \"Study\"");
#line 92
 testRunner.And("I choose \"Prod\" from \"Environment\"");
#line 93
 testRunner.And("I choose \"Edit Check Site 8\" from \"Site\"");
#line 94
 testRunner.And("I choose \"sub {Var(num1)}\" from \"Subject\"");
#line 95
 testRunner.And("I choose \"Subject Identification\" from \"Form\"");
#line 96
 testRunner.And("I click button \"Locate\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table4.AddRow(new string[] {
                        "Subject Number",
                        "{Var(num1)}"});
            table4.AddRow(new string[] {
                        "Subject Initials",
                        "sub"});
#line 97
 testRunner.And("I enter data in DDE and save", ((string)(null)), table4);
#line 101
 testRunner.And("I choose \"Screening\" from \"Folder\"");
#line 102
 testRunner.And("I choose \"Informed Consent\" from \"Form\"");
#line 103
 testRunner.And("I click button \"Locate\"");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table5.AddRow(new string[] {
                        "Date Informed Consent Signed",
                        "09 Jan 2000"});
            table5.AddRow(new string[] {
                        "End Date",
                        "10 Jan 2000"});
            table5.AddRow(new string[] {
                        "Original Distribution Number",
                        "10"});
            table5.AddRow(new string[] {
                        "Current Distribution Number",
                        "19"});
#line 104
 testRunner.And("I enter data in DDE and save", ((string)(null)), table5);
#line 110
 testRunner.And("I choose \"Concomitant Medications\" from \"Form\"");
#line 111
 testRunner.And("I click button \"Locate\"");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table6.AddRow(new string[] {
                        "Start Date",
                        "08 Jan 2000"});
            table6.AddRow(new string[] {
                        "End Date",
                        "11 Jan 2000"});
            table6.AddRow(new string[] {
                        "Original Axis Number",
                        "10"});
            table6.AddRow(new string[] {
                        "Current Axis Number",
                        "20"});
#line 112
 testRunner.And("I enter data in DDE log line 1 and save", ((string)(null)), table6);
#line 119
 testRunner.And("I navigate to \"Home\"");
#line 120
 testRunner.And("I select Study \"Edit Check Study 3\" and Site \"Edit Check Site 8\"");
#line 121
 testRunner.And("I select a Subject \"sub{Var(num1)}\"");
#line 122
 testRunner.And("I select Form \"Concomitant Medications\" in Folder \"Screening\"");
#line 123
 testRunner.And("I open log line 1");
#line 124
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 125
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 126
 testRunner.And("I take a screenshot");
#line 127
 testRunner.And("I answer the Query \"\'Date Informed Consent Signed\' is greater. Please revise.\" on" +
                    " Field \"Start Date\" with \"{answer}\"");
#line 128
 testRunner.And("I answer the Query \"Informed Consent \'Current Distribution Number\' is not equal t" +
                    "o Concomitant Medications \'Current Axis Number\'.\" on Field \"Current Axis Number\"" +
                    " with \"{answer}\"");
#line 129
 testRunner.And("I save the CRF page");
#line 130
 testRunner.And("I open log line 1");
#line 131
 testRunner.And("I close the Query \"\'Date Informed Consent Signed\' is greater. Please revise.\" on " +
                    "Field \"Start Date\"");
#line 132
 testRunner.And("I close the Query \"Informed Consent \'Current Distribution Number\' is not equal to" +
                    " Concomitant Medications \'Current Axis Number\'.\" on Field \"Current Axis Number\"");
#line 133
 testRunner.And("I save the CRF page");
#line 134
 testRunner.And("I take a screenshot");
#line 135
 testRunner.And("I open log line 1");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table7.AddRow(new string[] {
                        "Start Date",
                        "09 Jan 2000"});
            table7.AddRow(new string[] {
                        "Current Axis Number",
                        "19"});
#line 136
 testRunner.And("I enter data in CRF and save", ((string)(null)), table7);
#line 140
 testRunner.And("I open log line 1");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Message",
                        "Closed"});
            table8.AddRow(new string[] {
                        "Start Date",
                        "\'Date Informed Consent Signed\' is greater. Please revise.",
                        "true"});
            table8.AddRow(new string[] {
                        "Current Axis Number",
                        "Informed Consent \'Current Distribution Number\' is not equal to Concomitant Medica" +
                            "tions \'Current Axis Number\'.",
                        "true"});
#line 141
 testRunner.And("I verify Query is not displayed", ((string)(null)), table8);
#line 145
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table9.AddRow(new string[] {
                        "Start Date",
                        "08 Jan 2000"});
            table9.AddRow(new string[] {
                        "Current Axis Number",
                        "20"});
#line 146
 testRunner.When("I enter data in CRF and save", ((string)(null)), table9);
#line 150
 testRunner.And("I open log line 1");
#line 151
 testRunner.Then("I verify closed Query with message \"\'Date Informed Consent Signed\' is greater. Pl" +
                    "ease revise.\" is displayed on Field \"Start Date\"");
#line 152
 testRunner.And("I verify closed Query with message \"Informed Consent \'Current Distribution Number" +
                    "\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is displayed o" +
                    "n Field \"Current Axis Number\"");
#line 154
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.1.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_1_2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.1.2", new string[] {
                        "release_564_Patch11",
                        "PB_8.1.2",
                        "Draft"});
#line 160
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 162
    testRunner.Given("I select Study \"Edit Check Study 3\" and Site \"Edit Check Site 8\"");
#line 163
    testRunner.And("I select a Subject \"sub{Var(num1)}\"");
#line 164
 testRunner.And("I select Form \"Concomitant Medications\" in Folder \"Screening\"");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table10.AddRow(new string[] {
                        "Start Date",
                        "07 Jan 2000"});
            table10.AddRow(new string[] {
                        "End Date",
                        "12 Jan 2000"});
            table10.AddRow(new string[] {
                        "Original Axis Number",
                        "10"});
            table10.AddRow(new string[] {
                        "Current Axis Number",
                        "18"});
#line 165
 testRunner.And("I enter data in CRF on a new log line and save", ((string)(null)), table10);
#line 171
 testRunner.And("I open log line 2");
#line 172
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 173
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 174
 testRunner.And("I take a screenshot");
#line 175
 testRunner.And("I answer the Query \"\'Date Informed Consent Signed\' is greater. Please revise.\" on" +
                    " Field \"Start Date\" with \"{answer}\"");
#line 176
 testRunner.And("I answer the Query \"Informed Consent \'Current Distribution Number\' is not equal t" +
                    "o Concomitant Medications \'Current Axis Number\'.\" on Field \"Current Axis Number\"" +
                    " with \"{answer}\"");
#line 177
 testRunner.And("I save the CRF page");
#line 178
 testRunner.And("I open log line 2");
#line 179
 testRunner.And("I close the Query \"\'Date Informed Consent Signed\' is greater. Please revise.\" on " +
                    "Field \"Start Date\"");
#line 180
 testRunner.And("I close the Query \"Informed Consent \'Current Distribution Number\' is not equal to" +
                    " Concomitant Medications \'Current Axis Number\'.\" on Field \"Current Axis Number\"");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table11.AddRow(new string[] {
                        "Start Date",
                        "09 Jan 2000"});
            table11.AddRow(new string[] {
                        "Current Axis Number",
                        "19"});
#line 181
 testRunner.And("I enter data in CRF", ((string)(null)), table11);
#line 185
 testRunner.And("I save the CRF page");
#line 186
 testRunner.And("I take a screenshot");
#line 187
 testRunner.And("I open log line 2");
#line 188
 testRunner.And("I verify Field \"Start Date\" has no Query");
#line 189
 testRunner.And("I verify Field \"Current Axis Number\" has no Query");
#line 190
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table12.AddRow(new string[] {
                        "Start Date",
                        "07 Jan 2000"});
            table12.AddRow(new string[] {
                        "Current Axis Number",
                        "18"});
#line 191
 testRunner.And("I enter data in CRF and save", ((string)(null)), table12);
#line 195
 testRunner.And("I open log line 2");
#line 196
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is not displayed on Field \"Start Date\"");
#line 197
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "not displayed on Field \"Current Axis Number\"");
#line 198
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.1.3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_1_3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.1.3", new string[] {
                        "release_564_Patch11",
                        "PB_8.1.3",
                        "Draft"});
#line 204
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 206
    testRunner.Given("I select Study \"Edit Check Study 3\" and Site \"Edit Check Site 8\"");
#line 207
    testRunner.And("I select a Subject \"sub{Var(num1)}\"");
#line 208
 testRunner.And("I select Form \"Concomitant Medications\" in Folder \"Screening\"");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table13.AddRow(new string[] {
                        "Start Date",
                        "07 Jan 2000"});
            table13.AddRow(new string[] {
                        "End Date",
                        "12 Jan 2000"});
            table13.AddRow(new string[] {
                        "Original Axis Number",
                        "10"});
            table13.AddRow(new string[] {
                        "Current Axis Number",
                        "18"});
#line 209
 testRunner.And("I enter data in CRF on a new log line and save", ((string)(null)), table13);
#line 215
 testRunner.And("I open log line 3");
#line 216
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 217
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 218
 testRunner.And("I take a screenshot");
#line 219
 testRunner.And("I cancel the Query \"\'Date Informed Consent Signed\' is greater. Please revise.\" on" +
                    " Field \"Start Date\"");
#line 220
 testRunner.And("I cancel the Query \"Informed Consent \'Current Distribution Number\' is not equal t" +
                    "o Concomitant Medications \'Current Axis Number\'.\" on Field \"Current Axis Number\"" +
                    "");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table14.AddRow(new string[] {
                        "Start Date",
                        "09 Jan 2000"});
            table14.AddRow(new string[] {
                        "Current Axis Number",
                        "19"});
#line 221
 testRunner.And("I enter data in CRF", ((string)(null)), table14);
#line 225
 testRunner.And("I save the CRF page");
#line 226
 testRunner.And("I take a screenshot");
#line 227
 testRunner.And("I open log line 3");
#line 228
 testRunner.And("I verify Field \"Start Date\" has no Query");
#line 229
 testRunner.And("I verify Field \"Current Axis Number\" has no Query");
#line 230
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table15.AddRow(new string[] {
                        "Start Date",
                        "07 Jan 2000"});
            table15.AddRow(new string[] {
                        "Current Axis Number",
                        "18"});
#line 231
 testRunner.And("I enter data in CRF and save", ((string)(null)), table15);
#line 235
 testRunner.And("I open log line 3");
#line 236
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 237
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 238
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.2.1 Task Summary")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_2_1TaskSummary()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.2.1 Task Summary", new string[] {
                        "release_564_Patch11",
                        "PB_8.2.1",
                        "Draft"});
#line 244
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 246
 testRunner.And("I select Study \"Edit Check Study 3\" and Site \"Edit Check Site 8\"");
#line 247
    testRunner.And("I select a Subject \"sub{Var(num1)}\"");
#line 249
 testRunner.When("I expand \"Open Queries\" in Task Summary");
#line 250
 testRunner.Then("I should see \"Screening-Concomitant Medications\" in \"Open Queries\"");
#line 251
 testRunner.And("I select \"Screening-Concomitant Medications\" in \"Open Queries\"");
#line 252
 testRunner.And("I open log line 3");
#line 253
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 254
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 255
 testRunner.And("I take a screenshot");
#line 257
    testRunner.And("I select a Subject \"sub{Var(num1)}\"");
#line 259
 testRunner.When("I expand \"Cancel Query\" in Task Summary");
#line 260
 testRunner.Then("I should see \"Screening-Concomitant Medications\" in \"Open Query\"");
#line 261
 testRunner.And("I select \"Screening-Concomitant Medications\" in \"Open Query\"");
#line 262
 testRunner.And("I open log line 3");
#line 263
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 264
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 266
 testRunner.And("I verify Cancel Query with message \"\'Date Informed Consent Signed\' is greater. Pl" +
                    "ease revise.\" is displayed on Field \"Start Date\"");
#line 267
 testRunner.And("I verify Cancel Query with message \"Informed Consent \'Current Distribution Number" +
                    "\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is displayed o" +
                    "n Field \"Start Date\"");
#line 268
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.3.1 Query Management")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_3_1QueryManagement()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.3.1 Query Management", new string[] {
                        "release_564_Patch11",
                        "PB_8.3.1",
                        "Draft"});
#line 274
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 276
 testRunner.And("I navigate to \"Query Management\"");
#line 277
 testRunner.And("I choose \"Edit Check Study 3 (Prod)\" from \"Study\"");
#line 278
 testRunner.And("I choose \"World\" from \"Site Group\"");
#line 279
 testRunner.And("I choose \"Edit Check Site 8\" from \"Site\"");
#line 280
 testRunner.And("I choose \"sub{Var(num1)}\" from \"Subject\"");
#line 281
 testRunner.And("I click button \"Advanced Search\"");
#line 283
 testRunner.And("I select Form \"Concomitant Medications\" in search result");
#line 284
 testRunner.And("I open log line 2");
#line 285
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 286
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 287
 testRunner.And("I take a screenshot");
#line 288
 testRunner.And("I open log line 3");
#line 289
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 290
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 291
 testRunner.And("I take a screenshot");
#line 294
 testRunner.And("I select \"Cancel\"");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table16.AddRow(new string[] {
                        "Start Date",
                        "07 Jan 2000"});
            table16.AddRow(new string[] {
                        "End Date",
                        "12 Jan 2000"});
            table16.AddRow(new string[] {
                        "Original Axis Numbe",
                        "10"});
#line 295
 testRunner.And("I enter data in CRF on new log line 4 and save and reopen", ((string)(null)), table16);
#line 300
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 301
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 302
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table17.AddRow(new string[] {
                        "Start Date",
                        "09 Jan 2000"});
            table17.AddRow(new string[] {
                        "Current Axis Number",
                        "19"});
#line 303
 testRunner.And("I enter data in CRF", ((string)(null)), table17);
#line 307
 testRunner.And("I cancel the Query \"\'Date Informed Consent Signed\' is greater. Please revise.\" on" +
                    " Field \"Start Date\"");
#line 308
 testRunner.And("I cancel the Query \"Informed Consent \'Current Distribution Number\' is not equal t" +
                    "o Concomitant Medications \'Current Axis Number\'.\" on Field \"Current Axis Number\"" +
                    "");
#line 309
 testRunner.And("I save the CRF page");
#line 310
 testRunner.And("I take a screenshot");
#line 311
 testRunner.And("I open log line 4");
#line 312
 testRunner.And("I verify Field \"Start Date\" has no Query");
#line 313
 testRunner.And("I verify Field \"Current Axis Number\" has no Query");
#line 314
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table18.AddRow(new string[] {
                        "Start Date",
                        "07 Jan 2000"});
            table18.AddRow(new string[] {
                        "Current Axis Number",
                        "18"});
#line 315
 testRunner.And("I enter data in CRF and save", ((string)(null)), table18);
#line 319
 testRunner.And("I open log line 4");
#line 320
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 321
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 322
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.3.2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_3_2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.3.2", new string[] {
                        "release_564_Patch11",
                        "PB_8.3.2",
                        "Draft"});
#line 328
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 330
 testRunner.And("I navigate to \"Query Management\"");
#line 331
 testRunner.And("I choose \"Edit Check Study 3 (Prod)\" from \"Study\"");
#line 332
 testRunner.And("I choose \"World\" from \"Site Group\"");
#line 333
 testRunner.And("I choose \"Edit Check Site 8\" from \"Site\"");
#line 334
 testRunner.And("I choose \"sub{Var(num1)}\" from \"Subject\"");
#line 335
 testRunner.And("I click button \"Advanced Search\"");
#line 337
 testRunner.And("I select Form \"Concomitant Medications\" in search result");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table19.AddRow(new string[] {
                        "Start Date",
                        "07 Jan 2000"});
            table19.AddRow(new string[] {
                        "End Date",
                        "12 Jan 2000"});
            table19.AddRow(new string[] {
                        "Original Axis Numbe",
                        "10"});
            table19.AddRow(new string[] {
                        "Current Axis Number",
                        "18"});
#line 338
 testRunner.And("I enter data in CRF on new log line 5 and save and reopen", ((string)(null)), table19);
#line 344
 testRunner.And("I open log line 5");
#line 345
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 346
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 347
 testRunner.And("I take a screenshot");
#line 348
 testRunner.And("I answer the Query \"\'Date Informed Consent Signed\' is greater. Please revise.\" on" +
                    " Field \"Start Date\" with \"{answer}\"");
#line 349
 testRunner.And("I answer the Query \"Informed Consent \'Current Distribution Number\' is not equal t" +
                    "o Concomitant Medications \'Current Axis Number\'.\" on Field \"Current Axis Number\"" +
                    " with \"{answer}\"");
#line 350
 testRunner.And("I save the CRF page");
#line 351
 testRunner.And("I open log line 5");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table20.AddRow(new string[] {
                        "Start Date",
                        "09 Jan 2000"});
            table20.AddRow(new string[] {
                        "Current Axis Number",
                        "19"});
#line 352
 testRunner.And("I enter data in CRF and save", ((string)(null)), table20);
#line 356
 testRunner.And("I open log line 5");
#line 357
 testRunner.And("I close the Query \"\'Date Informed Consent Signed\' is greater. Please revise.\" on " +
                    "Field \"Start Date\"");
#line 358
 testRunner.And("I close the Query \"Informed Consent \'Current Distribution Number\' is not equal to" +
                    " Concomitant Medications \'Current Axis Number\'.\" on Field \"Current Axis Number\"");
#line 359
 testRunner.And("I save the CRF page");
#line 360
 testRunner.And("I take a screenshot");
#line 361
 testRunner.And("I open log line 5");
#line 362
 testRunner.And("I verify Field \"Start Date\" has no Query");
#line 363
 testRunner.And("I verify Field \"Current Axis Number\" has no Query");
#line 364
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table21.AddRow(new string[] {
                        "Start Date",
                        "07 Jan 2000"});
            table21.AddRow(new string[] {
                        "Current Axis Number",
                        "18"});
#line 365
 testRunner.And("I enter data in CRF and save", ((string)(null)), table21);
#line 369
 testRunner.And("I open log line 5");
#line 370
 testRunner.And("I verify Requires Response Query with message \"\'Date Informed Consent Signed\' is " +
                    "greater. Please revise.\" is displayed on Field \"Start Date\"");
#line 371
 testRunner.And("I verify Requires Response Query with message \"Informed Consent \'Current Distribu" +
                    "tion Number\' is not equal to Concomitant Medications \'Current Axis Number\'.\" is " +
                    "displayed on Field \"Current Axis Number\"");
#line 372
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.4.1 Generate the Data PDFs.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_4_1GenerateTheDataPDFs_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.4.1 Generate the Data PDFs.", new string[] {
                        "release_564_Patch11",
                        "PB_8.4.1",
                        "Draft"});
#line 378
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 379
 testRunner.And("I navigate to \"PDF Generator\"");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Profile",
                        "Study",
                        "Role",
                        "SiteGroup",
                        "Site",
                        "Subject"});
            table22.AddRow(new string[] {
                        "pdf{RndNum<num>(3)}",
                        "test1",
                        "Edit Check Study 8 (Prod)",
                        "CDM1",
                        "World",
                        "Edit Check Site 2",
                        "SUB640"});
#line 381
 testRunner.And("I create Data PDF", ((string)(null)), table22);
#line 385
 testRunner.And("I generate Data PDF \"pdf{Var(num)}\"");
#line 386
 testRunner.And("I wait for PDF \"pdf{Var(num)}\" to complete");
#line 387
 testRunner.When("I View Data PDF \"pdf{Var(num)}\"");
#line 389
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.5.1 When I run the Report, then query related data are displayed in the repo" +
            "rt.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_5_1WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.5.1 When I run the Report, then query related data are displayed in the repo" +
                    "rt.", new string[] {
                        "release_564_Patch11",
                        "PB_8.5.1",
                        "Draft"});
#line 395
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 397
 testRunner.And("I navigate to \"Reporter\"");
#line 398
 testRunner.And("I select Report \"Audit Trail\"");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table23.AddRow(new string[] {
                        "Edit Check Study 8",
                        "Prod"});
#line 399
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table23);
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table24.AddRow(new string[] {
                        "Edit Check Site 8"});
#line 402
 testRunner.And("I set report parameter \"Sites\" with table", ((string)(null)), table24);
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table25.AddRow(new string[] {
                        "sub 10250"});
#line 405
 testRunner.And("I set report parameter \"Subjects\" with table", ((string)(null)), table25);
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table26.AddRow(new string[] {
                        "Screening"});
#line 408
 testRunner.And("I set report parameter \"Folders\" with table", ((string)(null)), table26);
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table27.AddRow(new string[] {
                        "Informed Consent"});
            table27.AddRow(new string[] {
                        "Concomitant Medications"});
#line 411
 testRunner.And("I set report parameter \"Forms\" with table", ((string)(null)), table27);
#line 416
 testRunner.And("I click button \"Submit Report\"");
#line 417
 testRunner.And("I switch to \"Targeted SDV Subject Override\" window");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.5.2 When I run the Report, then query related data are displayed in the repo" +
            "rt.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_5_2WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.5.2 When I run the Report, then query related data are displayed in the repo" +
                    "rt.", new string[] {
                        "release_564_Patch11",
                        "PB_8.5.2",
                        "Draft"});
#line 427
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 430
 testRunner.And("I navigate to \"Reporter\"");
#line 431
 testRunner.And("I select report \"Query Detail\"");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table28.AddRow(new string[] {
                        "Edit Check Study 8",
                        "Prod"});
#line 432
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table28);
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table29.AddRow(new string[] {
                        "Edit Check Site 8"});
#line 435
 testRunner.And("I set report parameter \"Sites\" with table", ((string)(null)), table29);
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table30.AddRow(new string[] {
                        "sub 10250"});
#line 438
 testRunner.And("I set report parameter \"Subjects\" with table", ((string)(null)), table30);
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table31.AddRow(new string[] {
                        "Screening"});
#line 441
 testRunner.And("I set report parameter \"Folders\" with table", ((string)(null)), table31);
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table32.AddRow(new string[] {
                        "Informed Consent"});
            table32.AddRow(new string[] {
                        "Concomitant Medications"});
#line 444
 testRunner.And("I set report parameter \"Forms\" with table", ((string)(null)), table32);
#line 448
 testRunner.When("I click button \"Submit Report\"");
#line 449
 testRunner.And("I switch to \"Targeted SDV Subject Override\" window");
#line 451
 testRunner.And("I take a screenshot");
#line 452
 testRunner.And("I close report");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.5.3 When I run the Report, then query related data are displayed in the repo" +
            "rt.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_5_3WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.5.3 When I run the Report, then query related data are displayed in the repo" +
                    "rt.", new string[] {
                        "release_564_Patch11",
                        "PB_8.5.3",
                        "Draft"});
#line 458
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 461
 testRunner.And("I navigate to \"Reporter\"");
#line 462
 testRunner.And("I select report \"Edit Check Log Report\"");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table33.AddRow(new string[] {
                        "Edit Check Study 8",
                        "Prod"});
#line 463
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table33);
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table34.AddRow(new string[] {
                        "Edit Check Site 8"});
#line 466
 testRunner.And("I set report parameter \"Sites\" with table", ((string)(null)), table34);
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table35.AddRow(new string[] {
                        "sub 10250"});
#line 469
 testRunner.And("I set report parameter \"Subjects\" with table", ((string)(null)), table35);
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table36.AddRow(new string[] {
                        "Screening"});
#line 472
 testRunner.And("I set report parameter \"Folders\" with table", ((string)(null)), table36);
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table37.AddRow(new string[] {
                        "Concomitant Medications"});
#line 475
 testRunner.And("I set report parameter \"Forms\" with table", ((string)(null)), table37);
#line 480
 testRunner.And("I select checkbox \"Edit Check\" for \"Check Type\"");
#line 481
 testRunner.And("I select checkbox Check \"CheckExecution\" for \"Log Type\"");
#line 482
 testRunner.When("I click button \"Submit Report\"");
#line 483
 testRunner.And("I switch to \"Targeted SDV Subject Override\" window");
#line 484
 testRunner.Then("I should see fired editchecks");
#line 485
 testRunner.And("I take a screenshot");
#line 486
 testRunner.And("I close report");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.5.4 When I run the Report, then query related data are displayed in the repo" +
            "rt.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_5_4WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.5.4 When I run the Report, then query related data are displayed in the repo" +
                    "rt.", new string[] {
                        "release_564_Patch11",
                        "PB_8.5.4",
                        "Draft"});
#line 492
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 495
 testRunner.And("I navigate to \"Reporter\"");
#line 496
 testRunner.And("I select report \"Stream-Audit Trail\"");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table38.AddRow(new string[] {
                        "Edit Check Study 8",
                        "Prod"});
#line 497
testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table38);
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table39.AddRow(new string[] {
                        "Edit Check Site 8"});
#line 500
 testRunner.And("I set report parameter \"Sites\" with table", ((string)(null)), table39);
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table40.AddRow(new string[] {
                        "sub 10250"});
#line 503
 testRunner.And("I set report parameter \"Subjects\" with table", ((string)(null)), table40);
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table41.AddRow(new string[] {
                        "Screening"});
#line 506
 testRunner.And("I set report parameter \"Folders\" with table", ((string)(null)), table41);
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table42.AddRow(new string[] {
                        "Concomitant Medications"});
            table42.AddRow(new string[] {
                        "form2"});
#line 509
 testRunner.And("I set report parameter \"Forms\" with table", ((string)(null)), table42);
#line 513
 testRunner.And("I click button \"Submit Report\"");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table43.AddRow(new string[] {
                        "Separator",
                        "."});
            table43.AddRow(new string[] {
                        "File type",
                        ".csv"});
            table43.AddRow(new string[] {
                        "Export type",
                        "attachment"});
            table43.AddRow(new string[] {
                        "Save as Unicode",
                        "Unchecked"});
#line 517
 testRunner.When("I select \"Parameter\" to \"Value\", from the tabe below", ((string)(null)), table43);
#line 523
 testRunner.And("I open excel file");
#line 524
 testRunner.Then("I should see queries on \"Start Date\" and \"Current Axis Number\" fields");
#line 525
 testRunner.And("I take a screenshot");
#line 526
 testRunner.And("I close report");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.5.5 When I run the Report, then query related data are displayed in the repo" +
            "rt.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_5_5WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.5.5 When I run the Report, then query related data are displayed in the repo" +
                    "rt.", new string[] {
                        "release_564_Patch11",
                        "PB_8.5.5",
                        "Draft"});
#line 532
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 535
 testRunner.And("I navigate to \"Reporter\"");
#line 536
 testRunner.And("I select report \"Stream-Query Detail\"");
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table44.AddRow(new string[] {
                        "Edit Check Study 8",
                        "Prod"});
#line 537
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table44);
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table45.AddRow(new string[] {
                        "Edit Check Site 8"});
#line 540
 testRunner.And("I set report parameter \"Sites\" with table", ((string)(null)), table45);
#line hidden
            TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table46.AddRow(new string[] {
                        "sub 10250"});
#line 543
 testRunner.And("I set report parameter \"Subjects\" with table", ((string)(null)), table46);
#line hidden
            TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table47.AddRow(new string[] {
                        "Screening"});
#line 546
 testRunner.And("I set report parameter \"Folders\" with table", ((string)(null)), table47);
#line hidden
            TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table48.AddRow(new string[] {
                        "Concomitant Medications"});
#line 549
 testRunner.And("I set report parameter \"Forms\" with table", ((string)(null)), table48);
#line 553
 testRunner.And("I click button \"Submit Report\"");
#line hidden
            TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table49.AddRow(new string[] {
                        "Separator",
                        "."});
            table49.AddRow(new string[] {
                        "File type",
                        ".csv"});
            table49.AddRow(new string[] {
                        "Export type",
                        "attachment"});
            table49.AddRow(new string[] {
                        "Save as Unicode",
                        "Unchecked"});
#line 554
 testRunner.When("I select \"Parameter\" to \"Value\", from the tabe below", ((string)(null)), table49);
#line 560
 testRunner.And("I open excel file");
#line 561
 testRunner.Then("I should see queries on \"Start Date\" and \"Current Axis Number\" fields");
#line 562
 testRunner.And("I take a screenshot");
#line 563
 testRunner.And("I close report");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.5.6 When I run the Report, then query related data are displayed in the repo" +
            "rt.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_5_6WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.5.6 When I run the Report, then query related data are displayed in the repo" +
                    "rt.", new string[] {
                        "release_564_Patch11",
                        "PB_8.5.6",
                        "Draft"});
#line 569
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 572
 testRunner.And("I navigate to \"Reporter\"");
#line 573
 testRunner.And("I select report \"Stream-Edit Check Log Report\"");
#line hidden
            TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table50.AddRow(new string[] {
                        "Edit Check Study 8",
                        "Prod"});
#line 574
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table50);
#line hidden
            TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table51.AddRow(new string[] {
                        "Edit Check Site 8"});
#line 577
 testRunner.And("I set report parameter \"Sites\" with table", ((string)(null)), table51);
#line hidden
            TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table52.AddRow(new string[] {
                        "sub 10250"});
#line 580
 testRunner.And("I set report parameter \"Subjects\" with table", ((string)(null)), table52);
#line hidden
            TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table53.AddRow(new string[] {
                        "Concomitant Medications"});
#line 583
 testRunner.And("I set report parameter \"Forms\" with table", ((string)(null)), table53);
#line 587
 testRunner.And("I select checkbox \"Edit Check\" for \"Check Type\"");
#line 588
 testRunner.And("I select checkbox Check \"CheckExecution\" for \"Log Type\"");
#line 589
 testRunner.And("I click button \"Submit Report\"");
#line hidden
            TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table54.AddRow(new string[] {
                        "Separator",
                        "."});
            table54.AddRow(new string[] {
                        "File type",
                        ".csv"});
            table54.AddRow(new string[] {
                        "Export type",
                        "attachment"});
            table54.AddRow(new string[] {
                        "Save as Unicode",
                        "Unchecked"});
#line 590
 testRunner.And("I select \"Parameter\" to \"Value\", from the tabe below", ((string)(null)), table54);
#line 596
 testRunner.When("I open excel file");
#line 597
 testRunner.Then("I should see fired editchecks");
#line 598
 testRunner.And("I take a screenshot");
#line 599
 testRunner.And("I close report");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.6.1 When I run the Report, then query related data are displayed in the repo" +
            "rt.J-Review verification.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_6_1WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_J_ReviewVerification_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.6.1 When I run the Report, then query related data are displayed in the repo" +
                    "rt.J-Review verification.", new string[] {
                        "release_564_Patch11",
                        "PB_8.6.1",
                        "Draft"});
#line 605
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 607
 testRunner.And("I navigate to \"Reporter\"");
#line 608
 testRunner.And("I select report \"J-Review\"");
#line hidden
            TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table55.AddRow(new string[] {
                        "Edit Check Study 8",
                        "Prod"});
#line 609
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table55);
#line 612
 testRunner.And("I click button \"Submit Report\"");
#line 613
 testRunner.And("I select \"Edit Check Study 8\" \"Prod\" from \"Studies\"");
#line 614
 testRunner.And("I click button \"Reports\"");
#line 615
 testRunner.And("I select \"Detail Data Listing\" report from \"Type\" in \"Report Browser\"");
#line 616
 testRunner.And("I select \"MetricViews\" from \"Panels\"");
#line 617
 testRunner.And("I select \"Queries\" from \"MetricViews\"");
#line 618
 testRunner.And("I select \"Project, Site, Subject, Datapage, Field, Record Position QueryText, Que" +
                    "ryStatus, Answered Data, Answer Text\"");
#line 619
 testRunner.When("I click button \"Create Report\"");
#line 620
 testRunner.Then("I should see \"sub801\"");
#line 621
 testRunner.And("I should see \"Added Query\" in \"QueryText\"");
#line 622
 testRunner.And("I take a screenshot");
#line 623
 testRunner.And("I Close \"Detail Data Listing\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.7.1 When I run the Report, then query related data are displayed in the repo" +
            "rt. BOXI report verification.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_7_1WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_BOXIReportVerification_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.7.1 When I run the Report, then query related data are displayed in the repo" +
                    "rt. BOXI report verification.", new string[] {
                        "release_564_Patch11",
                        "PB_8.7.1",
                        "Draft"});
#line 629
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 631
 testRunner.And("I navigate to \"Reporter\"");
#line 632
 testRunner.And("I select report \"Business Objects XI\"");
#line hidden
            TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table56.AddRow(new string[] {
                        "Edit Check Study 8",
                        "Prod"});
#line 633
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table56);
#line 636
 testRunner.And("I click button \"Submit Report\"");
#line 637
 testRunner.And("I select dropdown \"New\"");
#line 638
 testRunner.And("I select \"Web Intelligence Document\"");
#line 639
 testRunner.And("I select \"Rave 5.6 Universe\"");
#line 640
 testRunner.And("I select \"Project Name, Site Name, Subject Name, Folder Name, Form Name, Query Te" +
                    "xt\" in \"Results Objects\"");
#line 641
 testRunner.And("I select \"Site Name, Subject Name, Folder Name, FormName\" in \"Query Filters\"");
#line 642
 testRunner.And("I select \"Equal To\" from \"In List\" in \"Query Filters\" for \"Site Name\"");
#line 643
 testRunner.And("Enter \"Value(s) from list\" \"Edit Check Site 8\" in \"Query Filters\" for \"Site Name\"" +
                    "");
#line 644
 testRunner.And("I select \"Equal To\" from \"In List\" in \"Query Filters\" for \"Subject Name\"");
#line 645
 testRunner.And("Enter \"Value(s) from list\" \"sub801\" in \"Query Filters\" for \"Subject Name\"");
#line 646
 testRunner.And("I select \"Equal To\" from \"In List\" in \"Query Filters\" for \"Folder Name\"");
#line 647
 testRunner.And("Enter \"Value(s) from list\" \"Screening\" in \"Query Filters\" for \"Folder Name\"");
#line 648
 testRunner.And("I select \"Equal To\" from \"In List\" in \"Query Filters\" for \"Form Name\"");
#line 649
 testRunner.And("Enter \"Value(s) from list\" \"Concomitant Medications\" in \"Query Filters\" for \"Form" +
                    " Name\"");
#line 650
 testRunner.When("I click button \"Run Query\"");
#line 651
 testRunner.Then("I should see \"sub801\"");
#line 652
 testRunner.And("I should see \"Added Query\" in \"QueryText\"");
#line 653
 testRunner.And("I take a screenshot");
#line 654
 testRunner.And("I Close \"BOXI Report\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.8.1 When I run the Report, then query related data are displayed in the repo" +
            "rt. Migrate Subject")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_8_1WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_MigrateSubject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.8.1 When I run the Report, then query related data are displayed in the repo" +
                    "rt. Migrate Subject", new string[] {
                        "release_564_Patch11",
                        "PB_8.8.1",
                        "Draft"});
#line 660
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 662
 testRunner.And("I select Study \"AM Edit Check Study\"");
#line 663
 testRunner.And("I select Site \"AM Edit Site\"");
#line hidden
            TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table57.AddRow(new string[] {
                        "Subject Number",
                        "{NextSubjectNum<num1>(Edit Check Study 8,prod,Subject Number)}"});
            table57.AddRow(new string[] {
                        "Subject Initials",
                        "sub802"});
#line 664
    testRunner.And("I create a Subject", ((string)(null)), table57);
#line 668
 testRunner.And("I select Form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table58.AddRow(new string[] {
                        "Standard 1",
                        "6"});
            table58.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table58.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 669
 testRunner.And("I enter data in CRF and save", ((string)(null)), table58);
#line 674
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response");
#line 675
 testRunner.And("I answer the query on \"Log Field 1\" field");
#line 676
 testRunner.And("I save the CRF page");
#line 677
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 678
 testRunner.And("I save the CRF page");
#line 679
 testRunner.And("I note CRF Version \"<Source CRF Version1>\"");
#line 680
 testRunner.And("I take a screenshot");
#line 682
 testRunner.And("I select site \"AM Edit Site\"");
#line hidden
            TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table59.AddRow(new string[] {
                        "Subject Number",
                        "{NextSubjectNum<num1>(Edit Check Study 8,prod,Subject Number)}"});
            table59.AddRow(new string[] {
                        "Subject Initials",
                        "sub803"});
#line 683
    testRunner.And("I create a Subject", ((string)(null)), table59);
#line 687
 testRunner.And("I select Form \"Mixed Form\"");
#line 688
 testRunner.And("I enter data in CRF and save");
#line hidden
            TechTalk.SpecFlow.Table table60 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table60.AddRow(new string[] {
                        "Standard 1",
                        "6"});
            table60.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table60.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 689
testRunner.And("I save the CRF page", ((string)(null)), table60);
#line 694
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response");
#line 695
 testRunner.And("I answer the query on \"Log Field 1\" field");
#line 696
 testRunner.And("I save the CRF page");
#line hidden
            TechTalk.SpecFlow.Table table61 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table61.AddRow(new string[] {
                        "Standard 1",
                        "5"});
#line 697
 testRunner.And("I enter data in CRF and save", ((string)(null)), table61);
#line 700
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 701
 testRunner.And("I save the CRF page");
#line 702
 testRunner.And("I note CRF Version \"<Source CRF Version1>\"");
#line 703
 testRunner.And("I take a screenshot");
#line 705
 testRunner.And("I navigate to \"Home\"");
#line 706
 testRunner.And("I navigate to \"Architect\"");
#line 707
 testRunner.And("I select \"AM Edit Check Study\" in \"Active Projects\"");
#line 708
 testRunner.And("I select \"Draft123\" in \"CRF Drafts\"");
#line 709
 testRunner.And("I navigate to \"Edit Checks\"");
#line 710
 testRunner.And("I inactivate edit check \"Mixed Form Query\"");
#line 712
 testRunner.And("I select Draft \"Draft123\" in \"Header\"");
#line 715
 testRunner.And("I publish CRF Version \"Target{RndNum<num1>(3)}\"");
#line 717
 testRunner.And("I select Study \"AM Edit Check Study\" in \"Header\"");
#line 718
 testRunner.And("I navigate to \"Amendment Manager\"");
#line 719
 testRunner.And("I choose \"V1 (25)\" from \"Source CRF\"");
#line 720
 testRunner.And("I choose \"Target003 (39)\" from \"Target CRF\"");
#line 721
 testRunner.And("I click button \"Create Plan\"");
#line 722
 testRunner.And("I take a screenshot");
#line 723
 testRunner.And("I navigate to \"Execute Plan\"");
#line 724
 testRunner.And("I migrate all Subjects");
#line 725
 testRunner.And("I select Migration Results and verify Job Status is set to Complete");
#line 726
 testRunner.And("I take a screenshot");
#line 729
 testRunner.And("I navigate to \"Home\"");
#line 730
 testRunner.And("I select \"AM Edit Check Study\"");
#line 731
 testRunner.And("I select site \"AM Edit Site\"");
#line 732
    testRunner.And("I select a subject \"sub802\"");
#line 733
 testRunner.And("I select Form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table62.AddRow(new string[] {
                        "Log Field 1",
                        "4"});
#line 734
 testRunner.And("I enter data in CRF and save", ((string)(null)), table62);
#line 737
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line hidden
            TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table63.AddRow(new string[] {
                        "Log Field 1",
                        "3"});
            table63.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 738
 testRunner.And("I add a new log line, enter and save the data, from the table below", ((string)(null)), table63);
#line 742
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line 743
 testRunner.And("I take a screenshot");
#line 745
 testRunner.And("I select site \"AM Edit Site\"");
#line 746
    testRunner.And("I select a subject \"sub803\"");
#line 747
 testRunner.And("I select Form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table64.AddRow(new string[] {
                        "Standard 1",
                        "8"});
#line 748
 testRunner.And("I enter data in CRF and save", ((string)(null)), table64);
#line 751
 testRunner.And("I save the CRF page");
#line 752
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line hidden
            TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table65.AddRow(new string[] {
                        "Log Field 1",
                        "6"});
            table65.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 753
 testRunner.And("I add a new log line, enter and save the data, from the table below", ((string)(null)), table65);
#line 757
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line 758
 testRunner.And("I take a screenshot");
#line 760
 testRunner.And("I navigate to \"Home\"");
#line 761
 testRunner.And("I navigate to \"Architect\"");
#line 762
 testRunner.And("I navigate to \"AM Edit Check Study\"");
#line 763
 testRunner.And("I navigate to \"Draft 1\"");
#line 764
 testRunner.And("I navigate to \"Edit Checks\"");
#line 765
 testRunner.And("I select edit image for \"Mixed Form Query\" Edit Check");
#line 766
 testRunner.And("I select checkbox \"Active\"");
#line 767
 testRunner.And("I select  link \"Update\"");
#line 768
 testRunner.And("I navigate to \"Draft 1\"");
#line 769
 testRunner.And("I publish CRF Version");
#line 770
 testRunner.And("I note CRF Version \"<Target CRF Version2>\"");
#line 771
 testRunner.And("I navigate to \"AM Edit Check Study\"");
#line 772
 testRunner.And("I navigate to \"Amendment Manager\"");
#line 773
 testRunner.And("I select \"<Target CRF Version1>\" from dropdown \"Source CRF\"");
#line 774
 testRunner.And("I select \"<Target CRF Version2>\" from dropdown \"Target CRF\"");
#line 775
 testRunner.And("I click button \"Create Plan\"");
#line 776
 testRunner.And("I navigate to \"Exceute Plan\"");
#line 777
 testRunner.And("I Migrate \"All Subjects\"");
#line 778
 testRunner.And("I select Migration Results and verify Job Status is set to Complete");
#line 779
 testRunner.And("I take a screenshot");
#line 781
 testRunner.And("I navigate to \"Home\"");
#line 782
 testRunner.And("I select \"AM Edit Check Study\"");
#line 783
 testRunner.And("I select site \"AM Edit Site\"");
#line 784
    testRunner.And("I select a subject \"sub802\"");
#line 785
 testRunner.And("I select Form \"Mixed Form\"");
#line 786
 testRunner.And("I verify new query did fire on \"Log Field 1\" field with require response on the f" +
                    "irst log line");
#line 787
 testRunner.And("I verify new query did fire on \"Log Field 1\" field with require response on the s" +
                    "econd log line");
#line 788
 testRunner.And("I take a screenshot");
#line 790
 testRunner.And("I select site \"AM Edit Site\"");
#line 791
    testRunner.And("I select a subject \"sub803\"");
#line 792
 testRunner.And("I select Form \"Mixed Form\"");
#line 793
 testRunner.And("I verify new query did fire on \"Log Field 1\" field with require response on the f" +
                    "irst log line");
#line 794
 testRunner.And("I verify new query did fire on \"Log Field 1\" field with require response on the s" +
                    "econd log line");
#line 795
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.9.1 When I run the Report, then query related data are displayed in the repo" +
            "rt. Publish Checks")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_9_1WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_PublishChecks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.9.1 When I run the Report, then query related data are displayed in the repo" +
                    "rt. Publish Checks", new string[] {
                        "release_564_Patch11",
                        "PB_8.9.1",
                        "Draft"});
#line 801
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 803
 testRunner.And("I navigate to \"Architect\"");
#line 804
 testRunner.And("I navigate to \"AM Edit Check Study\"");
#line 805
 testRunner.And("I navigate to \"Draft 1\"");
#line 806
 testRunner.And("I publish and push CRF Version");
#line 807
 testRunner.And("I note CRF Version \"<Publish CRF Version1>\"");
#line 808
 testRunner.And("I publish CRF Version");
#line 809
 testRunner.And("I note CRF Version \"<Publish CRF Version2>\"");
#line 810
 testRunner.And("I publish CRF Version");
#line 811
 testRunner.And("I note CRF Version \"<Publish CRF Version3>\"");
#line 813
 testRunner.And("I navigate to \"Home\"");
#line 814
 testRunner.And("I select \"AM Edit Check Study\"");
#line 815
 testRunner.And("I select site \"AM Edit Site\"");
#line hidden
            TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table66.AddRow(new string[] {
                        "Subject Number",
                        "{NextSubjectNum<num1>(Edit Check Study 8,prod,Subject Number)}"});
            table66.AddRow(new string[] {
                        "Subject Initials",
                        "sub804"});
#line 816
    testRunner.And("I create a Subject", ((string)(null)), table66);
#line 820
 testRunner.And("I select Form \"Mixed Form\"");
#line 821
 testRunner.And("I enter data in CRF and save");
#line hidden
            TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table67.AddRow(new string[] {
                        "Standard 1",
                        "6"});
            table67.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table67.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 822
testRunner.And("I save the CRF page", ((string)(null)), table67);
#line 827
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response");
#line 828
 testRunner.And("I take a screenshot");
#line 829
 testRunner.And("I answer the query on \"Log Field 1\" field");
#line 830
 testRunner.And("I save the CRF page");
#line 831
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 832
 testRunner.And("I save the CRF page");
#line 833
 testRunner.And("I take a screenshot");
#line 835
 testRunner.And("I navigate to \"Home\"");
#line 836
 testRunner.And("I navigate to \"Architect\"");
#line 837
 testRunner.And("I navigate to \"AM Edit Check Study\"");
#line 838
 testRunner.And("I navigate to \"Pulish Checks\"");
#line 839
 testRunner.And("I select \"<Publish CRF Version1>\" from dropdown \"Current CRF Version\"");
#line 840
 testRunner.And("I select \"<Publish CRF Version2>\" from dropdown \"Reference CRF Version\"");
#line 841
 testRunner.And("I click button \"Create Plan\"");
#line 842
 testRunner.And("I check \"Inactivate\" checkbox for \"Mixed Form Query\" edit check");
#line 843
 testRunner.And("I navigate to \"Save\"");
#line 844
 testRunner.And("I take a screenshot");
#line 845
 testRunner.And("I navigate to \"Publish\"");
#line 846
 testRunner.And("I verify Job Status is set to Complete");
#line 847
 testRunner.And("I take a screenshot");
#line 849
 testRunner.And("I navigate to \"Home\"");
#line 850
 testRunner.And("I select \"AM Edit Check Study\"");
#line 851
 testRunner.And("I select site \"AM Edit Site\"");
#line 852
    testRunner.And("I select a subject \"sub804\"");
#line 853
 testRunner.And("I select Form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table68.AddRow(new string[] {
                        "Standard 1",
                        "7"});
#line 854
 testRunner.And("I enter data in CRF and save", ((string)(null)), table68);
#line 857
 testRunner.And("I save the CRF page");
#line 858
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line 859
 testRunner.And("I take a screenshot");
#line 861
 testRunner.And("I navigate to \"Home\"");
#line 862
 testRunner.And("I navigate to \"Architect\"");
#line 863
 testRunner.And("I navigate to \"AM Edit Check Study\"");
#line 864
 testRunner.And("I navigate to \"Pulish Checks\"");
#line 865
 testRunner.And("I select \"<Publish CRF Version1>\" from dropdown \"Current CRF Version\"");
#line 866
 testRunner.And("I select \"<Publish CRF Version3>\" from dropdown \"Reference CRF Version\"");
#line 867
 testRunner.And("I click button \"Create Plan\"");
#line 868
 testRunner.And("I check \"Publish\" checkbox for \"Mixed Form Query\" edit check");
#line 869
 testRunner.And("I navigate to \"Save\"");
#line 870
 testRunner.And("I take a screenshot");
#line 871
 testRunner.And("I navigate to \"Publish\"");
#line 872
 testRunner.And("I verify Job Status is set to Complete");
#line 873
 testRunner.And("I take a screenshot");
#line 875
 testRunner.And("I navigate to \"Home\"");
#line 876
 testRunner.And("I select \"AM Edit Check Study\"");
#line 877
 testRunner.And("I select site \"AM Edit Site\"");
#line 878
    testRunner.And("I select a subject \"sub804\"");
#line 879
 testRunner.And("I select Form \"Mixed Form\"");
#line 880
 testRunner.And("I verify new query did fire on \"Log Field 1\" field");
#line 881
 testRunner.And("I answer the query on \"Log Field 1\" field");
#line 882
 testRunner.And("I save the CRF page");
#line 883
 testRunner.And("I take a screenshot");
#line 884
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 885
 testRunner.And("I save the CRF page");
#line 886
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table69.AddRow(new string[] {
                        "Standard 1",
                        "8"});
#line 887
 testRunner.And("I enter data in CRF and save", ((string)(null)), table69);
#line 890
 testRunner.And("I save the CRF page");
#line 891
 testRunner.And("I verify new query did fire on \"Log Field 1\" field.");
#line 892
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_8.10.1 When I run the Report, then query related data are displayed in the rep" +
            "ort. Queries verification on data points with Freeze, Hard lock and Inactive rec" +
            "ords")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "8")]
        public virtual void PB_8_10_1WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_QueriesVerificationOnDataPointsWithFreezeHardLockAndInactiveRecords()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_8.10.1 When I run the Report, then query related data are displayed in the rep" +
                    "ort. Queries verification on data points with Freeze, Hard lock and Inactive rec" +
                    "ords", new string[] {
                        "release_564_Patch11",
                        "PB_8.10.1",
                        "Draft"});
#line 898
this.ScenarioSetup(scenarioInfo);
#line 23
this.FeatureBackground();
#line 900
 testRunner.And("I select \"Edit Check Study 8\"");
#line 901
 testRunner.And("I select site \"Edit Check Site 8\"");
#line hidden
            TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table70.AddRow(new string[] {
                        "Subject Number",
                        "{NextSubjectNum<num1>(Edit Check Study 8,prod,Subject Number)}"});
            table70.AddRow(new string[] {
                        "Subject Initials",
                        "sub805"});
#line 902
    testRunner.And("I create a Subject", ((string)(null)), table70);
#line 906
 testRunner.And("I select Form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table71.AddRow(new string[] {
                        "Standard 1",
                        "6"});
            table71.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table71.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 907
 testRunner.And("I enter data in CRF and save", ((string)(null)), table71);
#line 912
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response on first" +
                    " record position");
#line 913
 testRunner.And("I take a screenshot");
#line 914
 testRunner.And("I add new log line 2");
#line hidden
            TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table72.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table72.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 915
 testRunner.And("I enter data in CRF and save", ((string)(null)), table72);
#line 919
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response on secon" +
                    "d record position");
#line 920
 testRunner.And("I take a screenshot");
#line 921
 testRunner.And("I add new log line 3");
#line hidden
            TechTalk.SpecFlow.Table table73 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table73.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table73.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 922
 testRunner.And("I enter data in CRF and save", ((string)(null)), table73);
#line 926
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response on third" +
                    " record position");
#line 927
 testRunner.And("I take a screenshot");
#line 929
 testRunner.And("I answer the query on \"Log Field 1\" field on first record position");
#line 930
 testRunner.And("I save the CRF page");
#line 931
 testRunner.And("I answer the query on \"Log Field 1\" field on seond record position");
#line 932
 testRunner.And("I save the CRF page");
#line 933
 testRunner.And("I answer the query on \"Log Field 1\" field on third record position");
#line 934
 testRunner.And("I save the CRF page");
#line hidden
            TechTalk.SpecFlow.Table table74 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table74.AddRow(new string[] {
                        "Log Field 1",
                        "6"});
#line 936
 testRunner.And("I enter data in CRF and save", ((string)(null)), table74);
#line 939
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 940
 testRunner.And("I save the CRF page");
#line 941
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table75 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table75.AddRow(new string[] {
                        "Log Field 1",
                        "6"});
#line 942
 testRunner.And("I enter data in CRF and save", ((string)(null)), table75);
#line 945
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 946
 testRunner.And("I save the CRF page");
#line 947
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table76 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table76.AddRow(new string[] {
                        "Log Field 1",
                        "6"});
#line 948
 testRunner.And("I enter data in CRF and save", ((string)(null)), table76);
#line 951
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 952
 testRunner.And("I save the CRF page");
#line 953
 testRunner.And("I take a screenshot");
#line 955
 testRunner.And("I select edit icon on first record position");
#line 956
 testRunner.And("I select checkbox \"Freeze\" on \"Log Field 1\" field on first record position");
#line 957
 testRunner.And("I save the CRF page");
#line 958
 testRunner.And("I select edit icon on second record position");
#line 959
 testRunner.And("I select checkbox \"Hadrd Lock\" on \"Log Field 1\" field on second record position");
#line 960
 testRunner.And("I save the CRF page");
#line 961
 testRunner.And("I navigate to \"Inactivate\"");
#line 962
 testRunner.And("I select \"3\" in dropdown");
#line 963
 testRunner.And("I select \"Inactivate\" button");
#line 964
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table77 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table77.AddRow(new string[] {
                        "Standard 1",
                        "7"});
#line 966
 testRunner.And("I enter data in CRF and save", ((string)(null)), table77);
#line 969
 testRunner.And("I save the CRF page");
#line 970
 testRunner.And("I verify new query did fire on \"Log Field 1\" field on first record position");
#line 971
 testRunner.And("I take a screenshot");
#line 972
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field on second record position");
#line 973
 testRunner.And("I take a screenshot");
#line 974
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field on third record position");
#line 975
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
