// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Medidata.RBT.Features.Rave.Features.EDC
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UpdatedTabOrderToEnableMouselessDataEntry_UntouchedLandscapeLogFormWithSetLogLinesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EDCTabOrderUntouchedSetLogForm.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
                    "ith set log lines", "As A Rave EDC User\nI want to tab from field to field \nSo that I can enter data wi" +
                    "thout using a mouse", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
                            "ith set log lines")))
            {
                Medidata.RBT.Features.Rave.Features.EDC.UpdatedTabOrderToEnableMouselessDataEntry_UntouchedLandscapeLogFormWithSetLogLinesFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 15
#line 16
 testRunner.Given("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 17
 testRunner.And("I select Study \"Standard Study\" and Site \"Site 1\"");
#line 18
 testRunner.And("I select a Subject \"777777779{Var(num1)}\"");
#line 19
 testRunner.Given("I select link \"Log Form Landscape (Set)\" located in \"Left Nav\"");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The cursor begins in the data entry position for the first field on the page when" +
            " I click on the page from the left-hand side menu.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-01c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WIP")]
        public virtual void TheCursorBeginsInTheDataEntryPositionForTheFirstFieldOnThePageWhenIClickOnThePageFromTheLeft_HandSideMenu_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The cursor begins in the data entry position for the first field on the page when" +
                    " I click on the page from the left-hand side menu.", new string[] {
                        "release_2012.1.0",
                        "US11550-01c",
                        "WIP"});
#line 60
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 61
 testRunner.Then("the cursor focus is located on \"textbox\" in the column labeled \"Field Label 1\" in" +
                    " the \"first\" position in the \"first\" row");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The cursor moves from one field to the next when the user hits the tab key and ig" +
            "nores help text.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-02c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WIP")]
        public virtual void TheCursorMovesFromOneFieldToTheNextWhenTheUserHitsTheTabKeyAndIgnoresHelpText_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The cursor moves from one field to the next when the user hits the tab key and ig" +
                    "nores help text.", new string[] {
                        "release_2012.1.0",
                        "US11550-02c",
                        "WIP"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 67
 testRunner.When("I hit \"tab\" key");
#line 68
 testRunner.Then("the cursor focus is located on \"datetime\" in the column labeled \"Field Label 2\" i" +
                    "n the \"first\" position in the \"first\" row");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The cursor moves from one field to the next when the user hits the tab key and ig" +
            "nores other non-enterable fields.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-03c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void TheCursorMovesFromOneFieldToTheNextWhenTheUserHitsTheTabKeyAndIgnoresOtherNon_EnterableFields_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The cursor moves from one field to the next when the user hits the tab key and ig" +
                    "nores other non-enterable fields.", new string[] {
                        "release_2012.1.0",
                        "US11550-03c",
                        "Draft"});
#line 73
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 74
 testRunner.Given("move cursor focus to \"textbox\" in the column labeled \"Field Label 16\" in the \"fir" +
                    "st\" position in the \"first\" row");
#line 75
 testRunner.When("I hit \"tab\" key");
#line 76
 testRunner.Then("the cursor focus is located on \"textbox\" in the column labeled \"Field Label 18\" i" +
                    "n the \"first\" position in the \"first\" row");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The cursor moves through all data entry input elements in a datetime field before" +
            " moving to the next field.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-04c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WIP")]
        public virtual void TheCursorMovesThroughAllDataEntryInputElementsInADatetimeFieldBeforeMovingToTheNextField_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The cursor moves through all data entry input elements in a datetime field before" +
                    " moving to the next field.", new string[] {
                        "release_2012.1.0",
                        "US11550-04c",
                        "WIP"});
#line 81
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 82
 testRunner.Given("move cursor focus to \"datetime\" in the column labeled \"Field Label 2\" in the \"fir" +
                    "st\" position in the \"first\" row");
#line 83
 testRunner.When("I hit \"tab\" key");
#line 84
 testRunner.Then("the cursor focus is located on \"datetime\" in the column labeled \"Field Label 2\" i" +
                    "n the \"second\" position in the \"first\" row");
#line 85
 testRunner.When("I hit \"tab\" key");
#line 86
 testRunner.Then("the cursor focus is located on \"datetime\" in the column labeled \"Field Label 2\" i" +
                    "n the \"third\" position in the \"first\" row");
#line 87
 testRunner.When("I hit \"tab\" key");
#line 88
 testRunner.Then("the cursor focus is located on \"datetime\" in the column labeled \"Field Label 2\" i" +
                    "n the \"fourth\" position in the \"first\" row");
#line 89
 testRunner.When("I hit \"tab\" key");
#line 90
 testRunner.Then("the cursor focus is located on \"datetime\" in the column labeled \"Field Label 2\" i" +
                    "n the \"fifth\" position in the \"first\" row");
#line 91
 testRunner.When("I hit \"tab\" key");
#line 92
 testRunner.Then("the cursor focus is located on \"datetime\" in the column labeled \"Field Label 2\" i" +
                    "n the \"sixth\" position in the \"first\" row");
#line 93
 testRunner.When("I hit \"tab\" key");
#line 94
 testRunner.Then("the cursor focus is located on \"dropdown\" in the column labeled \"Field Label 3\" i" +
                    "n the \"first\" position in the \"first\" row");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The cursor moves through all options in a radio button (horizontal).")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-05c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WIP")]
        public virtual void TheCursorMovesThroughAllOptionsInARadioButtonHorizontal_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The cursor moves through all options in a radio button (horizontal).", new string[] {
                        "release_2012.1.0",
                        "US11550-05c",
                        "WIP"});
#line 99
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 100
 testRunner.Given("move cursor focus to \"radiobutton\" in the column labeled \"Field Label 7\" in the \"" +
                    "first\" position in the \"first\" row");
#line 101
 testRunner.When("I hit \"tab\" key");
#line 102
 testRunner.Then("the cursor focus is located on \"radiobutton\" in the column labeled \"Field Label 7" +
                    "\" in the \"second\" position in the \"first\" row");
#line 103
 testRunner.When("I hit \"tab\" key");
#line 104
 testRunner.Then("the cursor focus is located on \"radiobutton\" in the column labeled \"Field Label 7" +
                    "\" in the \"third\" position in the \"first\" row");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The cursor moves through all options in a radio button (vertical).")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-06c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void TheCursorMovesThroughAllOptionsInARadioButtonVertical_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The cursor moves through all options in a radio button (vertical).", new string[] {
                        "release_2012.1.0",
                        "US11550-06c",
                        "Draft"});
#line 109
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 110
 testRunner.Given("move cursor focus to \"radiobutton vertical\" in the column labeled \"Field Label 8\"" +
                    " in the \"first\" position in the \"first\" row");
#line 111
 testRunner.When("I hit \"tab\" key");
#line 112
 testRunner.Then("the cursor focus is located on \"radiobutton vertical\" in the column labeled \"Fiel" +
                    "d Label 8\" in the \"second\" position in the \"first\" row");
#line 113
 testRunner.When("I hit \"tab\" key");
#line 114
 testRunner.Then("the cursor focus is located on \"radiobutton vertical\" in the column labeled \"Fiel" +
                    "d Label 8\" in the \"third\" position in the \"first\" row");
#line 115
 testRunner.When("I hit \"tab\" key");
#line 116
 testRunner.Then("the cursor focus is located on \"specify textbox\" in the column labeled \"Field Lab" +
                    "el 8\" in the \"fourth\" position in the \"first\" row");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The cursor moves through all data entry input elements for a field associated wit" +
            "h a unit dictionary before moving to the next field.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-07c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WIP")]
        public virtual void TheCursorMovesThroughAllDataEntryInputElementsForAFieldAssociatedWithAUnitDictionaryBeforeMovingToTheNextField_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The cursor moves through all data entry input elements for a field associated wit" +
                    "h a unit dictionary before moving to the next field.", new string[] {
                        "release_2012.1.0",
                        "US11550-07c",
                        "WIP"});
#line 121
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 122
 testRunner.Given("move cursor focus to \"textbox\" in the column labeled \"Field Label 14\" in the \"fir" +
                    "st\" position in the \"first\" row");
#line 123
 testRunner.When("I hit \"tab\" key");
#line 124
 testRunner.Then("the cursor focus is located on \"unit dictionary\" in the column labeled \"Field Lab" +
                    "el 14\" in the \"second\" position in the \"first\" row");
#line 125
 testRunner.When("I hit \"tab\" key");
#line 126
 testRunner.Then("the cursor focus is located on \"textbox\" in the column labeled \"Field Label 15\" i" +
                    "n the \"first\" position in the \"first\" row");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The screen scrolls to the right when the eCRF is longer than the width of the scr" +
            "een and I tab away from the last visible field.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-08c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WIP")]
        public virtual void TheScreenScrollsToTheRightWhenTheECRFIsLongerThanTheWidthOfTheScreenAndITabAwayFromTheLastVisibleField_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The screen scrolls to the right when the eCRF is longer than the width of the scr" +
                    "een and I tab away from the last visible field.", new string[] {
                        "release_2012.1.0",
                        "US11550-08c",
                        "WIP"});
#line 131
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 132
 testRunner.Given("move cursor focus to \"browser file upload button\" in the column labeled \"Field La" +
                    "bel 5\" in the \"first\" position in the \"first\" row");
#line 133
 testRunner.When("I hit \"tab\" key");
#line 134
 testRunner.Then("the cursor focus is located on \"textbox\" in the column labeled \"Field Label 6\" in" +
                    " the \"first\" position in the \"first\" row");
#line 135
 testRunner.And("the browser scrolls to the right");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("When I tab away from the last field of a log line and there is one or more additi" +
            "onal log lines to be filled, I should tab to the first field of the next log lin" +
            "e.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-09c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WIP")]
        public virtual void WhenITabAwayFromTheLastFieldOfALogLineAndThereIsOneOrMoreAdditionalLogLinesToBeFilledIShouldTabToTheFirstFieldOfTheNextLogLine_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When I tab away from the last field of a log line and there is one or more additi" +
                    "onal log lines to be filled, I should tab to the first field of the next log lin" +
                    "e.", new string[] {
                        "release_2012.1.0",
                        "US11550-09c",
                        "WIP"});
#line 140
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 141
 testRunner.Given("move cursor focus to \"textbox\" in the column labeled \"Field Label 18\" in the \"fir" +
                    "st\" position in the \"first\" row");
#line 142
 testRunner.When("I hit \"tab\" key");
#line 143
 testRunner.Then("the cursor focus is located on \"textbox\" in the column labeled \"Field Label 1\" in" +
                    " the \"first\" position in the \"second\" row");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("When I tab away from the last field of the last log line, I should tab to the sav" +
            "e button.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Updated tab order to enable mouseless data entry - Untouched landscape log form w" +
            "ith set log lines")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11550-10c")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WIP")]
        public virtual void WhenITabAwayFromTheLastFieldOfTheLastLogLineIShouldTabToTheSaveButton_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When I tab away from the last field of the last log line, I should tab to the sav" +
                    "e button.", new string[] {
                        "release_2012.1.0",
                        "US11550-10c",
                        "WIP"});
#line 149
this.ScenarioSetup(scenarioInfo);
#line 15
this.FeatureBackground();
#line 150
 testRunner.Given("move cursor focus to \"textbox\" in the column labeled \"Field Label 18\" in the \"fir" +
                    "st\" position in the \"third\" row");
#line 151
 testRunner.When("I hit \"tab\" key");
#line 152
 testRunner.Then("the cursor focus is on \"button\" labeled \"Save\"");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
