// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Medidata.RBT.Features.Rave.Features.EDC
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class US10246_DT13300Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "US10246_DT13300.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "US10246_DT13300", @"The month component of the date in a date field, and the meridian component of the time in a time field, should be displayed in uppercase when All Upper Case is selected in Configuration and Locale is set to Japanese
As a Rave Administrator
When I have selected All Upper Case in Configuration > Other Settings
And my Locale is set to Japanese in My Profile
And I enter data for datetime fields
Then the month component of the date in all date fields should be in uppercase
And the meridian component of the time in all time fields should be in uppercase", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "US10246_DT13300")))
            {
                Medidata.RBT.Features.Rave.Features.EDC.US10246_DT13300Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 12
 #line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@PB_US10246_DT13300_01 As a Study Coordinator, when I save the month into a date " +
            "field, and the time into a time field, then I see the month and meridian display" +
            "ed in uppercase.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "US10246_DT13300")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PB_US10246_DT13300_01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Validation")]
        public virtual void PB_US10246_DT13300_01AsAStudyCoordinatorWhenISaveTheMonthIntoADateFieldAndTheTimeIntoATimeFieldThenISeeTheMonthAndMeridianDisplayedInUppercase_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@PB_US10246_DT13300_01 As a Study Coordinator, when I save the month into a date " +
                    "field, and the time into a time field, then I see the month and meridian display" +
                    "ed in uppercase.", new string[] {
                        "release_2012.1.0",
                        "PB_US10246_DT13300_01",
                        "Validation"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 12
 this.FeatureBackground();
#line 40
 testRunner.When("I am logged in to Rave with username \"defjapan\" and password \"password\"");
#line 41
 testRunner.And("I select Study \"US10246_DT13300_SJ\" and Site \"Site 1\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Control Type"});
            table1.AddRow(new string[] {
                        "Subject Identifier",
                        "SUB {RndNum<num1>(3)}",
                        "text"});
#line 42
 testRunner.And("I create a Subject", ((string)(null)), table1);
#line 46
 testRunner.And("I select Form \"Device Form\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Control Type"});
            table2.AddRow(new string[] {
                        "Device Implant Date 1",
                        "UN",
                        "datetime"});
            table2.AddRow(new string[] {
                        "Device Implant Date 2",
                        "Jul",
                        "datetime"});
            table2.AddRow(new string[] {
                        "Device Implant Date 3",
                        "UNK",
                        "datetime"});
            table2.AddRow(new string[] {
                        "Device Implant Date 4",
                        "12 Jul 1972",
                        "datetime"});
            table2.AddRow(new string[] {
                        "Device Implant Date 5",
                        "UN Jul 1972",
                        "datetime"});
            table2.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 UNK 1972",
                        "datetime"});
            table2.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN UNK 1972",
                        "datetime"});
            table2.AddRow(new string[] {
                        "Device Implant Date 8",
                        "UN 07 1972",
                        "datetime"});
            table2.AddRow(new string[] {
                        "Device Implant Date 9",
                        "UN UN 1972",
                        "datetime"});
            table2.AddRow(new string[] {
                        "Device Implant Time",
                        "11:59 am",
                        "datetime"});
#line 47
 testRunner.And("I enter data in CRF and save", ((string)(null)), table2);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table3.AddRow(new string[] {
                        "Device Implant Date 1",
                        "UN"});
            table3.AddRow(new string[] {
                        "Device Implant Date 2",
                        "JUL"});
            table3.AddRow(new string[] {
                        "Device Implant Date 3",
                        "UNK"});
            table3.AddRow(new string[] {
                        "Device Implant Date 4",
                        "12 JUL 1972"});
            table3.AddRow(new string[] {
                        "Device Implant Date 5",
                        "UN JUL 1972"});
            table3.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 UNK 1972"});
            table3.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN UNK 1972"});
            table3.AddRow(new string[] {
                        "Device Implant Date 8",
                        "UN 07 1972"});
            table3.AddRow(new string[] {
                        "Device Implant Date 9",
                        "UN UN 1972"});
            table3.AddRow(new string[] {
                        "Device Implant Time",
                        "11:59 AM"});
#line 59
 testRunner.Then("I should see data for fields in CRF", ((string)(null)), table3);
#line 71
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@PB_US10246_DT13300_02 As a Study Coordinator, I save an unknown month. When I ed" +
            "it the form and save a month, then I see the month displayed in uppercase.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "US10246_DT13300")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PB_US10246_DT13300_02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Validation")]
        public virtual void PB_US10246_DT13300_02AsAStudyCoordinatorISaveAnUnknownMonth_WhenIEditTheFormAndSaveAMonthThenISeeTheMonthDisplayedInUppercase_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@PB_US10246_DT13300_02 As a Study Coordinator, I save an unknown month. When I ed" +
                    "it the form and save a month, then I see the month displayed in uppercase.", new string[] {
                        "release_2012.1.0",
                        "PB_US10246_DT13300_02",
                        "Validation"});
#line 76
this.ScenarioSetup(scenarioInfo);
#line 12
 this.FeatureBackground();
#line 78
 testRunner.When("I am logged in to Rave with username \"defjapan\" and password \"password\"");
#line 79
 testRunner.And("I select Study \"US10246_DT13300_SJ\" and Site \"Site 1\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table4.AddRow(new string[] {
                        "Subject Identifier",
                        "SUB {RndNum<num1>(3)}"});
#line 80
 testRunner.And("I create a Subject", ((string)(null)), table4);
#line 83
 testRunner.And("I select Form \"Device Form\"");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Control Type"});
            table5.AddRow(new string[] {
                        "Device Implant Date 1",
                        "UN",
                        "datetime"});
            table5.AddRow(new string[] {
                        "Device Implant Date 2",
                        "Jul",
                        "datetime"});
            table5.AddRow(new string[] {
                        "Device Implant Date 3",
                        "UNK",
                        "datetime"});
            table5.AddRow(new string[] {
                        "Device Implant Date 4",
                        "12 Jul 1972",
                        "datetime"});
            table5.AddRow(new string[] {
                        "Device Implant Date 5",
                        "UN Jul 1972",
                        "datetime"});
            table5.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 UNK 1972",
                        "datetime"});
            table5.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN UNK 1972",
                        "datetime"});
            table5.AddRow(new string[] {
                        "Device Implant Date 8",
                        "UN 07 1972",
                        "datetime"});
            table5.AddRow(new string[] {
                        "Device Implant Date 9",
                        "UN UN 1972",
                        "datetime"});
            table5.AddRow(new string[] {
                        "Device Implant Time",
                        "11:59 am",
                        "datetime"});
#line 84
 testRunner.And("I enter data in CRF and save", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table6.AddRow(new string[] {
                        "Device Implant Date 1",
                        "UN"});
            table6.AddRow(new string[] {
                        "Device Implant Date 2",
                        "JUL"});
            table6.AddRow(new string[] {
                        "Device Implant Date 3",
                        "UNK"});
            table6.AddRow(new string[] {
                        "Device Implant Date 4",
                        "12 JUL 1972"});
            table6.AddRow(new string[] {
                        "Device Implant Date 5",
                        "UN JUL 1972"});
            table6.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 UNK 1972"});
            table6.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN UNK 1972"});
            table6.AddRow(new string[] {
                        "Device Implant Date 8",
                        "UN 07 1972"});
            table6.AddRow(new string[] {
                        "Device Implant Date 9",
                        "UN UN 1972"});
            table6.AddRow(new string[] {
                        "Device Implant Time",
                        "11:59 AM"});
#line 96
 testRunner.Then("I should see data for fields in CRF", ((string)(null)), table6);
#line 108
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table7.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 Jul 1972"});
            table7.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN Jul 1972"});
#line 109
 testRunner.And("I enter data in CRF and save", ((string)(null)), table7);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table8.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 JUL 1972"});
            table8.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN JUL 1972"});
#line 113
 testRunner.Then("I should see data for fields in CRF", ((string)(null)), table8);
#line 117
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute(@"@PB_US10246_DT13300_03  As a Study Coordinator, My Profile > Locale is set to English. when I save the month into a date field, and the time into a time field, then I see the month and meridian displayed in uppercase. When I set My Profile > Locale to Japanese, and I edit the form and save a new month and new meridian, then I see the month and meridian displayed in uppercase.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "US10246_DT13300")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PB_US10246_DT13300_03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Validation")]
        public virtual void PB_US10246_DT13300_03AsAStudyCoordinatorMyProfileLocaleIsSetToEnglish_WhenISaveTheMonthIntoADateFieldAndTheTimeIntoATimeFieldThenISeeTheMonthAndMeridianDisplayedInUppercase_WhenISetMyProfileLocaleToJapaneseAndIEditTheFormAndSaveANewMonthAndNewMeridianThenISeeTheMonthAndMeridianDisplayedInUppercase_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo(@"@PB_US10246_DT13300_03  As a Study Coordinator, My Profile > Locale is set to English. when I save the month into a date field, and the time into a time field, then I see the month and meridian displayed in uppercase. When I set My Profile > Locale to Japanese, and I edit the form and save a new month and new meridian, then I see the month and meridian displayed in uppercase.", new string[] {
                        "release_2012.1.0",
                        "PB_US10246_DT13300_03",
                        "Validation"});
#line 122
this.ScenarioSetup(scenarioInfo);
#line 12
 this.FeatureBackground();
#line 124
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 125
 testRunner.And("I select Study \"US10246_DT13300_SJ\" and Site \"Site 1\"");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table9.AddRow(new string[] {
                        "Subject Identifier",
                        "SUB {RndNum<num1>(3)}"});
#line 126
 testRunner.And("I create a Subject", ((string)(null)), table9);
#line 129
 testRunner.And("I select Form \"Device Form\"");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Control Type"});
            table10.AddRow(new string[] {
                        "Device Implant Date 1",
                        "UN",
                        "datetime"});
            table10.AddRow(new string[] {
                        "Device Implant Date 2",
                        "Jul",
                        "datetime"});
            table10.AddRow(new string[] {
                        "Device Implant Date 3",
                        "UNK",
                        "datetime"});
            table10.AddRow(new string[] {
                        "Device Implant Date 4",
                        "12 Jul 1972",
                        "datetime"});
            table10.AddRow(new string[] {
                        "Device Implant Date 5",
                        "UN Jul 1972",
                        "datetime"});
            table10.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 UNK 1972",
                        "datetime"});
            table10.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN UNK 1972",
                        "datetime"});
            table10.AddRow(new string[] {
                        "Device Implant Date 8",
                        "UN 07 1972",
                        "datetime"});
            table10.AddRow(new string[] {
                        "Device Implant Date 9",
                        "UN UN 1972",
                        "datetime"});
            table10.AddRow(new string[] {
                        "Device Implant Time",
                        "11:59 am",
                        "datetime"});
#line 130
 testRunner.And("I enter data in CRF and save", ((string)(null)), table10);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table11.AddRow(new string[] {
                        "Device Implant Date 1",
                        "UN"});
            table11.AddRow(new string[] {
                        "Device Implant Date 2",
                        "JUL"});
            table11.AddRow(new string[] {
                        "Device Implant Date 3",
                        "UNK"});
            table11.AddRow(new string[] {
                        "Device Implant Date 4",
                        "12 JUL 1972"});
            table11.AddRow(new string[] {
                        "Device Implant Date 5",
                        "UN JUL 1972"});
            table11.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 UNK 1972"});
            table11.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN UNK 1972"});
            table11.AddRow(new string[] {
                        "Device Implant Date 8",
                        "UN 07 1972"});
            table11.AddRow(new string[] {
                        "Device Implant Date 9",
                        "UN UN 1972"});
            table11.AddRow(new string[] {
                        "Device Implant Time",
                        "11:59 AM"});
#line 142
 testRunner.Then("I should see data for fields in CRF", ((string)(null)), table11);
#line 154
 testRunner.And("I take a screenshot");
#line 155
 testRunner.And("I am logged in to Rave with username \"defjapan\" and password \"password\"");
#line 156
 testRunner.And("I select Study \"US10246_DT13300_SJ\" and Site \"Site 1\"");
#line 157
 testRunner.And("I select a Subject \"SUB {Var(num1)}\"");
#line 158
 testRunner.And("I select Form \"Device Form\"");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Control Type"});
            table12.AddRow(new string[] {
                        "Device Implant Date 2",
                        "Aug",
                        "datetime"});
            table12.AddRow(new string[] {
                        "Device Implant Date 4",
                        "12 Aug 1972",
                        "datetime"});
            table12.AddRow(new string[] {
                        "Device Implant Date 5",
                        "UN Aug 1972",
                        "datetime"});
            table12.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 Aug 1972",
                        "datetime"});
            table12.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN Aug 1972",
                        "datetime"});
            table12.AddRow(new string[] {
                        "Device Implant Time",
                        "11:59 pm",
                        "datetime"});
#line 159
 testRunner.And("I enter data in CRF and save", ((string)(null)), table12);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table13.AddRow(new string[] {
                        "Device Implant Date 2",
                        "AUG"});
            table13.AddRow(new string[] {
                        "Device Implant Date 4",
                        "12 AUG 1972"});
            table13.AddRow(new string[] {
                        "Device Implant Date 5",
                        "UN AUG 1972"});
            table13.AddRow(new string[] {
                        "Device Implant Date 6",
                        "12 AUG 1972"});
            table13.AddRow(new string[] {
                        "Device Implant Date 7",
                        "UN AUG 1972"});
            table13.AddRow(new string[] {
                        "Device Implant Time",
                        "11:59 PM"});
#line 167
 testRunner.Then("I should see data for fields in CRF", ((string)(null)), table13);
#line 175
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
