// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Medidata.RBT.Features.Rave.Features.EDC
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DisablingEnablingAddEventsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "US11547_DT11148_DisableAddEvents.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Disabling/Enabling Add Events", "As a data manager\nI want to be able to disable and reenable Add Events\nSo that I " +
                    "can decide when a study coordinator can add new folders to a subject", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Disabling/Enabling Add Events")))
            {
                Medidata.RBT.Features.Rave.Features.EDC.DisablingEnablingAddEventsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 13
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-01 By default, the Add Event feature should be available for a subject w" +
            "hen one or more matrices/folders can be added for a study.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_01ByDefaultTheAddEventFeatureShouldBeAvailableForASubjectWhenOneOrMoreMatricesFoldersCanBeAddedForAStudy_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-01 By default, the Add Event feature should be available for a subject w" +
                    "hen one or more matrices/folders can be added for a study.", new string[] {
                        "release_2012.1.0",
                        "US11547-01",
                        "Draft"});
#line 65
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 66
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 67
    testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 68
 testRunner.And("I select a Subject \"SUB004\"");
#line 69
 testRunner.When("The \"Disable\" button is available");
#line 70
 testRunner.Then("I can see \"enabled\" dropdown labeled \"Add Event\"");
#line 71
 testRunner.And("I can see \"Add\" button");
#line 72
 testRunner.And("I take a screenshot");
#line 73
 testRunner.When("I select \"Grid View\"");
#line 74
 testRunner.Then("I can see \"enabled\" dropdown labeled \"Add Event\"");
#line 75
 testRunner.And("I can see \"Add\" button");
#line 76
 testRunner.And("I take a screenshot");
#line 77
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-02 A user with lock permission can see the disable add event button on t" +
            "he subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_02AUserWithLockPermissionCanSeeTheDisableAddEventButtonOnTheSubjectHomePage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-02 A user with lock permission can see the disable add event button on t" +
                    "he subject home page.", new string[] {
                        "release_2012.1.0",
                        "US11547-02",
                        "Draft"});
#line 82
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 83
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 84
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 85
 testRunner.And("I select a Subject \"SUB004\"");
#line 86
 testRunner.When("The \"Disable\" button is available");
#line 87
 testRunner.Then("I can see \"Disable\" button");
#line 88
 testRunner.And("I take a screenshot");
#line 89
 testRunner.And("I log out of Rave");
#line 90
 testRunner.When("I am logged in to Rave with username \"cdm1\" and password \"password\"");
#line 91
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 92
 testRunner.And("I select a Subject \"SUB004\"");
#line 93
 testRunner.Then("I can see \"Disable\" button");
#line 94
 testRunner.And("I take a screenshot");
#line 95
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void US11547_03AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectHomePage_(string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "release_2012.1.0",
                    "US11547-03",
                    "Draft"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-03 A user without lock permission cannot see the disable add event butto" +
                    "n on the subject home page.", @__tags);
#line 100
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 101
 testRunner.When(string.Format("I am logged in to Rave with username \"{0}\" and password \"{1}\"", userName, password));
#line 102
    testRunner.When("I select Study \"Study A\" and Site \"Site A1\"");
#line 103
 testRunner.And("I select a Subject \"SUB004\"");
#line 104
 testRunner.Then("I can not see \"Disable\" button");
#line 105
 testRunner.And("I take a screenshot");
#line 106
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-03 A user without lock permission cannot see the disable add event butto" +
            "n on the subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "cdm2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "cdm2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_03AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectHomePage__Cdm2()
        {
            this.US11547_03AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectHomePage_("cdm2", "password", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-03 A user without lock permission cannot see the disable add event butto" +
            "n on the subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "siteuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "siteuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_03AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectHomePage__Siteuser()
        {
            this.US11547_03AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectHomePage_("siteuser", "password", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-04 The \"Disable Add Events\" tooltip displays when a user hovers over the" +
            " disable add event button on the subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_04TheDisableAddEventsTooltipDisplaysWhenAUserHoversOverTheDisableAddEventButtonOnTheSubjectHomePage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-04 The \"Disable Add Events\" tooltip displays when a user hovers over the" +
                    " disable add event button on the subject home page.", new string[] {
                        "release_2012.1.0",
                        "US11547-04",
                        "Draft"});
#line 116
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 117
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 118
    testRunner.When("I select Study \"Study A\" and Site \"Site A1\"");
#line 119
 testRunner.And("I select a Subject \"SUB004\"");
#line 120
 testRunner.When("The \"Disable\" button is available");
#line 121
 testRunner.Then("I can see tooltip \"Disable Add Events\" on button labeled \"Disable\"");
#line 122
 testRunner.And("I take a screenshot");
#line 123
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-05 Clicking on the disable add event button disables the Add Event featu" +
            "re on the subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-05")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_05ClickingOnTheDisableAddEventButtonDisablesTheAddEventFeatureOnTheSubjectHomePage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-05 Clicking on the disable add event button disables the Add Event featu" +
                    "re on the subject home page.", new string[] {
                        "release_2012.1.0",
                        "US11547-05",
                        "Draft"});
#line 128
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 129
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 130
 testRunner.When("I select Study \"Study A\" and Site \"Site A1\"");
#line 131
 testRunner.And("I select a Subject \"SUB004\"");
#line 132
 testRunner.When("The \"Disable\" button is available");
#line 133
 testRunner.And("I take a screenshot");
#line 134
 testRunner.When("I click button \"Disable\"");
#line 135
 testRunner.Then("I can see \"disabled\" dropdown labeled \"Add Event\"");
#line 136
 testRunner.And("I can not see \"Add\" button");
#line 137
 testRunner.And("I can not see \"Disable\" button");
#line 138
 testRunner.And("I take a screenshot");
#line 139
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-06 A user should not be able to add event if the Add Event feature is di" +
            "sabled on the subject home page. A lock icon, indicating that the Add Event feat" +
            "ure is disabled, should display next to the Add Event dropdown if the user has E" +
            "ntry rights.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-06")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_06AUserShouldNotBeAbleToAddEventIfTheAddEventFeatureIsDisabledOnTheSubjectHomePage_ALockIconIndicatingThatTheAddEventFeatureIsDisabledShouldDisplayNextToTheAddEventDropdownIfTheUserHasEntryRights_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-06 A user should not be able to add event if the Add Event feature is di" +
                    "sabled on the subject home page. A lock icon, indicating that the Add Event feat" +
                    "ure is disabled, should display next to the Add Event dropdown if the user has E" +
                    "ntry rights.", new string[] {
                        "release_2012.1.0",
                        "US11547-06",
                        "Draft"});
#line 145
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 146
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 147
 testRunner.When("I select Study \"Study A\" and Site \"Site A1\"");
#line 148
 testRunner.And("I select a Subject \"SUB004\"");
#line 149
 testRunner.When("The \"Disable\" button is available");
#line 150
 testRunner.When("I click button \"Disable\"");
#line 151
 testRunner.And("I take a screenshot");
#line 152
 testRunner.And("I log out of Rave");
#line 153
 testRunner.When("I am logged in to Rave with username \"cdm1\" and password \"password\"");
#line 154
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 155
 testRunner.And("I select a Subject \"SUB004\"");
#line 156
 testRunner.Then("I can see \"disabled\" dropdown labeled \"Add Event\"");
#line 157
 testRunner.And("I can not see \"Add\" button");
#line 158
 testRunner.And("I can see Add Event lock icon");
#line 159
 testRunner.And("I take a screenshot");
#line 160
 testRunner.Then("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-07 A user with unlock permission can see the enable add event button on " +
            "the subject home page only when the Add Event feature is disabled.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-07")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_07AUserWithUnlockPermissionCanSeeTheEnableAddEventButtonOnTheSubjectHomePageOnlyWhenTheAddEventFeatureIsDisabled_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-07 A user with unlock permission can see the enable add event button on " +
                    "the subject home page only when the Add Event feature is disabled.", new string[] {
                        "release_2012.1.0",
                        "US11547-07",
                        "Draft"});
#line 165
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 166
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 167
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 168
 testRunner.And("I select a Subject \"SUB004\"");
#line 169
 testRunner.And("The \"Disable\" button is available");
#line 170
 testRunner.When("I click button \"Disable\"");
#line 171
 testRunner.And("I take a screenshot");
#line 172
 testRunner.And("I log out of Rave");
#line 173
 testRunner.When("I am logged in to Rave with username \"cdm2\" and password \"password\"");
#line 174
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 175
 testRunner.And("I select a Subject \"SUB004\"");
#line 176
 testRunner.Then("I can see \"Enable\" button");
#line 177
 testRunner.And("I take a screenshot");
#line 178
 testRunner.And("I log out of Rave");
#line 179
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 180
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 181
 testRunner.And("I select a Subject \"SUB005\"");
#line 182
 testRunner.And("The \"Enable\" button is available");
#line 183
 testRunner.And("I take a screenshot");
#line 184
 testRunner.When("I click button \"Enable\"");
#line 185
 testRunner.And("I take a screenshot");
#line 186
 testRunner.And("I log out of Rave");
#line 187
 testRunner.When("I am logged in to Rave with username \"cdm2\" and password \"password\"");
#line 188
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 189
 testRunner.And("I select a Subject \"SUB005\"");
#line 190
 testRunner.Then("I can not see \"Enable\" button");
#line 191
 testRunner.And("I take a screenshot");
#line 192
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void US11547_08AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectHomePage_(string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "release_2012.1.0",
                    "US11547-08",
                    "Draft"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-08 A user without unlock permission cannot see the enable add event butt" +
                    "on on the subject home page.", @__tags);
#line 198
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 199
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 200
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 201
 testRunner.And("I select a Subject \"SUB004\"");
#line 202
 testRunner.And("The \"Enable\" button is available");
#line 203
 testRunner.And("I take a screenshot");
#line 204
 testRunner.And("I log out of Rave");
#line 205
 testRunner.When(string.Format("I am logged in to Rave with username \"{0}\" and password \"{1}\"", userName, password));
#line 206
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 207
 testRunner.And("I select a Subject \"SUB004\"");
#line 208
 testRunner.Then("I can not see \"Enable\" button");
#line 209
 testRunner.And("I take a screenshot");
#line 210
 testRunner.When(string.Format("I am logged in to Rave with username \"{0}\" and password \"{1}\"", userName, password));
#line 211
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 212
 testRunner.And("I select a Subject \"SUB005\"");
#line 213
 testRunner.Then("I can not see \"Enable\" button");
#line 214
 testRunner.And("I take a screenshot");
#line 215
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-08 A user without unlock permission cannot see the enable add event butt" +
            "on on the subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-08")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "cdm1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "cdm1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_08AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectHomePage__Cdm1()
        {
            this.US11547_08AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectHomePage_("cdm1", "password", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-08 A user without unlock permission cannot see the enable add event butt" +
            "on on the subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-08")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "siteuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "siteuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_08AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectHomePage__Siteuser()
        {
            this.US11547_08AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectHomePage_("siteuser", "password", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-09 The \"Enable Add Events\" tool tip displays when a user hovers over the" +
            " enable add event button on the subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-09")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_09TheEnableAddEventsToolTipDisplaysWhenAUserHoversOverTheEnableAddEventButtonOnTheSubjectHomePage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-09 The \"Enable Add Events\" tool tip displays when a user hovers over the" +
                    " enable add event button on the subject home page.", new string[] {
                        "release_2012.1.0",
                        "US11547-09",
                        "Draft"});
#line 225
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 226
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 227
    testRunner.When("I select Study \"Study A\" and Site \"Site A1\"");
#line 228
 testRunner.And("I select a Subject \"SUB004\"");
#line 229
 testRunner.When("The \"Enable\" button is available");
#line 230
 testRunner.Then("I can see tooltip \"Enable Add Events\" on button labeled \"Enable\"");
#line 231
 testRunner.And("I take a screenshot");
#line 232
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-10 Clicking on the enable add event button on the subject home page allo" +
            "ws users to add event.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-10")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_10ClickingOnTheEnableAddEventButtonOnTheSubjectHomePageAllowsUsersToAddEvent_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-10 Clicking on the enable add event button on the subject home page allo" +
                    "ws users to add event.", new string[] {
                        "release_2012.1.0",
                        "US11547-10",
                        "Draft"});
#line 237
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 238
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 239
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 240
 testRunner.And("I select a Subject \"SUB004\"");
#line 241
 testRunner.And("The \"Enable\" button is available");
#line 242
 testRunner.When("I click button \"Enable\"");
#line 243
 testRunner.Then("I can see \"enabled\" dropdown labeled \"Add Event\"");
#line 244
 testRunner.And("I can see \"Add\" button");
#line 245
 testRunner.Then("I can not see \"Enable\" button");
#line 246
 testRunner.And("I take a screenshot");
#line 247
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-11 A user with lock permission can see the disable add event button on t" +
            "he subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_11AUserWithLockPermissionCanSeeTheDisableAddEventButtonOnTheSubjectGridViewPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-11 A user with lock permission can see the disable add event button on t" +
                    "he subject grid view page.", new string[] {
                        "release_2012.1.0",
                        "US11547-11",
                        "Draft"});
#line 253
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 254
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 255
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 256
 testRunner.And("I select a Subject \"SUB004\"");
#line 257
 testRunner.And("The \"Disable\" button is available");
#line 258
 testRunner.And("I take a screenshot");
#line 259
 testRunner.And("I select \"Grid View\"");
#line 260
 testRunner.Then("I can see \"Disable\" button");
#line 261
 testRunner.And("I take a screenshot");
#line 262
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void US11547_12AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectGridViewPage_(string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "release_2012.1.0",
                    "US11547-12",
                    "Draft"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-12 A user without lock permission cannot see the disable add event butto" +
                    "n on the subject grid view page.", @__tags);
#line 267
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 268
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 269
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 270
 testRunner.And("I select a Subject \"SUB004\"");
#line 271
 testRunner.And("The \"Disable\" button is available");
#line 272
 testRunner.And("I take a screenshot");
#line 273
 testRunner.And("I log out of Rave");
#line 274
 testRunner.When(string.Format("I am logged in to Rave with username \"{0}\" and password \"{1}\"", userName, password));
#line 275
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 276
 testRunner.And("I select a Subject \"SUB004\"");
#line 277
 testRunner.And("I select \"Grid View\"");
#line 278
 testRunner.Then("I can not see \"Disable\" button");
#line 279
 testRunner.And("I take a screenshot");
#line 280
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-12 A user without lock permission cannot see the disable add event butto" +
            "n on the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-12")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "cdm2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "cdm2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_12AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectGridViewPage__Cdm2()
        {
            this.US11547_12AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectGridViewPage_("cdm2", "password", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-12 A user without lock permission cannot see the disable add event butto" +
            "n on the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-12")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "siteuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "siteuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_12AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectGridViewPage__Siteuser()
        {
            this.US11547_12AUserWithoutLockPermissionCannotSeeTheDisableAddEventButtonOnTheSubjectGridViewPage_("siteuser", "password", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-13 The \"Disable Add Events\" tool tip displays when a user hovers over th" +
            "e disable add event button on the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-13")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_13TheDisableAddEventsToolTipDisplaysWhenAUserHoversOverTheDisableAddEventButtonOnTheSubjectGridViewPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-13 The \"Disable Add Events\" tool tip displays when a user hovers over th" +
                    "e disable add event button on the subject grid view page.", new string[] {
                        "release_2012.1.0",
                        "US11547-13",
                        "Draft"});
#line 290
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 291
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 292
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 293
 testRunner.And("I select a Subject \"SUB004\"");
#line 294
 testRunner.And("The \"Disable\" button is available");
#line 295
 testRunner.And("I take a screenshot");
#line 296
 testRunner.And("I select \"Grid View\"");
#line 297
 testRunner.When("The \"Disable\" button is available");
#line 298
 testRunner.Then("I can see tooltip \"Disable Add Events\" on button labeled \"Disable\"");
#line 299
 testRunner.And("I take a screenshot");
#line 300
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-14 Clicking on the disable add event button disables the Add Event featu" +
            "re on the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-14")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_14ClickingOnTheDisableAddEventButtonDisablesTheAddEventFeatureOnTheSubjectGridViewPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-14 Clicking on the disable add event button disables the Add Event featu" +
                    "re on the subject grid view page.", new string[] {
                        "release_2012.1.0",
                        "US11547-14",
                        "Draft"});
#line 305
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 306
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 307
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 308
 testRunner.And("I select a Subject \"SUB004\"");
#line 309
 testRunner.And("The \"Disable\" button is available");
#line 310
 testRunner.And("I take a screenshot");
#line 311
 testRunner.And("I select \"Grid View\"");
#line 312
 testRunner.When("I click button \"Disable\"");
#line 313
 testRunner.Then("I can see \"disabled\" dropdown labeled \"Add Event\"");
#line 314
 testRunner.And("I can not see \"Add\" button");
#line 315
 testRunner.Then("I can not see \"Disable\" button");
#line 316
 testRunner.And("I take a screenshot");
#line 317
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-15 A user should not be able to add event if the Add Event feature is di" +
            "sabled on the subject grid view page. A lock icon, indicating that the Add Event" +
            " feature is disabled, should display next to the Add Event dropdown.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-15")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_15AUserShouldNotBeAbleToAddEventIfTheAddEventFeatureIsDisabledOnTheSubjectGridViewPage_ALockIconIndicatingThatTheAddEventFeatureIsDisabledShouldDisplayNextToTheAddEventDropdown_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-15 A user should not be able to add event if the Add Event feature is di" +
                    "sabled on the subject grid view page. A lock icon, indicating that the Add Event" +
                    " feature is disabled, should display next to the Add Event dropdown.", new string[] {
                        "release_2012.1.0",
                        "US11547-15",
                        "Draft"});
#line 322
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 323
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 324
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 325
 testRunner.And("I select a Subject \"SUB004\"");
#line 326
 testRunner.And("The \"Disable\" button is available");
#line 327
 testRunner.And("I click button \"Disable\"");
#line 328
 testRunner.And("I take a screenshot");
#line 329
 testRunner.And("I log out of Rave");
#line 330
 testRunner.When("I am logged in to Rave with username \"cdm1\" and password \"password\"");
#line 331
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 332
 testRunner.And("I select a Subject \"SUB004\"");
#line 333
 testRunner.And("I select \"Grid View\"");
#line 334
 testRunner.Then("I can not see \"Add\" button");
#line 335
 testRunner.And("I can see Add Event lock icon");
#line 336
 testRunner.And("I take a screenshot");
#line 337
 testRunner.Then("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void US11547_16AUserWithUnlockPermissionCanSeeTheEnableAddEventButtonOnTheSubjectGridViewPageOnlyWhenTheAddEventFeatureIsDisabled_(string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "release_2012.1.0",
                    "US11547-16",
                    "Draft"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-16 A user with unlock permission can see the enable add event button on " +
                    "the subject grid view page only when the Add Event feature is disabled.", @__tags);
#line 342
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 343
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 344
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 345
 testRunner.And("I select a Subject \"SUB004\"");
#line 346
 testRunner.And("The \"Disable\" button is available");
#line 347
 testRunner.And("I click button \"Disable\"");
#line 348
 testRunner.And("I take a screenshot");
#line 349
 testRunner.And("I log out of Rave");
#line 350
 testRunner.When(string.Format("I am logged in to Rave with username \"{0}\" and password \"{1}\"", userName, password));
#line 351
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 352
 testRunner.And("I select a Subject \"SUB004\"");
#line 353
 testRunner.And("I select \"Grid View\"");
#line 354
 testRunner.Then("I can see \"Enable\" button");
#line 355
 testRunner.And("I take a screenshot");
#line 356
 testRunner.When(string.Format("I am logged in to Rave with username \"{0}\" and password \"{1}\"", userName, password));
#line 357
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 358
 testRunner.And("I select a Subject \"SUB005\"");
#line 359
 testRunner.And("I select \"Grid View\"");
#line 360
 testRunner.Then("I can not see \"Enable\" button");
#line 361
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-16 A user with unlock permission can see the enable add event button on " +
            "the subject grid view page only when the Add Event feature is disabled.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-16")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "defuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "defuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_16AUserWithUnlockPermissionCanSeeTheEnableAddEventButtonOnTheSubjectGridViewPageOnlyWhenTheAddEventFeatureIsDisabled__Defuser()
        {
            this.US11547_16AUserWithUnlockPermissionCanSeeTheEnableAddEventButtonOnTheSubjectGridViewPageOnlyWhenTheAddEventFeatureIsDisabled_("defuser", "password", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-16 A user with unlock permission can see the enable add event button on " +
            "the subject grid view page only when the Add Event feature is disabled.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-16")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "cdm2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "cdm2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_16AUserWithUnlockPermissionCanSeeTheEnableAddEventButtonOnTheSubjectGridViewPageOnlyWhenTheAddEventFeatureIsDisabled__Cdm2()
        {
            this.US11547_16AUserWithUnlockPermissionCanSeeTheEnableAddEventButtonOnTheSubjectGridViewPageOnlyWhenTheAddEventFeatureIsDisabled_("cdm2", "password", ((string[])(null)));
        }
        
        public virtual void US11547_17AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectGridViewPage_(string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "release_2012.1.0",
                    "US11547-17",
                    "Draft"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-17 A user without unlock permission cannot see the enable add event butt" +
                    "on on the subject grid view page.", @__tags);
#line 371
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 372
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 373
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 374
 testRunner.And("I select a Subject \"SUB004\"");
#line 375
 testRunner.And("The \"Disable\" button is available");
#line 376
 testRunner.And("I click button \"Disable\"");
#line 377
 testRunner.And("I take a screenshot");
#line 378
 testRunner.And("I log out of Rave");
#line 379
 testRunner.When(string.Format("I am logged in to Rave with username \"{0}\" and password \"{1}\"", userName, password));
#line 380
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 381
 testRunner.And("I select a Subject \"SUB004\"");
#line 382
 testRunner.And("I select \"Grid View\"");
#line 383
 testRunner.Then("I can not see \"Enable\" button");
#line 384
 testRunner.And("I take a screenshot");
#line 385
 testRunner.When(string.Format("I am logged in to Rave with username \"{0}\" and password \"{1}\"", userName, password));
#line 386
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 387
 testRunner.And("I select a Subject \"SUB005\"");
#line 388
 testRunner.And("I select \"Grid View\"");
#line 389
 testRunner.Then("I can not see \"Enable\" button");
#line 390
 testRunner.And("I take a screenshot");
#line 391
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-17 A user without unlock permission cannot see the enable add event butt" +
            "on on the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "cdm1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "cdm1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_17AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectGridViewPage__Cdm1()
        {
            this.US11547_17AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectGridViewPage_("cdm1", "password", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-17 A user without unlock permission cannot see the enable add event butt" +
            "on on the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "siteuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User Name", "siteuser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "password")]
        public virtual void US11547_17AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectGridViewPage__Siteuser()
        {
            this.US11547_17AUserWithoutUnlockPermissionCannotSeeTheEnableAddEventButtonOnTheSubjectGridViewPage_("siteuser", "password", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-18 The \"Enable Add Events\" tool tip displays when a user hovers over the" +
            " enable add event button on the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-18")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_18TheEnableAddEventsToolTipDisplaysWhenAUserHoversOverTheEnableAddEventButtonOnTheSubjectGridViewPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-18 The \"Enable Add Events\" tool tip displays when a user hovers over the" +
                    " enable add event button on the subject grid view page.", new string[] {
                        "release_2012.1.0",
                        "US11547-18",
                        "Draft"});
#line 401
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 402
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 403
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 404
 testRunner.And("I select a Subject \"SUB004\"");
#line 405
 testRunner.And("The \"Enable\" button is available");
#line 406
 testRunner.And("I take a screenshot");
#line 407
 testRunner.And("I select \"Grid View\"");
#line 408
 testRunner.When("The \"Enable\" button is available");
#line 409
 testRunner.Then("I can see tooltip \"Enable Add Events\" on button labeled \"Enable\"");
#line 410
 testRunner.And("I take a screenshot");
#line 411
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-19 Clicking on the enable add event button allows users to add event on " +
            "the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-19")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_19ClickingOnTheEnableAddEventButtonAllowsUsersToAddEventOnTheSubjectGridViewPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-19 Clicking on the enable add event button allows users to add event on " +
                    "the subject grid view page.", new string[] {
                        "release_2012.1.0",
                        "US11547-19",
                        "Draft"});
#line 416
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 417
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 418
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 419
 testRunner.And("I select a Subject \"SUB004\"");
#line 420
 testRunner.And("The \"Disable\" button is available");
#line 421
 testRunner.And("I take a screenshot");
#line 422
 testRunner.And("I click button \"Disable\"");
#line 423
 testRunner.When("I click button \"Enable\"");
#line 424
 testRunner.Then("I can see \"enabled\" dropdown labeled \"Add Event\"");
#line 425
 testRunner.Then("I can see \"Add\" button");
#line 426
 testRunner.Then("I can not see \"Enable\" button");
#line 427
 testRunner.And("I take a screenshot");
#line 428
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-20 Disabling the Add Event feature on the subject home page also disable" +
            "s the Add Event feature on the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-20")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_20DisablingTheAddEventFeatureOnTheSubjectHomePageAlsoDisablesTheAddEventFeatureOnTheSubjectGridViewPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-20 Disabling the Add Event feature on the subject home page also disable" +
                    "s the Add Event feature on the subject grid view page.", new string[] {
                        "release_2012.1.0",
                        "US11547-20",
                        "Draft"});
#line 433
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 434
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 435
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 436
 testRunner.And("I select a Subject \"SUB004\"");
#line 437
 testRunner.And("The \"Disable\" button is available");
#line 438
 testRunner.And("I click button \"Disable\"");
#line 439
 testRunner.And("I take a screenshot");
#line 440
 testRunner.And("I select \"Grid View\"");
#line 441
 testRunner.Then("I can see \"disabled\" dropdown labeled \"Add Event\"");
#line 442
 testRunner.Then("I can not see \"Add\" button");
#line 443
 testRunner.Then("I can not see \"Disable\" button");
#line 444
 testRunner.And("I take a screenshot");
#line 445
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-21 Disabling the Add Event feature on the subject grid view page also di" +
            "sables the Add Event feature on the subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-21")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_21DisablingTheAddEventFeatureOnTheSubjectGridViewPageAlsoDisablesTheAddEventFeatureOnTheSubjectHomePage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-21 Disabling the Add Event feature on the subject grid view page also di" +
                    "sables the Add Event feature on the subject home page.", new string[] {
                        "release_2012.1.0",
                        "US11547-21",
                        "Draft"});
#line 450
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 451
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 452
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 453
 testRunner.And("I select a Subject \"SUB004\"");
#line 454
 testRunner.And("The \"Disable\" button is available");
#line 455
 testRunner.And("I take a screenshot");
#line 456
 testRunner.And("I select \"Grid View\"");
#line 457
 testRunner.And("I click button \"Disable\"");
#line 458
 testRunner.And("I take a screenshot");
#line 459
 testRunner.And("I select \"Calendar View\"");
#line 460
 testRunner.Then("I can see \"disabled\" dropdown labeled \"Add Event\"");
#line 461
 testRunner.Then("I can not see \"Add\" button");
#line 462
 testRunner.Then("I can not see \"Disable\" button");
#line 463
 testRunner.And("I take a screenshot");
#line 464
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-22 Enabling the Add Event feature on the subject home page also enables " +
            "the Add Event feature on the subject grid view page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-22")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_22EnablingTheAddEventFeatureOnTheSubjectHomePageAlsoEnablesTheAddEventFeatureOnTheSubjectGridViewPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-22 Enabling the Add Event feature on the subject home page also enables " +
                    "the Add Event feature on the subject grid view page.", new string[] {
                        "release_2012.1.0",
                        "US11547-22",
                        "Draft"});
#line 469
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 470
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 471
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 472
 testRunner.And("I select a Subject \"SUB004\"");
#line 473
 testRunner.And("The \"Enable\" button is available");
#line 474
 testRunner.And("I take a screenshot");
#line 475
 testRunner.And("I click button \"Enable\"");
#line 476
 testRunner.And("I select \"Grid View\"");
#line 477
 testRunner.Then("I can see \"enabled\" dropdown labeled \"Add Event\"");
#line 478
 testRunner.Then("I can see \"Add\" button");
#line 479
 testRunner.Then("I can not see \"Enable\" button");
#line 480
 testRunner.And("I take a screenshot");
#line 481
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-23 Enabling the Add Event feature on the subject grid view page also ena" +
            "bles the Add Event feature on the subject home page.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-23")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_23EnablingTheAddEventFeatureOnTheSubjectGridViewPageAlsoEnablesTheAddEventFeatureOnTheSubjectHomePage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-23 Enabling the Add Event feature on the subject grid view page also ena" +
                    "bles the Add Event feature on the subject home page.", new string[] {
                        "release_2012.1.0",
                        "US11547-23",
                        "Draft"});
#line 486
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 487
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 488
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 489
 testRunner.And("I select a Subject \"SUB004\"");
#line 490
 testRunner.And("I select \"Grid View\"");
#line 491
 testRunner.And("The \"Disable\" button is available");
#line 492
 testRunner.And("I take a screenshot");
#line 493
 testRunner.And("I click button \"Disable\"");
#line 494
 testRunner.And("I click button \"Enable\"");
#line 495
 testRunner.And("I take a screenshot");
#line 496
 testRunner.And("I select \"Calendar View\"");
#line 497
 testRunner.Then("I can see \"enabled\" dropdown labeled \"Add Event\"");
#line 498
 testRunner.Then("I can see \"Add\" button");
#line 499
 testRunner.Then("I can not see \"Enable\" button");
#line 500
 testRunner.And("I take a screenshot");
#line 501
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-24 Locking \"All\" in the subject grid view page disables the Add Event fe" +
            "ature.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-24")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_24LockingAllInTheSubjectGridViewPageDisablesTheAddEventFeature_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-24 Locking \"All\" in the subject grid view page disables the Add Event fe" +
                    "ature.", new string[] {
                        "release_2012.1.0",
                        "US11547-24",
                        "Draft"});
#line 506
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 507
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 508
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 509
 testRunner.And("I select a Subject \"SUB004\"");
#line 510
 testRunner.And("I select \"Grid View\"");
#line 511
 testRunner.And("The \"Disable\" button is available");
#line 512
 testRunner.And("I take a screenshot");
#line 513
 testRunner.When("I select \"All\"");
#line 514
 testRunner.And("I check Lock checkbox");
#line 515
 testRunner.And("I click radiobutton with label \"Set\"");
#line 516
 testRunner.And("I take a screenshot");
#line 517
 testRunner.And("I click button \"Save\"");
#line 518
 testRunner.And("I take a screenshot");
#line 519
 testRunner.Then("I can see \"disabled\" dropdown labeled \"Add Event\"");
#line 520
 testRunner.Then("I can not see \"Add\" button");
#line 521
 testRunner.Then("I can not see \"Disable\" button");
#line 522
 testRunner.And("I take a screenshot");
#line 523
 testRunner.And("I log out of Rave");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("@US11547-25 Unlocking \"All\" in the subject grid view page enables the Add Event f" +
            "eature.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Disabling/Enabling Add Events")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("US11547-25")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void US11547_25UnlockingAllInTheSubjectGridViewPageEnablesTheAddEventFeature_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("@US11547-25 Unlocking \"All\" in the subject grid view page enables the Add Event f" +
                    "eature.", new string[] {
                        "release_2012.1.0",
                        "US11547-25",
                        "Draft"});
#line 528
this.ScenarioSetup(scenarioInfo);
#line 13
this.FeatureBackground();
#line 529
 testRunner.When("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 530
 testRunner.And("I select Study \"Study A\" and Site \"Site A1\"");
#line 531
 testRunner.And("I select a Subject \"SUB004\"");
#line 532
 testRunner.And("I select \"Grid View\"");
#line 533
 testRunner.When("I select \"All\"");
#line 534
 testRunner.And("I check Lock checkbox");
#line 535
 testRunner.And("I click radiobutton with label \"Set\"");
#line 536
 testRunner.And("I take a screenshot");
#line 537
 testRunner.And("I click button \"Save\"");
#line 538
 testRunner.And("I take a screenshot");
#line 539
 testRunner.And("The \"Enable\" button is available");
#line 540
 testRunner.And("I check Lock checkbox");
#line 541
 testRunner.And("I click radiobutton with label \"Clear\"");
#line 542
 testRunner.And("I take a screenshot");
#line 543
 testRunner.And("I click button \"Save\"");
#line 544
 testRunner.And("I take a screenshot");
#line 545
 testRunner.Then("I can see \"enabled\" dropdown labeled \"Add Event\"");
#line 546
 testRunner.And("I can see \"Add\" button");
#line 547
 testRunner.And("I can not see \"Enable\" button");
#line 548
 testRunner.And("I take a screenshot");
#line 549
 testRunner.And("I log out of Rave");
#line 550
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
