// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Medidata.RBT.Features.Rave.Features.EDC
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DT13905NeedsCVRefreshIsNotSetToOnForAllDatapointsRelatedWhenLabUnitConversionIsCreatedOrUpdatedFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "US15417_DT13905.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
                    " Conversion is created or updated", @"As a Rave user
Given I enter lab data in non-standard units
And I do not use Alert or Reference Labs for the lab data
When I update or create a lab unit conversion formula to convert the lab data to standard units
Then I should see the lab data converted to standard values in the standard units in Clinical Views", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
                            " Conversion is created or updated")))
            {
                Medidata.RBT.Features.Rave.Features.EDC.DT13905NeedsCVRefreshIsNotSetToOnForAllDatapointsRelatedWhenLabUnitConversionIsCreatedOrUpdatedFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 12
#line 13
    testRunner.Given("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line 24
 testRunner.And("I select Study \"Mediflex_SJ\" and Site \"Site 1\"");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an EDC user, when I create a unit conversion formula to convert lab data in a " +
            "non-standard unit to standard values in a standard unit, then I should see the s" +
            "tandard value and standard units in Clinical Views.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
            " Conversion is created or updated")]
        public virtual void AsAnEDCUserWhenICreateAUnitConversionFormulaToConvertLabDataInANon_StandardUnitToStandardValuesInAStandardUnitThenIShouldSeeTheStandardValueAndStandardUnitsInClinicalViews_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As an EDC user, when I create a unit conversion formula to convert lab data in a " +
                    "non-standard unit to standard values in a standard unit, then I should see the s" +
                    "tandard value and standard units in Clinical Views.", new string[] {
                        "release_2012.1.0",
                        "PB_DT13905_01",
                        "Draft"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table1.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table1.AddRow(new string[] {
                        "Subject number",
                        "{RndNum<num1>(3)}"});
            table1.AddRow(new string[] {
                        "Age",
                        "20"});
            table1.AddRow(new string[] {
                        "Sex",
                        "MaleREGAQT"});
#line 29
 testRunner.When("I create a Subject", ((string)(null)), table1);
#line 43
 testRunner.And("I select Form \"Hematology\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Unit"});
            table2.AddRow(new string[] {
                        "WBC",
                        "1",
                        "10^9/L"});
#line 47
 testRunner.And("I enter data in CRF and save", ((string)(null)), table2);
#line 53
 testRunner.And("I select \"Home\"");
#line 54
 testRunner.And("I navigate to \"Lab Administration\"");
#line 55
 testRunner.And("I navigate to \"Unit Conversions\"");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "From",
                        "To",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table3.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "",
                        "2",
                        "1",
                        "0",
                        "0"});
#line 58
 testRunner.And("I add new unit conversion data", ((string)(null)), table3);
#line 61
 testRunner.And("I go to the Reporter module");
#line 63
 testRunner.And("I run the Data Listings Report for Study \"Mediflex_SJ\"");
#line 65
 testRunner.And("I select the Lab view");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Analyte",
                        "Value",
                        "Units",
                        "Standard Value",
                        "Standard Units"});
            table4.AddRow(new string[] {
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "20",
                        "%"});
#line 67
 testRunner.Then("I should see lab data", ((string)(null)), table4);
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an EDC user, when I create a unit conversion formula to convert lab data in a " +
            "non-standard unit to standard values in a standard unit for a specific analyte, " +
            "then I should see the standard value and standard units in Clinical Views.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
            " Conversion is created or updated")]
        public virtual void AsAnEDCUserWhenICreateAUnitConversionFormulaToConvertLabDataInANon_StandardUnitToStandardValuesInAStandardUnitForASpecificAnalyteThenIShouldSeeTheStandardValueAndStandardUnitsInClinicalViews_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As an EDC user, when I create a unit conversion formula to convert lab data in a " +
                    "non-standard unit to standard values in a standard unit for a specific analyte, " +
                    "then I should see the standard value and standard units in Clinical Views.", new string[] {
                        "release_2012.1.0",
                        "PB_DT13905_02",
                        "Draft"});
#line 74
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table5.AddRow(new string[] {
                        "Subject Number",
                        "{RndNum<num1>(3)}"});
            table5.AddRow(new string[] {
                        "Age",
                        "20"});
            table5.AddRow(new string[] {
                        "Sex",
                        "MaleREGAQT"});
            table5.AddRow(new string[] {
                        "Pregancy Status",
                        "NoREGAQT"});
            table5.AddRow(new string[] {
                        "Subject Date",
                        "01 FEB 2011"});
#line 75
 testRunner.When("I create a Subject", ((string)(null)), table5);
#line 83
 testRunner.And("I save the CRF page");
#line 90
 testRunner.And("I am on CRF page \"Hematology\" on subject level in Subject \"SUB{Var(num1)}\" in Sit" +
                    "e \"Site 1\" in Study \"Mediflex_SJ\"");
#line 91
 testRunner.And("I select Lab \"Local Lab DT13905\"");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value",
                        "Unit"});
            table6.AddRow(new string[] {
                        "WBC",
                        "1",
                        "10^9/L"});
#line 92
 testRunner.And("I enter data in CRF page", ((string)(null)), table6);
#line 96
 testRunner.And("I save the CRF page");
#line 97
 testRunner.And("I go to Unit Conversions page in the Lab Admin module");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "From Unit",
                        "To Unit",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table7.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "WBC",
                        "4",
                        "1",
                        "0",
                        "0"});
#line 98
 testRunner.And("I enter unit conversion data", ((string)(null)), table7);
#line 101
 testRunner.And("I go to the Reporter module");
#line 102
 testRunner.And("I run the Data Listings Report for Study \"Mediflex_SJ\"");
#line 103
 testRunner.And("I select the Lab view");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Analyte",
                        "Value",
                        "Units",
                        "Standard Value",
                        "Standard Units"});
            table8.AddRow(new string[] {
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "40",
                        "%"});
#line 104
 testRunner.Then("I should see lab data", ((string)(null)), table8);
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an EDC user, when I update a unit conversion formula to convert lab data in a " +
            "non-standard unit to standard values in a standard unit, then I should see the s" +
            "tandard value and standard units in Clinical Views.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
            " Conversion is created or updated")]
        public virtual void AsAnEDCUserWhenIUpdateAUnitConversionFormulaToConvertLabDataInANon_StandardUnitToStandardValuesInAStandardUnitThenIShouldSeeTheStandardValueAndStandardUnitsInClinicalViews_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As an EDC user, when I update a unit conversion formula to convert lab data in a " +
                    "non-standard unit to standard values in a standard unit, then I should see the s" +
                    "tandard value and standard units in Clinical Views.", new string[] {
                        "release_2012.1.0",
                        "PB_DT13905_03",
                        "Draft"});
#line 111
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line 113
 testRunner.When("I go to Unit Conversions page in the Lab Admin module");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "From Unit",
                        "To Unit",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table9.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "",
                        "2",
                        "1",
                        "0",
                        "0"});
#line 114
 testRunner.And("I enter unit conversion data", ((string)(null)), table9);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table10.AddRow(new string[] {
                        "Subject Number",
                        "{RndNum<num1>(3)}"});
            table10.AddRow(new string[] {
                        "Age",
                        "20"});
            table10.AddRow(new string[] {
                        "Sex",
                        "MaleREGAQT"});
            table10.AddRow(new string[] {
                        "Pregancy Status",
                        "NoREGAQT"});
            table10.AddRow(new string[] {
                        "Subject Date",
                        "01 FEB 2011"});
#line 117
 testRunner.And("I create a Subject", ((string)(null)), table10);
#line 125
 testRunner.And("I save the CRF page");
#line 132
 testRunner.And("I am on CRF page \"Hematology\" on subject level in Subject \"SUB{Var(num1)}\" in Sit" +
                    "e \"Site 1\" in Study \"Mediflex_SJ\"");
#line 133
 testRunner.And("I select Lab \"Local Lab DT13905\"");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value",
                        "Unit"});
            table11.AddRow(new string[] {
                        "WBC",
                        "1",
                        "10^9/L"});
#line 134
 testRunner.And("I enter data in CRF", ((string)(null)), table11);
#line 138
 testRunner.And("I save the CRF");
#line 139
 testRunner.And("I go to the Reporter module");
#line 140
 testRunner.And("I run the Data Listings Report for Study \"Mediflex_SJ\"");
#line 141
 testRunner.And("I select the Lab view");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Analyte",
                        "Value",
                        "Units",
                        "Standard Value",
                        "Standard Units"});
            table12.AddRow(new string[] {
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "20",
                        "%"});
#line 142
 testRunner.Then("I should see lab data", ((string)(null)), table12);
#line 145
 testRunner.And("I go to Unit Conversions page in the Lab Admin module");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "From Unit",
                        "To Unit",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table13.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "",
                        "3",
                        "1",
                        "0",
                        "0"});
#line 146
 testRunner.And("I enter unit conversion data", ((string)(null)), table13);
#line 149
 testRunner.And("I go to the Reporter module");
#line 150
 testRunner.And("I run the Data Listings Report for Study \"Mediflex_SJ\"");
#line 151
 testRunner.And("I select the Lab view");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Analyte",
                        "Value",
                        "Units",
                        "Standard Value",
                        "Standard Units"});
            table14.AddRow(new string[] {
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "30",
                        "%"});
#line 152
 testRunner.Then("I should see lab data", ((string)(null)), table14);
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As an EDC user, when I update a unit conversion formula to convert lab data in a " +
            "non-standard unit to standard values in a standard unit for a specific analyte, " +
            "then I should see the standard value and standard units in Clinical Views.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
            " Conversion is created or updated")]
        public virtual void AsAnEDCUserWhenIUpdateAUnitConversionFormulaToConvertLabDataInANon_StandardUnitToStandardValuesInAStandardUnitForASpecificAnalyteThenIShouldSeeTheStandardValueAndStandardUnitsInClinicalViews_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As an EDC user, when I update a unit conversion formula to convert lab data in a " +
                    "non-standard unit to standard values in a standard unit for a specific analyte, " +
                    "then I should see the standard value and standard units in Clinical Views.", new string[] {
                        "release_2012.1.0",
                        "PB_DT13905_04",
                        "Draft"});
#line 159
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line 160
 testRunner.When("I go to Unit Conversions page in the Lab Admin module");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "From Unit",
                        "To Unit",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table15.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "WBC",
                        "3",
                        "1",
                        "0",
                        "0"});
#line 161
 testRunner.And("I enter unit conversion data", ((string)(null)), table15);
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table16.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table16.AddRow(new string[] {
                        "Subject Number",
                        "{RndNum<num1>(5)}"});
            table16.AddRow(new string[] {
                        "Age",
                        "20"});
            table16.AddRow(new string[] {
                        "Sex",
                        "MaleREGAQT"});
            table16.AddRow(new string[] {
                        "Pregancy Status",
                        "NoREGAQT"});
            table16.AddRow(new string[] {
                        "Subject Date",
                        "01 FEB 2011"});
#line 164
 testRunner.And("I create a Subject", ((string)(null)), table16);
#line 177
 testRunner.And("I save the CRF page");
#line 178
 testRunner.And("I am on CRF page \"Hematology\" on subject level in Subject \"SUB{Var(num1)}\" in Sit" +
                    "e \"Site 1\" in Study \"Mediflex_SJ\"");
#line 179
 testRunner.And("I select Lab \"Local Lab DT13905 \"");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value",
                        "Unit"});
            table17.AddRow(new string[] {
                        "WBC",
                        "1",
                        "10^9/L"});
#line 180
 testRunner.And("I enter data in CRF page", ((string)(null)), table17);
#line 184
 testRunner.And("I save the CRF page");
#line 185
 testRunner.And("I go to the Reporter module");
#line 186
 testRunner.And("I run the Data Listings Report for Study \"Mediflex_SJ\"");
#line 187
 testRunner.And("I select the Lab view");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Analyte",
                        "Value",
                        "Units",
                        "Standard Value",
                        "Standard Units"});
            table18.AddRow(new string[] {
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "30",
                        "%"});
#line 188
 testRunner.Then("I should see lab data", ((string)(null)), table18);
#line 191
 testRunner.And("I go to Unit Conversions page in the Lab Admin module");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "From Unit",
                        "To Unit",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table19.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "",
                        "5",
                        "1",
                        "0",
                        "0"});
#line 192
 testRunner.And("I enter unit conversion data", ((string)(null)), table19);
#line 195
 testRunner.And("I go to the Reporter module");
#line 196
 testRunner.And("I run the Data Listings Report for Study \"Mediflex_SJ\"");
#line 197
 testRunner.And("I select the Lab view");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Analyte",
                        "Value",
                        "Units",
                        "Standard Value",
                        "Standard Units"});
            table20.AddRow(new string[] {
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "50",
                        "%"});
#line 198
 testRunner.Then("I should see lab data", ((string)(null)), table20);
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
