// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Medidata.RBT.Features.Rave.Features.EDC
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DT13905NeedsCVRefreshIsNotSetToOnForAllDatapointsRelatedWhenLabUnitConversionIsCreatedOrUpdatedFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "US15417_DT13905.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
                    " Conversion is created or updated", @"As a Rave user
Given I enter lab data in non-standard units
And I do not use Alert or Reference Labs for the lab data
When I update or create a lab unit conversion formula to convert the lab data to standard units
Then I should see the lab data converted to standard values in the standard units in Clinical Views", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
                            " Conversion is created or updated")))
            {
                Medidata.RBT.Features.Rave.Features.EDC.DT13905NeedsCVRefreshIsNotSetToOnForAllDatapointsRelatedWhenLabUnitConversionIsCreatedOrUpdatedFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 12
#line 13
    testRunner.Given("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_DT13905_01 As an EDC user, when I create a unit conversion formula to convert " +
            "lab data in a non-standard unit to standard values in a standard unit, then I sh" +
            "ould see the standard value and standard units in Clinical Views.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
            " Conversion is created or updated")]
        public virtual void PB_DT13905_01AsAnEDCUserWhenICreateAUnitConversionFormulaToConvertLabDataInANon_StandardUnitToStandardValuesInAStandardUnitThenIShouldSeeTheStandardValueAndStandardUnitsInClinicalViews_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_DT13905_01 As an EDC user, when I create a unit conversion formula to convert " +
                    "lab data in a non-standard unit to standard values in a standard unit, then I sh" +
                    "ould see the standard value and standard units in Clinical Views.", new string[] {
                        "release_2012.1.0",
                        "PB_DT13905_01",
                        "Draft"});
#line 87
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line 88
 testRunner.And("I select Study \"US15417_DT13905_SJ\" and Site \"Site 1\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table1.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table1.AddRow(new string[] {
                        "Subject number",
                        "{RndNum<num1>(3)}"});
            table1.AddRow(new string[] {
                        "Age",
                        "20"});
            table1.AddRow(new string[] {
                        "Sex",
                        "MaleREGAQT"});
            table1.AddRow(new string[] {
                        "Pregancy Status",
                        "NoREGAQT"});
            table1.AddRow(new string[] {
                        "Subject Date",
                        "01 Feb 2011"});
#line 89
 testRunner.When("I create a Subject", ((string)(null)), table1);
#line 97
 testRunner.And("I take a screenshot");
#line 98
 testRunner.And("I select Form \"Hematology\"");
#line 99
 testRunner.And("I choose \"US15417_DT13905_SJ\" from \"Lab\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Unit"});
            table2.AddRow(new string[] {
                        "WBC",
                        "10",
                        "10^9/L"});
#line 100
 testRunner.And("I enter data in CRF and save", ((string)(null)), table2);
#line 104
 testRunner.And("I take a screenshot");
#line 105
 testRunner.And("I select \"Home\"");
#line 106
 testRunner.And("I navigate to \"Lab Administration\"");
#line 107
 testRunner.And("I navigate to \"Unit Conversions\"");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "From",
                        "To",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table3.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "...",
                        "2",
                        "1",
                        "0",
                        "0"});
#line 108
 testRunner.And("I add new unit conversion data", ((string)(null)), table3);
#line 111
 testRunner.And("I take a screenshot");
#line 114
 testRunner.And("I navigate to \"Home\"");
#line 115
 testRunner.And("I navigate to \"Reporter\"");
#line 116
 testRunner.And("I select Report \"Data Listing\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table4.AddRow(new string[] {
                        "US15417_DT13905_SJ",
                        "Prod"});
#line 117
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table4);
#line 120
 testRunner.And("I click button \"Submit Report\"");
#line 121
 testRunner.And("I switch to \"DataListingsReport\" window");
#line 122
 testRunner.And("I choose \"Clinical Views\" from \"Data Source\"");
#line 123
 testRunner.And("I choose \"AnalytesView\" from \"Form\"");
#line 124
 testRunner.And("I click button \"Run\"");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject",
                        "FormName",
                        "AnalyteName",
                        "AnalyteValue",
                        "LabUnits",
                        "StdValue",
                        "StdUnits"});
            table5.AddRow(new string[] {
                        "SUB{Var(num1)}",
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "20",
                        "%"});
#line 125
 testRunner.Then("I should verify row(s) exist in \"Result\" table", ((string)(null)), table5);
#line 128
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_DT13905_02 As an EDC user, when I create a unit conversion formula to convert " +
            "lab data in a non-standard unit to standard values in a standard unit for a spec" +
            "ific analyte, then I should see the standard value and standard units in Clinica" +
            "l Views.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
            " Conversion is created or updated")]
        public virtual void PB_DT13905_02AsAnEDCUserWhenICreateAUnitConversionFormulaToConvertLabDataInANon_StandardUnitToStandardValuesInAStandardUnitForASpecificAnalyteThenIShouldSeeTheStandardValueAndStandardUnitsInClinicalViews_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_DT13905_02 As an EDC user, when I create a unit conversion formula to convert " +
                    "lab data in a non-standard unit to standard values in a standard unit for a spec" +
                    "ific analyte, then I should see the standard value and standard units in Clinica" +
                    "l Views.", new string[] {
                        "release_2012.1.0",
                        "PB_DT13905_02",
                        "Draft"});
#line 133
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line 134
 testRunner.And("I select Study \"US15417_DT13905_SJ\" and Site \"Site 1\"");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table6.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table6.AddRow(new string[] {
                        "Subject number",
                        "{RndNum<num1>(3)}"});
            table6.AddRow(new string[] {
                        "Age",
                        "20"});
            table6.AddRow(new string[] {
                        "Sex",
                        "MaleREGAQT"});
            table6.AddRow(new string[] {
                        "Pregancy Status",
                        "NoREGAQT"});
            table6.AddRow(new string[] {
                        "Subject Date",
                        "01 Feb 2011"});
#line 135
 testRunner.When("I create a Subject", ((string)(null)), table6);
#line 143
 testRunner.And("I take a screenshot");
#line 144
 testRunner.And("I select Form \"Hematology\"");
#line 145
 testRunner.And("I choose \"US15417_DT13905_SJ\" from \"Lab\"");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Unit"});
            table7.AddRow(new string[] {
                        "WBC",
                        "10",
                        "10^9/L"});
            table7.AddRow(new string[] {
                        "NEUTROPHILS",
                        "10",
                        "10^9/L"});
#line 146
 testRunner.And("I enter data in CRF and save", ((string)(null)), table7);
#line 151
 testRunner.And("I take a screenshot");
#line 152
 testRunner.And("I select \"Home\"");
#line 153
 testRunner.And("I navigate to \"Lab Administration\"");
#line 154
 testRunner.And("I navigate to \"Unit Conversions\"");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "From",
                        "To",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table8.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "WBC",
                        "4",
                        "1",
                        "0",
                        "0"});
#line 155
 testRunner.And("I add new unit conversion data", ((string)(null)), table8);
#line 159
 testRunner.And("I take a screenshot");
#line 160
 testRunner.And("I navigate to \"Home\"");
#line 161
 testRunner.And("I navigate to \"Reporter\"");
#line 162
 testRunner.And("I select Report \"Data Listing\"");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table9.AddRow(new string[] {
                        "US15417_DT13905_SJ",
                        "Prod"});
#line 163
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table9);
#line 166
 testRunner.And("I click button \"Submit Report\"");
#line 167
 testRunner.And("I switch to \"DataListingsReport\" window");
#line 168
 testRunner.And("I choose \"Clinical Views\" from \"Data Source\"");
#line 169
 testRunner.And("I choose \"AnalytesView\" from \"Form\"");
#line 170
 testRunner.And("I click button \"Run\"");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject",
                        "FormName",
                        "AnalyteName",
                        "AnalyteValue",
                        "LabUnits",
                        "StdValue",
                        "StdUnits"});
            table10.AddRow(new string[] {
                        "SUB{Var(num1)}",
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "40",
                        "%"});
#line 172
 testRunner.Then("I should verify row(s) exist in \"Result\" table", ((string)(null)), table10);
#line 176
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_DT13905_03 As an EDC user, when I update a unit conversion formula to convert " +
            "lab data in a non-standard unit to standard values in a standard unit, then I sh" +
            "ould see the standard value and standard units in Clinical Views.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
            " Conversion is created or updated")]
        public virtual void PB_DT13905_03AsAnEDCUserWhenIUpdateAUnitConversionFormulaToConvertLabDataInANon_StandardUnitToStandardValuesInAStandardUnitThenIShouldSeeTheStandardValueAndStandardUnitsInClinicalViews_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_DT13905_03 As an EDC user, when I update a unit conversion formula to convert " +
                    "lab data in a non-standard unit to standard values in a standard unit, then I sh" +
                    "ould see the standard value and standard units in Clinical Views.", new string[] {
                        "release_2012.1.0",
                        "PB_DT13905_03",
                        "Draft"});
#line 180
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line 182
 testRunner.And("I select Study \"US15417_DT13905_SJ\" and Site \"Site 1\"");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table11.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table11.AddRow(new string[] {
                        "Subject number",
                        "{RndNum<num1>(3)}"});
            table11.AddRow(new string[] {
                        "Age",
                        "20"});
            table11.AddRow(new string[] {
                        "Sex",
                        "MaleREGAQT"});
            table11.AddRow(new string[] {
                        "Pregancy Status",
                        "NoREGAQT"});
            table11.AddRow(new string[] {
                        "Subject Date",
                        "01 Feb 2011"});
#line 183
 testRunner.And("I create a Subject", ((string)(null)), table11);
#line 192
 testRunner.And("I take a screenshot");
#line 193
 testRunner.And("I select Form \"Hematology\"");
#line 194
 testRunner.And("I choose \"US15417_DT13905_SJ\" from \"Lab\"");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Unit"});
            table12.AddRow(new string[] {
                        "WBC",
                        "10",
                        "10^9/L"});
#line 195
 testRunner.And("I enter data in CRF and save", ((string)(null)), table12);
#line 199
 testRunner.And("I take a screenshot");
#line 200
 testRunner.And("I navigate to \"Home\"");
#line 201
 testRunner.And("I navigate to \"Reporter\"");
#line 202
 testRunner.And("I select Report \"Data Listing\"");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table13.AddRow(new string[] {
                        "US15417_DT13905_SJ",
                        "Prod"});
#line 203
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table13);
#line 206
 testRunner.And("I click button \"Submit Report\"");
#line 207
 testRunner.And("I switch to \"DataListingsReport\" window");
#line 208
 testRunner.And("I choose \"Clinical Views\" from \"Data Source\"");
#line 209
 testRunner.And("I choose \"AnalytesView\" from \"Form\"");
#line 210
 testRunner.And("I click button \"Run\"");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject",
                        "FormName",
                        "AnalyteName",
                        "AnalyteValue",
                        "LabUnits",
                        "StdValue",
                        "StdUnits"});
            table14.AddRow(new string[] {
                        "SUB{Var(num1)}",
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "20",
                        "%"});
#line 212
 testRunner.Then("I should verify row(s) exist in \"Result\" table", ((string)(null)), table14);
#line 216
 testRunner.And("I take a screenshot");
#line 217
 testRunner.And("I select \"Home\"");
#line 218
 testRunner.And("I navigate to \"Lab Administration\"");
#line 219
 testRunner.And("I navigate to \"Unit Conversions\"");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "From",
                        "To",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table15.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "",
                        "3",
                        "1",
                        "0",
                        "0"});
#line 220
 testRunner.And("I add new unit conversion data", ((string)(null)), table15);
#line 224
 testRunner.And("I take a screenshot");
#line 225
 testRunner.And("I navigate to \"Home\"");
#line 226
 testRunner.And("I navigate to \"Reporter\"");
#line 227
 testRunner.And("I select Report \"Data Listing\"");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table16.AddRow(new string[] {
                        "Mediflex_SJ",
                        "Prod"});
#line 228
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table16);
#line 231
 testRunner.And("I click button \"Submit Report\"");
#line 232
 testRunner.And("I switch to \"DataListingsReport\" window");
#line 233
 testRunner.And("I choose \"Clinical Views\" from \"Data Source\"");
#line 234
 testRunner.And("I choose \"AnalytesView\" from \"Form\"");
#line 235
 testRunner.And("I click button \"Run\"");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject",
                        "FormName",
                        "AnalyteName",
                        "AnalyteValue",
                        "LabUnits",
                        "StdValue",
                        "StdUnits"});
            table17.AddRow(new string[] {
                        "SUB{Var(num1)}",
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "30",
                        "%"});
#line 237
 testRunner.Then("I should verify row(s) exist in \"Result\" table", ((string)(null)), table17);
#line 241
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB_DT13905_04 As an EDC user, when I update a unit conversion formula to convert " +
            "lab data in a non-standard unit to standard values in a standard unit for a spec" +
            "ific analyte, then I should see the standard value and standard units in Clinica" +
            "l Views.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13905 NeedsCVRefresh is not set to On for all datapoints related when Lab Unit" +
            " Conversion is created or updated")]
        public virtual void PB_DT13905_04AsAnEDCUserWhenIUpdateAUnitConversionFormulaToConvertLabDataInANon_StandardUnitToStandardValuesInAStandardUnitForASpecificAnalyteThenIShouldSeeTheStandardValueAndStandardUnitsInClinicalViews_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB_DT13905_04 As an EDC user, when I update a unit conversion formula to convert " +
                    "lab data in a non-standard unit to standard values in a standard unit for a spec" +
                    "ific analyte, then I should see the standard value and standard units in Clinica" +
                    "l Views.", new string[] {
                        "release_2012.1.0",
                        "PB_DT13905_04",
                        "Draft"});
#line 245
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line 247
 testRunner.And("I select Study \"US15417_DT13905_SJ\" and Site \"Site 1\"");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table18.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table18.AddRow(new string[] {
                        "Subject number",
                        "{RndNum<num1>(3)}"});
            table18.AddRow(new string[] {
                        "Age",
                        "20"});
            table18.AddRow(new string[] {
                        "Sex",
                        "MaleREGAQT"});
            table18.AddRow(new string[] {
                        "Pregancy Status",
                        "NoREGAQT"});
            table18.AddRow(new string[] {
                        "Subject Date",
                        "01 Feb 2011"});
#line 248
 testRunner.And("I create a Subject", ((string)(null)), table18);
#line 257
 testRunner.And("I take a screenshot");
#line 258
 testRunner.And("I select Form \"Hematology\"");
#line 259
 testRunner.And("I choose \"US15417_DT13905_SJ\" from \"Lab\"");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Unit"});
            table19.AddRow(new string[] {
                        "WBC",
                        "10",
                        "10^9/L"});
            table19.AddRow(new string[] {
                        "NEUTROPHILS",
                        "10",
                        "10^9/L"});
#line 260
 testRunner.And("I enter data in CRF and save", ((string)(null)), table19);
#line 265
 testRunner.And("I take a screenshot");
#line 266
 testRunner.And("I navigate to \"Home\"");
#line 267
 testRunner.And("I navigate to \"Reporter\"");
#line 268
 testRunner.And("I select Report \"Data Listing\"");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table20.AddRow(new string[] {
                        "Mediflex_SJ",
                        "Prod"});
#line 269
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table20);
#line 272
 testRunner.And("I click button \"Submit Report\"");
#line 273
 testRunner.And("I switch to \"DataListingsReport\" window");
#line 274
 testRunner.And("I choose \"Clinical Views\" from \"Data Source\"");
#line 275
 testRunner.And("I choose \"AnalytesView\" from \"Form\"");
#line 276
 testRunner.And("I click button \"Run\"");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject",
                        "FormName",
                        "AnalyteName",
                        "AnalyteValue",
                        "LabUnits",
                        "StdValue",
                        "StdUnits"});
            table21.AddRow(new string[] {
                        "SUB{Var(num1)}",
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "30",
                        "%"});
#line 278
 testRunner.Then("I should verify row(s) exist in \"Result\" table", ((string)(null)), table21);
#line 282
 testRunner.And("I take a screenshot");
#line 283
 testRunner.And("I select \"Home\"");
#line 284
 testRunner.And("I navigate to \"Lab Administration\"");
#line 285
 testRunner.And("I navigate to \"Unit Conversions\"");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "From",
                        "To",
                        "Analyte",
                        "A",
                        "B",
                        "C",
                        "D"});
            table22.AddRow(new string[] {
                        "10^9/L",
                        "%",
                        "",
                        "5",
                        "1",
                        "0",
                        "0"});
#line 286
 testRunner.And("I add new unit conversion data", ((string)(null)), table22);
#line 290
 testRunner.And("I take a screenshot");
#line 291
 testRunner.And("I navigate to \"Home\"");
#line 292
 testRunner.And("I navigate to \"Reporter\"");
#line 293
 testRunner.And("I select Report \"Data Listing\"");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table23.AddRow(new string[] {
                        "Mediflex_SJ",
                        "Prod"});
#line 294
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table23);
#line 297
 testRunner.And("I click button \"Submit Report\"");
#line 298
 testRunner.And("I switch to \"DataListingsReport\" window");
#line 299
 testRunner.And("I choose \"Clinical Views\" from \"Data Source\"");
#line 300
 testRunner.And("I choose \"AnalytesView\" from \"Form\"");
#line 301
 testRunner.And("I click button \"Run\"");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject",
                        "FormName",
                        "AnalyteName",
                        "AnalyteValue",
                        "LabUnits",
                        "StdValue",
                        "StdUnits"});
            table24.AddRow(new string[] {
                        "SUB{Var(num1)}",
                        "Hematology",
                        "WBC",
                        "10",
                        "10^9/L",
                        "50",
                        "%"});
#line 303
 testRunner.Then("I should verify row(s) exist in \"Result\" table", ((string)(null)), table24);
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
