// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Medidata.UAT.Features.Rave.EDC
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class Feaature8Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "564QueryRefiringLogic8.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feaature 8", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Feaature 8")))
            {
                Medidata.UAT.Features.Rave.EDC.Feaature8Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
    testRunner.Given("I am on Rave");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Study",
                        "Role",
                        "Site",
                        "Site Number"});
            table1.AddRow(new string[] {
                        "editcheck",
                        "Edit Check Study 8",
                        "cdm1",
                        "Edit Check Site 8",
                        "80001"});
            table1.AddRow(new string[] {
                        "editcheck1",
                        "Edit Check Study 8",
                        "cdm2",
                        "Edit Check Site 8",
                        "80001"});
            table1.AddRow(new string[] {
                        "editcheck",
                        "AM Edit Check Study",
                        "cdm1",
                        "AM Edit Site",
                        "80002"});
#line 5
 testRunner.And("user \"User\"  has study \"Study\" has role \"Role\" has site \"Site\" has Site Number in" +
                    " database \"<EDC>\", from the table below", ((string)(null)), table1);
#line 10
 testRunner.And("role \"cdm1\" has Query actions");
#line 11
 testRunner.And("role \"cdm2\" has Query actions");
#line 12
 testRunner.And("study \"Edit Check Study\" had draft \"<Draft1>\"");
#line 13
 testRunner.And("I publish and push \"CRF Version<RANDOMNUMBER>\" to site \"Edit Check Site 8\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Threshold",
                        "Value"});
            table2.AddRow(new string[] {
                        "Check Resolution Threshold",
                        "0"});
            table2.AddRow(new string[] {
                        "Check Execution Threshold",
                        "0"});
            table2.AddRow(new string[] {
                        "Custom Function Threshold",
                        "0"});
#line 14
 testRunner.And("I set and save \"Threshold\" in Configuration, Other Settings, Advance Configuratio" +
                    "n to \"Value\", from the table below", ((string)(null)), table2);
#line 19
 testRunner.And("I do cacheflush");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Data setup and verification for query re-firing.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void DataSetupAndVerificationForQueryRe_Firing_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Data setup and verification for query re-firing.", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 25
 testRunner.And("I login to Rave as user \"editcheck\" with password \"<Password>\"");
#line 26
 testRunner.And("I select \"DDE Module\"");
#line 27
 testRunner.And("I selct link \"First Pass\"");
#line 28
 testRunner.And("I select \"Edit Check Study 8, Prod, Edit Check Site 8\"");
#line 29
 testRunner.And("I enter \"sub801\"");
#line 30
 testRunner.And("I select \"Primary\" form");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table3.AddRow(new string[] {
                        "Subject Name",
                        "sub"});
            table3.AddRow(new string[] {
                        "Subject Number",
                        "801"});
#line 31
 testRunner.And("I enter and save the following data, from the table below", ((string)(null)), table3);
#line 35
 testRunner.And("I select folder \"Test A Single Edit\" form \"Informed Consent Date Form 1\"");
#line 36
 testRunner.And("I select button \"Locate\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table4.AddRow(new string[] {
                        "Informed Consent Date 1",
                        "09 Jan 2000"});
            table4.AddRow(new string[] {
                        "Informed Consent Date 2",
                        "10 Jan 2000"});
            table4.AddRow(new string[] {
                        "Numeric Field 1",
                        "10"});
            table4.AddRow(new string[] {
                        "Numeric Field 2",
                        "19"});
#line 37
 testRunner.And("I enter and submit the following data, from the table below", ((string)(null)), table4);
#line 43
 testRunner.And("I take a screenshot 1 of 70");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table5.AddRow(new string[] {
                        "Assessment Date 1",
                        "08 Jan 2000"});
            table5.AddRow(new string[] {
                        "Assessment Date 2",
                        "11 Jan 2000"});
            table5.AddRow(new string[] {
                        "Numeric Field 1",
                        "10"});
            table5.AddRow(new string[] {
                        "Numeric Field 2",
                        "20"});
#line 44
    testRunner.And("I enter and submit the following data in folder \"Test A Single Edit\" form \"Assess" +
                    "ment Date Log2\", from the table below", ((string)(null)), table5);
#line 51
 testRunner.And("I logout and login to Rave as user \"editcheck1\" with password \"<Password>\"");
#line 52
 testRunner.And("I select \"DDE Module\"");
#line 53
 testRunner.And("I selct link \"Second Pass\"");
#line 54
 testRunner.And("I select \"Edit Check Study 8, Prod, Edit Check Site 8\"");
#line 55
 testRunner.And("I enter \"sub801\"");
#line 56
 testRunner.And("I select \"Primary\" form");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table6.AddRow(new string[] {
                        "Subject Name",
                        "sub"});
            table6.AddRow(new string[] {
                        "Subject Number",
                        "801"});
#line 57
 testRunner.And("I enter and save the following data, from the table below", ((string)(null)), table6);
#line 61
 testRunner.And("I select folder \"Test A Single Edit\" form \"Informed Consent Date Form 1\"");
#line 62
 testRunner.And("I select button \"Locate\"");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table7.AddRow(new string[] {
                        "Informed Consent Date 1",
                        "09 Jan 2000"});
            table7.AddRow(new string[] {
                        "Informed Consent Date 2",
                        "10 Jan 2000"});
            table7.AddRow(new string[] {
                        "Numeric Field 1",
                        "10"});
            table7.AddRow(new string[] {
                        "Numeric Field 2",
                        "19"});
#line 63
 testRunner.And("I enter and submit the following data, from the table below", ((string)(null)), table7);
#line 69
 testRunner.And("I take a screenshot 2 of 70");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table8.AddRow(new string[] {
                        "Assessment Date 1",
                        "08 Jan 2000"});
            table8.AddRow(new string[] {
                        "Assessment Date 2",
                        "11 Jan 2000"});
            table8.AddRow(new string[] {
                        "Numeric Field 1",
                        "10"});
            table8.AddRow(new string[] {
                        "Numeric Field 2",
                        "20"});
#line 70
    testRunner.And("I enter and submit the following data in folder \"Test A Single Edit\" form \"Assess" +
                    "ment Date Log2\", from the table below", ((string)(null)), table8);
#line 77
 testRunner.And("I select link \"Home\"");
#line 78
 testRunner.And("I select \"Edit Check Study 8, Prod, Edit Check Site 8\"");
#line 79
 testRunner.And("I Select \"sub801\"");
#line 80
 testRunner.And("I navigate to folder \"Test A Single Edit\"");
#line 81
 testRunner.And("I select form \"Assessment Date Log2\"");
#line 82
 testRunner.And("I verify \"Assessment Date 1\" field displays query opened with require response");
#line 83
    testRunner.And("I verify \"Numeric Field 2\" field displays query opened with require response");
#line 84
 testRunner.And("I take a screenshot 3 of 70");
#line 85
 testRunner.And("I answer the queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields");
#line 86
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 87
 testRunner.And("I close the queries on \"Assessment Date 1\" field and \"Numeric Field 2\" fields");
#line 88
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 89
 testRunner.And("I take a screenshot 4 of 70");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table9.AddRow(new string[] {
                        "Assessment Date 1",
                        "09 Jan 2000"});
            table9.AddRow(new string[] {
                        "Numeric Field 2",
                        "19"});
#line 90
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table9);
#line 94
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 95
    testRunner.And("I verify the queries did not fire on \"Assessment Date 1\" field and \"Numeric Field" +
                    " 2\" fields");
#line 96
 testRunner.And("I take a screenshot 5 of 70");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table10.AddRow(new string[] {
                        "Assessment Date 1",
                        "08 Jan 2000"});
            table10.AddRow(new string[] {
                        "Numeric Field 2",
                        "20"});
#line 97
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table10);
#line 101
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 102
 testRunner.And("I verify new queries did not fire on \"Assessment Date 1\" field and \"Numeric Field" +
                    " 2\" fields");
#line 103
 testRunner.And("I take a screenshot 6 of 70");
#line 104
    testRunner.When("I run SQL Script \"Query Logging Script\"");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProjectName",
                        "SiteNumber",
                        "SiteName",
                        "Environment",
                        "SubjectName",
                        "CheckActionInstanceName",
                        "CheckActionInstanceDataPageName",
                        "CheckActionRecordPosition",
                        "CheckActionFieldName",
                        "CheckActionFieldData",
                        "TriggerFieldInstanceName",
                        "TriggerFieldInstanceDatapageName",
                        "TriggerFieldRecordPosition",
                        "TriggerFieldName",
                        "TriggerFieldData",
                        "EditCheckName",
                        "MarkingGroupName",
                        "QueryMessage",
                        "EventTime"});
            table11.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "1",
                        "Assessment Date 1",
                        "08 Jan 2000",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "1",
                        "Assessment Date 1",
                        "08 Jan 2000",
                        "*Greater Than Open Query Log Cross Form",
                        "Marking Group 1",
                        "Informed Consent Date 1 is greater. Please revise.",
                        "{DateTime}"});
            table11.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "1",
                        "Numeric Field 2",
                        "20",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "1",
                        "Numeric Field 2",
                        "20",
                        "*Is Not Equal to Open Query Log Cross Form*",
                        "Site",
                        "Informed Consent numeric field 2 is not equal to assessment numeric field 2",
                        "{DateTime}"});
#line 105
    testRunner.Then("I should see the logging data for queries", ((string)(null)), table11);
#line 109
 testRunner.And("I take a screenshot 7 of 70");
#line 111
 testRunner.And("I navigate to form \"Assessment Date Log2\" within folder \"Test A Single Edit\"");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table12.AddRow(new string[] {
                        "Assessment Date 1",
                        "07 Jan 2000"});
            table12.AddRow(new string[] {
                        "Assessment Date 2",
                        "12 Jan 2000"});
            table12.AddRow(new string[] {
                        "Numeric Field 1",
                        "10"});
            table12.AddRow(new string[] {
                        "Numeric Field 2",
                        "18"});
#line 112
    testRunner.And("I add a new log line, enter and save the data, from the table below", ((string)(null)), table12);
#line 118
 testRunner.And("I verify \"Assessment Date 1\" field displays query opened with require response on" +
                    " the second log line");
#line 119
    testRunner.And("I verify \"Numeric Field 2\" field displays query opened with require response on t" +
                    "he second log line");
#line 120
 testRunner.And("I take a screenshot 8 of 70");
#line 121
 testRunner.And("I answer the queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields on the s" +
                    "econd log line");
#line 122
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table13.AddRow(new string[] {
                        "Assessment Date 1",
                        "09 Jan 2000"});
            table13.AddRow(new string[] {
                        "Numeric Field 2",
                        "19"});
#line 123
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table13);
#line 127
 testRunner.And("I close the queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields on the se" +
                    "cond log line");
#line 128
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 129
 testRunner.And("I take a screenshot 9 of 70");
#line 130
 testRunner.And("I verify the queries did not fire on \"Assessment Date 1\" and \"Numeric Field 2\" fi" +
                    "elds");
#line 131
 testRunner.And("I take a screenshot 10 of 70");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table14.AddRow(new string[] {
                        "Assessment Date 1",
                        "07 Jan 2000"});
            table14.AddRow(new string[] {
                        "Numeric Field 2",
                        "18"});
#line 132
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table14);
#line 136
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 137
 testRunner.And("I verify new queries did fire on \"Assessment Date 1\" and \"Numeric Field 2\" fields" +
                    "");
#line 138
 testRunner.And("I take a screenshot 11 of 70");
#line 139
    testRunner.When("I run SQL Script \"Query Logging Script\"");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProjectName",
                        "SiteNumber",
                        "SiteName",
                        "Environment",
                        "SubjectName",
                        "CheckActionInstanceName",
                        "CheckActionInstanceDataPageName",
                        "CheckActionRecordPosition",
                        "CheckActionFieldName",
                        "CheckActionFieldData",
                        "TriggerFieldInstanceName",
                        "TriggerFieldInstanceDatapageName",
                        "TriggerFieldRecordPosition",
                        "TriggerFieldName",
                        "TriggerFieldData",
                        "EditCheckName",
                        "MarkingGroupName",
                        "QueryMessage",
                        "EventTime"});
            table15.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Assessment Date 1",
                        "07 Jan 2000",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Assessment Date 1",
                        "07 Jan 2000",
                        "*Greater Than Open Query Log Cross Form",
                        "Marking Group 1",
                        "Informed Consent Date 1 is greater. Please revise.",
                        "{DateTime}"});
            table15.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Numeric Field 2",
                        "18",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Numeric Field 2",
                        "18",
                        "*Is Not Equal to Open Query Log Cross Form*",
                        "Site",
                        "Informed Consent numeric field 2 is not equal to assessment numeric field 2",
                        "{DateTime}"});
#line 140
    testRunner.Then("I should not see the logging data for queries", ((string)(null)), table15);
#line 144
 testRunner.And("I take a screenshot\t12 of 70");
#line 146
 testRunner.And("I navigate to form \"Assessment Date Log2\" within folder \"Test A Single Edit\"");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table16.AddRow(new string[] {
                        "Assessment Date 1",
                        "07 Jan 2000"});
            table16.AddRow(new string[] {
                        "Assessment Date 2",
                        "12 Jan 2000"});
            table16.AddRow(new string[] {
                        "Numeric Field 1",
                        "10"});
            table16.AddRow(new string[] {
                        "Numeric Field 2",
                        "18"});
#line 147
    testRunner.And("I add a new log line, enter and save the data, from the table below", ((string)(null)), table16);
#line 153
 testRunner.And("I verify \"Assessment Date 1\" field displays query opened with require response on" +
                    " the third log line");
#line 154
    testRunner.And("I verify \"Numeric Field 2\" field displays query opened with require response on t" +
                    "he third log line");
#line 155
 testRunner.And("I take a screenshot 13 of 70");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table17.AddRow(new string[] {
                        "Assessment Date 1",
                        "09 Jan 2000"});
            table17.AddRow(new string[] {
                        "Numeric Field 2",
                        "19"});
#line 156
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table17);
#line 160
 testRunner.And("I cancel the queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields on the t" +
                    "hird log line");
#line 161
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 162
 testRunner.And("I take a screenshot 14 of 70");
#line 163
 testRunner.And("I verify the queries did not fire on \"Assessment Date 1\" and \"Numeric Field 2\" fi" +
                    "elds");
#line 164
 testRunner.And("I take a screenshot 15 of 70");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table18.AddRow(new string[] {
                        "Assessment Date 1",
                        "07 Jan 2000"});
            table18.AddRow(new string[] {
                        "Numeric Field 2",
                        "18"});
#line 165
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table18);
#line 169
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 170
 testRunner.And("I verify new queries did fire on \"Assessment Date 1\" and \"Numeric Field 2\" fields" +
                    "");
#line 171
 testRunner.And("I take a screenshot 16 of 70");
#line 172
    testRunner.When("I run SQL Script \"Query Logging Script\"");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProjectName",
                        "SiteNumber",
                        "SiteName",
                        "Environment",
                        "SubjectName",
                        "CheckActionInstanceName",
                        "CheckActionInstanceDataPageName",
                        "CheckActionRecordPosition",
                        "CheckActionFieldName",
                        "CheckActionFieldData",
                        "TriggerFieldInstanceName",
                        "TriggerFieldInstanceDatapageName",
                        "TriggerFieldRecordPosition",
                        "TriggerFieldName",
                        "TriggerFieldData",
                        "EditCheckName",
                        "MarkingGroupName",
                        "QueryMessage",
                        "EventTime"});
            table19.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "3",
                        "Assessment Date 1",
                        "07 Jan 2000",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Assessment Date 1",
                        "07 Jan 2000",
                        "*Greater Than Open Query Log Cross Form",
                        "Marking Group 1",
                        "Informed Consent Date 1 is greater. Please revise.",
                        "{DateTime}"});
            table19.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "3",
                        "Numeric Field 2",
                        "18",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Numeric Field 2",
                        "18",
                        "*Is Not Equal to Open Query Log Cross Form*",
                        "Site",
                        "Informed Consent numeric field 2 is not equal to assessment numeric field 2",
                        "{DateTime}"});
#line 173
    testRunner.Then("I should not see the logging data for queries", ((string)(null)), table19);
#line 177
 testRunner.And("I take a screenshot\t17 of 70");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Task Summary")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void TaskSummary()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Task Summary", ((string[])(null)));
#line 180
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 182
 testRunner.And("I navigate to a \"Edit Check Study 8, Edit Check Site 8\"");
#line 183
 testRunner.And("I select subject \"sub801\"");
#line 184
 testRunner.And("I select \"Open Query\" located in Task Summary");
#line 185
 testRunner.When("I select right arrow image for \"Open Queries\" located in \"Task Summary\"");
#line 186
 testRunner.Then("I should see added query on form \'Assessment Date Log2\'");
#line 187
 testRunner.When("I select \'Test A Single Edit-Assessment Date Log2\'");
#line 188
 testRunner.Then("I verify \"Assessment Date 1\" field displays query opened with require response");
#line 189
    testRunner.And("I verify \"Numeric Field 2\" field displays query opened with require response");
#line 190
 testRunner.And("I take a screenshot 18 of 70");
#line 192
 testRunner.And("I select subject \"sub801\"");
#line 193
 testRunner.And("I select \"Cancel Query\" located in Task Summary");
#line 194
 testRunner.When("I select right arrow image for \"Cancel Queries\" located in \"Task Summary\"");
#line 195
 testRunner.Then("I should see added query on form \'Assessment Date Log2\'");
#line 196
 testRunner.When("I select \'Test A Single Edit-Assessment Date Log2\'");
#line 197
 testRunner.Then("I verify \"Assessment Date 1\" field displays query opened with require response an" +
                    "d Cancel");
#line 198
    testRunner.And("I verify \"Numeric Field 2\" field displays query opened with require response and " +
                    "Cancel");
#line 199
 testRunner.And("I take a screenshot 19 of 70");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Query Management")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void QueryManagement()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Query Management", ((string[])(null)));
#line 202
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 204
 testRunner.And("I select \"Query Management\"");
#line 205
 testRunner.And("I seelct \"Edit Check Study 8 (Prod),  World, Edit Check Site 8, sub801\"");
#line 206
 testRunner.And("I select link Search");
#line 207
 testRunner.And("I select link form \"Assessment Date Log2\" for subject \"sub801\"");
#line 208
 testRunner.And("I verify \"Assessment Date 1\" field displays query opened with require response on" +
                    " the second log line");
#line 209
    testRunner.And("I verify \"Numeric Field 2\" field displays query opened with require response on t" +
                    "he second log line");
#line 210
 testRunner.And("I take a screenshot 20 of 70");
#line 211
 testRunner.And("I verify \"Assessment Date 1\" field displays query opened with require response on" +
                    " the third log line");
#line 212
    testRunner.And("I verify \"Numeric Field 2\" field displays query opened with require response on t" +
                    "he third log line");
#line 213
 testRunner.And("I take a screenshot 21 of 70");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table20.AddRow(new string[] {
                        "Assessment Date 1",
                        "07 Jan 2000"});
            table20.AddRow(new string[] {
                        "Assessment Date 2",
                        "12 Jan 2000"});
            table20.AddRow(new string[] {
                        "Numeric Field 1",
                        "10"});
            table20.AddRow(new string[] {
                        "Numeric Field 2",
                        "18"});
#line 215
    testRunner.And("I add a new log line, enter and save the data, from the table below", ((string)(null)), table20);
#line 221
 testRunner.And("I verify \"Assessment Date 1\" field displays query opened with require response on" +
                    " the fourth log line");
#line 222
    testRunner.And("I verify \"Numeric Field 2\" field displays query opened with require response on t" +
                    "he fourth log line");
#line 223
 testRunner.And("I take a screenshot 22 of 70");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table21.AddRow(new string[] {
                        "Assessment Date 1",
                        "09 Jan 2000"});
            table21.AddRow(new string[] {
                        "Numeric Field 2",
                        "19"});
#line 224
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table21);
#line 228
 testRunner.And("I cancel the queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields on the f" +
                    "ourth log line");
#line 229
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 230
 testRunner.And("I take a screenshot 23 of 70");
#line 231
 testRunner.And("I verify the queries did not fire on \"Assessment Date 1\" and \"Numeric Field 2\" fi" +
                    "elds");
#line 232
 testRunner.And("I take a screenshot 24 of 70");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table22.AddRow(new string[] {
                        "Assessment Date 1",
                        "07 Jan 2000"});
            table22.AddRow(new string[] {
                        "Numeric Field 2",
                        "18"});
#line 233
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table22);
#line 237
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 238
 testRunner.And("I verify new queries did fire on \"Assessment Date 1\" and \"Numeric Field 2\" fields" +
                    "");
#line 239
 testRunner.And("I take a screenshot 25 of 70");
#line 240
    testRunner.When("I run SQL Script \"Query Logging Script\"");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProjectName",
                        "SiteNumber",
                        "SiteName",
                        "Environment",
                        "SubjectName",
                        "CheckActionInstanceName",
                        "CheckActionInstanceDataPageName",
                        "CheckActionRecordPosition",
                        "CheckActionFieldName",
                        "CheckActionFieldData",
                        "TriggerFieldInstanceName",
                        "TriggerFieldInstanceDatapageName",
                        "TriggerFieldRecordPosition",
                        "TriggerFieldName",
                        "TriggerFieldData",
                        "EditCheckName",
                        "MarkingGroupName",
                        "QueryMessage",
                        "EventTime"});
            table23.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "4",
                        "Assessment Date 1",
                        "07 Jan 2000",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Assessment Date 1",
                        "07 Jan 2000",
                        "*Greater Than Open Query Log Cross Form",
                        "Marking Group 1",
                        "Informed Consent Date 1 is greater. Please revise.",
                        "{DateTime}"});
            table23.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "4",
                        "Numeric Field 2",
                        "18",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Numeric Field 2",
                        "18",
                        "*Is Not Equal to Open Query Log Cross Form*",
                        "Site",
                        "Informed Consent numeric field 2 is not equal to assessment numeric field 2",
                        "{DateTime}"});
#line 241
    testRunner.Then("I should not see the logging data for queries", ((string)(null)), table23);
#line 245
 testRunner.And("I take a screenshot 26 of 70");
#line 247
 testRunner.And("I navigate to form \"Assessment Date Log2\" within folder \"Test A Single Edit\"");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table24.AddRow(new string[] {
                        "Assessment Date 1",
                        "07 Jan 2000"});
            table24.AddRow(new string[] {
                        "Assessment Date 2",
                        "12 Jan 2000"});
            table24.AddRow(new string[] {
                        "Numeric Field 1",
                        "10"});
            table24.AddRow(new string[] {
                        "Numeric Field 2",
                        "18"});
#line 248
    testRunner.And("I add a new log line, enter and save the data, from the table below", ((string)(null)), table24);
#line 254
 testRunner.And("I verify \"Assessment Date 1\" field displays query opened with require response on" +
                    " the fifth log line");
#line 255
    testRunner.And("I verify \"Numeric Field 2\" field displays query opened with require response on t" +
                    "he fifth log line");
#line 256
 testRunner.And("I take a screenshot 27 of 70");
#line 257
 testRunner.And("I answer the queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields");
#line 258
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table25.AddRow(new string[] {
                        "Assessment Date 1",
                        "09 Jan 2000"});
            table25.AddRow(new string[] {
                        "Numeric Field 2",
                        "19"});
#line 259
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table25);
#line 263
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 264
 testRunner.And("I close the queries on \"Assessment Date 1\" field and \"Numeric Field 2\" fields");
#line 265
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 266
 testRunner.And("I take a screenshot 28 of 70");
#line 267
 testRunner.And("I verify the queries did not fire on \"Assessment Date 1\" and \"Numeric Field 2\" fi" +
                    "elds");
#line 268
 testRunner.And("I take a screenshot 29 of 70");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table26.AddRow(new string[] {
                        "Assessment Date 1",
                        "07 Jan 2000"});
            table26.AddRow(new string[] {
                        "Numeric Field 2",
                        "18"});
#line 269
 testRunner.And("I change the data on \"Assessment Date 1\" and \"Numeric Field 2\" fields, from the t" +
                    "able below", ((string)(null)), table26);
#line 273
 testRunner.And("I save the form \"Assessment Date Log2\"");
#line 274
 testRunner.And("I verify new queries did fire on \"Assessment Date 1\" and \"Numeric Field 2\" fields" +
                    "");
#line 275
 testRunner.And("I take a screenshot 30 of 70");
#line 276
    testRunner.When("I run SQL Script \"Query Logging Script\"");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProjectName",
                        "SiteNumber",
                        "SiteName",
                        "Environment",
                        "SubjectName",
                        "CheckActionInstanceName",
                        "CheckActionInstanceDataPageName",
                        "CheckActionRecordPosition",
                        "CheckActionFieldName",
                        "CheckActionFieldData",
                        "TriggerFieldInstanceName",
                        "TriggerFieldInstanceDatapageName",
                        "TriggerFieldRecordPosition",
                        "TriggerFieldName",
                        "TriggerFieldData",
                        "EditCheckName",
                        "MarkingGroupName",
                        "QueryMessage",
                        "EventTime"});
            table27.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "5",
                        "Assessment Date 1",
                        "07 Jan 2000",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Assessment Date 1",
                        "07 Jan 2000",
                        "*Greater Than Open Query Log Cross Form",
                        "Marking Group 1",
                        "Informed Consent Date 1 is greater. Please revise.",
                        "{DateTime}"});
            table27.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub801",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "5",
                        "Numeric Field 2",
                        "18",
                        "Test A Single Edit",
                        "Assessment Date Log2",
                        "2",
                        "Numeric Field 2",
                        "18",
                        "*Is Not Equal to Open Query Log Cross Form*",
                        "Site",
                        "Informed Consent numeric field 2 is not equal to assessment numeric field 2",
                        "{DateTime}"});
#line 277
    testRunner.Then("I should not see the logging data for queries", ((string)(null)), table27);
#line 281
 testRunner.And("I take a screenshot 31 of 70");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Generate the Data PDFs.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void GenerateTheDataPDFs_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate the Data PDFs.", ((string[])(null)));
#line 284
 this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 286
 testRunner.And("I select \"PDF Generator Module\"");
#line 287
 testRunner.And("I create Data PDF for Subject \"sub801\"");
#line 288
 testRunner.And("I generate Data PDF");
#line 289
 testRunner.When("I View Data PDF");
#line 290
 testRunner.Then("I should see \"Query Data\" in Audits");
#line 291
 testRunner.And("I take a screenshot 32 of 70");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("When I run the Report, then query related data are displayed in the report.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void WhenIRunTheReportThenQueryRelatedDataAreDisplayedInTheReport_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When I run the Report, then query related data are displayed in the report.", ((string[])(null)));
#line 294
 this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 304
 testRunner.And("I login to Rave as user \"<User 1>\" with password \"<Password>\"");
#line 305
 testRunner.And("I select \"Reporter Module\"");
#line 306
 testRunner.And("I select link \"Audit Trail Report\"");
#line 307
 testRunner.And("I select study \"Edit Check Study 8\"");
#line 308
 testRunner.And("I select site \"Edit Check Site 8\"");
#line 309
 testRunner.And("I select subject \"sub801\"");
#line 310
 testRunner.And("I select Folders \"Test A Single Edit\"");
#line 311
 testRunner.And("I select Forms \"Informed Consent Date Form \", \"Assessment Date Log2\"");
#line 312
 testRunner.When("I select button \"Submit Report\"");
#line 313
 testRunner.Then("I should see queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields");
#line 314
 testRunner.And("I take a screenshot 33 of 70");
#line 315
 testRunner.And("I close report");
#line 318
 testRunner.And("I select \"Reporter Module\"");
#line 319
 testRunner.And("I select link \"Query Detail\"");
#line 320
 testRunner.And("I select study \"Edit Check Study 8\"");
#line 321
 testRunner.And("I select site \"Edit Check Site 8\"");
#line 322
 testRunner.And("I select subject \"sub801\"");
#line 323
 testRunner.And("I select Folders \"Test A Single Edit\"");
#line 324
 testRunner.And("I select Forms \"Informed Consent Date Form \", \"Assessment Date Log2\"");
#line 325
 testRunner.When("I select button \"Submit Report\"");
#line 326
 testRunner.Then("I should see queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields");
#line 327
 testRunner.And("I take a screenshot 34 of 70");
#line 328
 testRunner.And("I close report");
#line 331
 testRunner.And("I select \"Reporter Module\"");
#line 332
 testRunner.And("I select link \"Edit Check Log Report\"");
#line 333
 testRunner.And("I select study \"Edit Check Study 8\"");
#line 334
 testRunner.And("I select site \"Edit Check Site 8\"");
#line 335
 testRunner.And("I select subject \"sub801\"");
#line 336
 testRunner.And("I select Form \"Assessment Date Log2\"");
#line 337
 testRunner.And("I select checkbox \"Edit Check\" for \"Check Type\"");
#line 338
 testRunner.And("I select checkbox Check \"CheckExecution\" for \"Log Type\"");
#line 339
 testRunner.When("I select button \"Submit Report\"");
#line 340
 testRunner.Then("I should see fired editchecks");
#line 341
 testRunner.And("I take a screenshot 35 of 70");
#line 342
 testRunner.And("I close report");
#line 345
 testRunner.And("I select \"Reporter Module\"");
#line 346
 testRunner.And("I select link \"Stream-Audit Trail\"");
#line 347
 testRunner.And("I select study \"Edit Check Study 8\"");
#line 348
 testRunner.And("I select site  \"Edit Check Site 8\"");
#line 349
 testRunner.And("I select subject \"sub801\"");
#line 350
 testRunner.And("I select Folders \"Test A Single Edit\"");
#line 351
 testRunner.And("I select Forms \"Informed Consent Date Form \", \"Assessment Date Log2\"");
#line 352
 testRunner.And("I select button \"Submit Report\"");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table28.AddRow(new string[] {
                        "Separator",
                        "."});
            table28.AddRow(new string[] {
                        "File type",
                        ".csv"});
            table28.AddRow(new string[] {
                        "Export type",
                        "attachment"});
            table28.AddRow(new string[] {
                        "Save as Unicode",
                        "Unchecked"});
#line 353
 testRunner.When("I select \"Parameter\" to \"Value\", from the tabe below", ((string)(null)), table28);
#line 359
 testRunner.And("I open excel file");
#line 360
 testRunner.Then("I should see queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields");
#line 361
 testRunner.And("I take a screenshot 36 of 70");
#line 362
 testRunner.And("I close report");
#line 365
 testRunner.And("I select \"Reporter Module\"");
#line 366
 testRunner.And("I select link \"Stream-Query Detail\"");
#line 367
 testRunner.And("I select study \"Edit Check Study 8\"");
#line 368
 testRunner.And("I select site  \"Edit Check Site 8\"");
#line 369
 testRunner.And("I select subject \"sub801\"");
#line 370
 testRunner.And("I select Folders \"Test A Single Edit\"");
#line 371
 testRunner.And("I select Forms \"Informed Consent Date Form \", \"Assessment Date Log2\"");
#line 372
 testRunner.And("I select button \"Submit Report\"");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table29.AddRow(new string[] {
                        "Separator",
                        "."});
            table29.AddRow(new string[] {
                        "File type",
                        ".csv"});
            table29.AddRow(new string[] {
                        "Export type",
                        "attachment"});
            table29.AddRow(new string[] {
                        "Save as Unicode",
                        "Unchecked"});
#line 373
 testRunner.When("I select \"Parameter\" to \"Value\", from the tabe below", ((string)(null)), table29);
#line 379
 testRunner.And("I open excel file");
#line 380
 testRunner.Then("I should see queries on \"Assessment Date 1\" and \"Numeric Field 2\" fields");
#line 381
 testRunner.And("I take a screenshot 37 of 70");
#line 382
 testRunner.And("I close report");
#line 385
 testRunner.And("I select \"Reporter Module\"");
#line 386
 testRunner.And("I select link \"Stream-Edit Check Log Report\"");
#line 387
 testRunner.And("I select study \"Edit Check Study 8\"");
#line 388
 testRunner.And("I select site \"Edit Check Site 8\"");
#line 389
 testRunner.And("I select subject \"sub801\"");
#line 390
 testRunner.And("I select Form \"Assessment Date Log2\"");
#line 391
 testRunner.And("I select checkbox \"Edit Check\" for \"Check Type\"");
#line 392
 testRunner.And("I select checkbox Check \"CheckExecution\" for \"Log Type\"");
#line 393
 testRunner.And("I select button \"Submit Report\"");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table30.AddRow(new string[] {
                        "Separator",
                        "."});
            table30.AddRow(new string[] {
                        "File type",
                        ".csv"});
            table30.AddRow(new string[] {
                        "Export type",
                        "attachment"});
            table30.AddRow(new string[] {
                        "Save as Unicode",
                        "Unchecked"});
#line 394
 testRunner.And("I select \"Parameter\" to \"Value\", from the tabe below", ((string)(null)), table30);
#line 400
 testRunner.When("I open excel file");
#line 401
 testRunner.Then("I should see fired editchecks");
#line 402
 testRunner.And("I take a screenshot 38 of 70");
#line 403
 testRunner.And("I close report");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("J-Review verification.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void J_ReviewVerification_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("J-Review verification.", ((string[])(null)));
#line 406
 this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 408
 testRunner.And("I login to Rave as user \"<User 1>\" with password \"<Password>\"");
#line 409
 testRunner.And("I select link \"Home\"");
#line 410
 testRunner.And("I select \"Reporter Module\"");
#line 411
 testRunner.And("I select \"J-Review\"");
#line 412
 testRunner.And("I select \"Edit Check Study 8\"");
#line 413
 testRunner.And("I select button \"Submit Report\"");
#line 414
 testRunner.And("I select \"Edit Check Study 8\" \"Prod\" from \"Studies\"");
#line 415
 testRunner.And("I select button \"Reports\"");
#line 416
 testRunner.And("I select \"Detail Data Listing\" report from \"Type\" in \"Report Browser\"");
#line 417
 testRunner.And("I select \"MetricViews\" from \"Panels\"");
#line 418
 testRunner.And("I select \"Queries\" from \"MetricViews\"");
#line 419
 testRunner.And("I select \"Project, Site, Subject, Datapage, Field, Record Position QueryText, Que" +
                    "ryStatus, Answered Data, Answer Text\"");
#line 420
 testRunner.When("I select button \"Create Report\"");
#line 421
 testRunner.Then("I should see \"sub801\"");
#line 422
 testRunner.And("I should see \"Added Query\" in \"QueryText\"");
#line 423
 testRunner.And("I take a screenshot 39 of 70");
#line 424
 testRunner.And("I Close \"Detail Data Listing\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("BOXI report verification.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void BOXIReportVerification_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BOXI report verification.", ((string[])(null)));
#line 427
 this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 429
 testRunner.And("I login to Rave as user \"editcheck1\" with password \"<Password>\"");
#line 430
 testRunner.And("I select \"Reporter Module\"");
#line 431
 testRunner.And("I select \"Business Objects XI\"");
#line 432
 testRunner.And("I select \"Edit Check Study 8\"");
#line 433
 testRunner.And("I select button \"Submit Report\"");
#line 434
 testRunner.And("I select dropdown \"New\"");
#line 435
 testRunner.And("I select \"Web Intelligence Document\"");
#line 436
 testRunner.And("I select \"Rave 5.6 Universe\"");
#line 437
 testRunner.And("I select \"Project Name, Site Name, Subject Name, Folder Name, Form Name, Query Te" +
                    "xt\" in \"Results Objects\"");
#line 438
 testRunner.And("I select \"Site Name, Subject Name, Folder Name, FormName\" in \"Query Filters\"");
#line 439
 testRunner.And("I select \"Equal To\" from \"In List\" in \"Query Filters\" for \"Site Name\"");
#line 440
 testRunner.And("Enter \"Value(s) from list\" \"Edit Check Site 8\" in \"Query Filters\" for \"Site Name\"" +
                    "");
#line 441
 testRunner.And("I select \"Equal To\" from \"In List\" in \"Query Filters\" for \"Subject Name\"");
#line 442
 testRunner.And("Enter \"Value(s) from list\" \"sub801\" in \"Query Filters\" for \"Subject Name\"");
#line 443
 testRunner.And("I select \"Equal To\" from \"In List\" in \"Query Filters\" for \"Folder Name\"");
#line 444
 testRunner.And("Enter \"Value(s) from list\" \"Test A Single Edit\" in \"Query Filters\" for \"Folder Na" +
                    "me\"");
#line 445
 testRunner.And("I select \"Equal To\" from \"In List\" in \"Query Filters\" for \"Form Name\"");
#line 446
 testRunner.And("Enter \"Value(s) from list\" \"Assessment Date Log2\" in \"Query Filters\" for \"Form Na" +
                    "me\"");
#line 447
 testRunner.When("I select button \"Run Query\"");
#line 448
 testRunner.Then("I should see \"sub801\"");
#line 449
 testRunner.And("I should see \"Added Query\" in \"QueryText\"");
#line 450
 testRunner.And("I take a screenshot 40 of 70");
#line 451
 testRunner.And("I Close \"BOXI Report\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Migrate Subject")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void MigrateSubject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Migrate Subject", ((string[])(null)));
#line 454
 this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 456
 testRunner.And("I login to Rave as user \"editcheck\" with password \"<Password>\"");
#line 457
 testRunner.And("I select \"AM Edit Check Study\"");
#line 458
 testRunner.And("I select site \"AM Edit Site\"");
#line 459
    testRunner.And("I create a subject \"sub802\"");
#line 460
 testRunner.And("I select form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table31.AddRow(new string[] {
                        "Standard 1",
                        "6"});
            table31.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table31.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 461
 testRunner.And("I enter and save the following data, from the table below", ((string)(null)), table31);
#line 466
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response");
#line 467
 testRunner.And("I answer the query on \"Log Field 1\" field");
#line 468
 testRunner.And("I save the form \"Mixed Form\"");
#line 469
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 470
 testRunner.And("I save the form \"Mixed Form\"");
#line 471
 testRunner.And("I note CRF Version \"<Source CRF Version1>\"");
#line 472
 testRunner.And("I take a screenshot\t41 of 70");
#line 474
 testRunner.And("I select site \"AM Edit Site\"");
#line 475
    testRunner.And("I create a subject \"sub803\"");
#line 476
 testRunner.And("I select form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table32.AddRow(new string[] {
                        "Standard 1",
                        "6"});
            table32.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table32.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 477
 testRunner.And("I enter and save the following data, from the table below", ((string)(null)), table32);
#line 482
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response");
#line 483
 testRunner.And("I answer the query on \"Log Field 1\" field");
#line 484
 testRunner.And("I save the form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table33.AddRow(new string[] {
                        "Standard 1",
                        "5"});
#line 485
 testRunner.And("I change the data on \"Standard 1\" field from the table below:", ((string)(null)), table33);
#line 488
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 489
 testRunner.And("I save the form \"Mixed Form\"");
#line 490
 testRunner.And("I note CRF Version \"<Source CRF Version1>\"");
#line 491
 testRunner.And("I take a screenshot 42 of 70");
#line 493
 testRunner.And("I select link \"Home\"");
#line 494
 testRunner.And("I select link \"Architect\"");
#line 495
 testRunner.And("I select link \"AM Edit Check Study\"");
#line 496
 testRunner.And("I select link \"Draft 1\"");
#line 497
 testRunner.And("I select link \"Edit Checks\"");
#line 498
 testRunner.And("I select edit image for \"Mixed Form Query\" Edit Check");
#line 499
 testRunner.And("I unselect checkbox \"Active\"");
#line 500
 testRunner.And("I select  link \"Update\"");
#line 501
 testRunner.And("I select link \"Draft 1\"");
#line 502
 testRunner.And("I publish CRF Version");
#line 503
 testRunner.And("I note CRF Version \"<Target CRF Version1>\"");
#line 504
 testRunner.And("I select link \"AM Edit Check Study\"");
#line 505
 testRunner.And("I select link \"Amendment Manager\"");
#line 506
 testRunner.And("I select \"<Source CRF Version1>\" from dropdown \"Source CRF\"");
#line 507
 testRunner.And("I select \"<Target CRF Version1>\" from dropdown \"Target CRF\"");
#line 508
 testRunner.And("I select button \"Create Plan\"");
#line 509
 testRunner.And("I take a screenshot 43 of 70");
#line 511
 testRunner.And("I Migrate \"All Subjects\"");
#line 512
 testRunner.And("I select Migration Results and verify Job Status is set to Complete");
#line 513
 testRunner.And("I take a screenshot 44 of 70");
#line 515
 testRunner.And("I select link \"Home\"");
#line 516
 testRunner.And("I select \"AM Edit Check Study\"");
#line 517
 testRunner.And("I select site \"AM Edit Site\"");
#line 518
    testRunner.And("I select a subject \"sub802\"");
#line 519
 testRunner.And("I select form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table34.AddRow(new string[] {
                        "Log Field 1",
                        "4"});
#line 520
 testRunner.And("I change the data on \"Log Field 1\" field from the table below:", ((string)(null)), table34);
#line 523
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table35.AddRow(new string[] {
                        "Log Field 1",
                        "3"});
            table35.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 524
 testRunner.And("I add a new log line, enter and save the data, from the table below", ((string)(null)), table35);
#line 528
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line 529
 testRunner.And("I take a screenshot 45 of 70");
#line 531
 testRunner.And("I select site \"AM Edit Site\"");
#line 532
    testRunner.And("I select a subject \"sub803\"");
#line 533
 testRunner.And("I select form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table36.AddRow(new string[] {
                        "Standard 1",
                        "8"});
#line 534
 testRunner.And("I change the data on \"Standard 1\" field from the table below:", ((string)(null)), table36);
#line 537
 testRunner.And("I save the form \"Mixed Form\"");
#line 538
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table37.AddRow(new string[] {
                        "Log Field 1",
                        "6"});
            table37.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 539
 testRunner.And("I add a new log line, enter and save the data, from the table below", ((string)(null)), table37);
#line 543
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line 544
 testRunner.And("I take a screenshot 46 of 70");
#line 546
 testRunner.And("I select link \"Home\"");
#line 547
 testRunner.And("I select link \"Architect\"");
#line 548
 testRunner.And("I select link \"AM Edit Check Study\"");
#line 549
 testRunner.And("I select link \"Draft 1\"");
#line 550
 testRunner.And("I select link \"Edit Checks\"");
#line 551
 testRunner.And("I select edit image for \"Mixed Form Query\" Edit Check");
#line 552
 testRunner.And("I select checkbox \"Active\"");
#line 553
 testRunner.And("I select  link \"Update\"");
#line 554
 testRunner.And("I select link \"Draft 1\"");
#line 555
 testRunner.And("I publish CRF Version");
#line 556
 testRunner.And("I note CRF Version \"<Target CRF Version2>\"");
#line 557
 testRunner.And("I select link \"AM Edit Check Study\"");
#line 558
 testRunner.And("I select link \"Amendment Manager\"");
#line 559
 testRunner.And("I select \"<Target CRF Version1>\" from dropdown \"Source CRF\"");
#line 560
 testRunner.And("I select \"<Target CRF Version2>\" from dropdown \"Target CRF\"");
#line 561
 testRunner.And("I select button \"Create Plan\"");
#line 562
 testRunner.And("I select link \"Exceute Plan\"");
#line 563
 testRunner.And("I Migrate \"All Subjects\"");
#line 564
 testRunner.And("I select Migration Results and verify Job Status is set to Complete");
#line 565
 testRunner.And("I take a screenshot 47 of 70");
#line 567
 testRunner.And("I select link \"Home\"");
#line 568
 testRunner.And("I select \"AM Edit Check Study\"");
#line 569
 testRunner.And("I select site \"AM Edit Site\"");
#line 570
    testRunner.And("I select a subject \"sub802\"");
#line 571
 testRunner.And("I select form \"Mixed Form\"");
#line 572
 testRunner.And("I verify new query did fire on \"Log Field 1\" field with require response on the f" +
                    "irst log line");
#line 573
 testRunner.And("I verify new query did fire on \"Log Field 1\" field with require response on the s" +
                    "econd log line");
#line 574
 testRunner.And("I take a screenshot 48 of 70");
#line 576
 testRunner.And("I select site \"AM Edit Site\"");
#line 577
    testRunner.And("I select a subject \"sub803\"");
#line 578
 testRunner.And("I select form \"Mixed Form\"");
#line 579
 testRunner.And("I verify new query did fire on \"Log Field 1\" field with require response on the f" +
                    "irst log line");
#line 580
 testRunner.And("I verify new query did fire on \"Log Field 1\" field with require response on the s" +
                    "econd log line");
#line 581
 testRunner.And("I take a screenshot 49 of 70");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Publish Checks")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void PublishChecks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Publish Checks", ((string[])(null)));
#line 584
 this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 586
 testRunner.And("I login to Rave as user \"editcheck\" with password \"<Password>\"");
#line 587
 testRunner.And("I select link \"Architect\"");
#line 588
 testRunner.And("I select link \"AM Edit Check Study\"");
#line 589
 testRunner.And("I select link \"Draft 1\"");
#line 590
 testRunner.And("I publish and push CRF Version");
#line 591
 testRunner.And("I note CRF Version \"<Publish CRF Version1>\"");
#line 592
 testRunner.And("I publish CRF Version");
#line 593
 testRunner.And("I note CRF Version \"<Publish CRF Version2>\"");
#line 594
 testRunner.And("I publish CRF Version");
#line 595
 testRunner.And("I note CRF Version \"<Publish CRF Version3>\"");
#line 597
 testRunner.And("I select link \"Home\"");
#line 598
 testRunner.And("I select \"AM Edit Check Study\"");
#line 599
 testRunner.And("I select site \"AM Edit Site\"");
#line 600
    testRunner.And("I create a subject \"sub804\"");
#line 601
 testRunner.And("I select form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table38.AddRow(new string[] {
                        "Standard 1",
                        "6"});
            table38.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table38.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 602
 testRunner.And("I enter and save the following data, from the table below", ((string)(null)), table38);
#line 607
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response");
#line 608
 testRunner.And("I take a screenshot 50 of 70");
#line 609
 testRunner.And("I answer the query on \"Log Field 1\" field");
#line 610
 testRunner.And("I save the form \"Mixed Form\"");
#line 611
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 612
 testRunner.And("I save the form \"Mixed Form\"");
#line 613
 testRunner.And("I take a screenshot 51 of 70");
#line 615
 testRunner.And("I select link \"Home\"");
#line 616
 testRunner.And("I select link \"Architect\"");
#line 617
 testRunner.And("I select link \"AM Edit Check Study\"");
#line 618
 testRunner.And("I select link \"Pulish Checks\"");
#line 619
 testRunner.And("I select \"<Publish CRF Version1>\" from dropdown \"Current CRF Version\"");
#line 620
 testRunner.And("I select \"<Publish CRF Version2>\" from dropdown \"Reference CRF Version\"");
#line 621
 testRunner.And("I select button \"Create Plan\"");
#line 622
 testRunner.And("I check \"Inactivate\" checkbox for \"Mixed Form Query\" edit check");
#line 623
 testRunner.And("I select link \"Save\"");
#line 624
 testRunner.And("I take a screenshot 52 of 70");
#line 625
 testRunner.And("I select link \"Publish\"");
#line 626
 testRunner.And("I verify Job Status is set to Complete");
#line 627
 testRunner.And("I take a screenshot 53 of 70");
#line 629
 testRunner.And("I select link \"Home\"");
#line 630
 testRunner.And("I select \"AM Edit Check Study\"");
#line 631
 testRunner.And("I select site \"AM Edit Site\"");
#line 632
    testRunner.And("I select a subject \"sub804\"");
#line 633
 testRunner.And("I select form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table39.AddRow(new string[] {
                        "Standard 1",
                        "7"});
#line 634
 testRunner.And("I change the data on \"Standard 1\" field from the table below:", ((string)(null)), table39);
#line 637
 testRunner.And("I save the form \"Mixed Form\"");
#line 638
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field");
#line 639
 testRunner.And("I take a screenshot 54 of 70");
#line 641
 testRunner.And("I select link \"Home\"");
#line 642
 testRunner.And("I select link \"Architect\"");
#line 643
 testRunner.And("I select link \"AM Edit Check Study\"");
#line 644
 testRunner.And("I select link \"Pulish Checks\"");
#line 645
 testRunner.And("I select \"<Publish CRF Version1>\" from dropdown \"Current CRF Version\"");
#line 646
 testRunner.And("I select \"<Publish CRF Version3>\" from dropdown \"Reference CRF Version\"");
#line 647
 testRunner.And("I select button \"Create Plan\"");
#line 648
 testRunner.And("I check \"Publish\" checkbox for \"Mixed Form Query\" edit check");
#line 649
 testRunner.And("I select link \"Save\"");
#line 650
 testRunner.And("I take a screenshot 55 of 70");
#line 651
 testRunner.And("I select link \"Publish\"");
#line 652
 testRunner.And("I verify Job Status is set to Complete");
#line 653
 testRunner.And("I take a screenshot 56 of 70");
#line 655
 testRunner.And("I select link \"Home\"");
#line 656
 testRunner.And("I select \"AM Edit Check Study\"");
#line 657
 testRunner.And("I select site \"AM Edit Site\"");
#line 658
    testRunner.And("I select a subject \"sub804\"");
#line 659
 testRunner.And("I select form \"Mixed Form\"");
#line 660
 testRunner.And("I verify new query did fire on \"Log Field 1\" field");
#line 661
 testRunner.And("I answer the query on \"Log Field 1\" field");
#line 662
 testRunner.And("I save the form \"Mixed Form\"");
#line 663
 testRunner.And("I take a screenshot 57 of 70");
#line 664
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 665
 testRunner.And("I save the form \"Mixed Form\"");
#line 666
 testRunner.And("I take a screenshot 58 of 70");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table40.AddRow(new string[] {
                        "Standard 1",
                        "8"});
#line 667
 testRunner.And("I change the data on \"Standard 1\" field from the table below:", ((string)(null)), table40);
#line 670
 testRunner.And("I save the form \"Mixed Form\"");
#line 671
 testRunner.And("I verify new query did fire on \"Log Field 1\" field.");
#line 672
 testRunner.And("I take a screenshot 59 of 70");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Queries verification on data points with Freeze, Hard lock and Inactive records")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Feaature 8")]
        public virtual void QueriesVerificationOnDataPointsWithFreezeHardLockAndInactiveRecords()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Queries verification on data points with Freeze, Hard lock and Inactive records", ((string[])(null)));
#line 675
 this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 677
 testRunner.And("I select \"Edit Check Study 8\"");
#line 678
 testRunner.And("I select site \"Edit Check Site 8\"");
#line 679
    testRunner.And("I create a subject \"sub805\"");
#line 680
 testRunner.And("I select form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table41.AddRow(new string[] {
                        "Standard 1",
                        "6"});
            table41.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table41.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 681
 testRunner.And("I enter and save the following data, from the table below", ((string)(null)), table41);
#line 686
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response on first" +
                    " record position");
#line 687
 testRunner.And("I take a screenshot 60 of 70");
#line 688
 testRunner.And("I add new log line 2");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table42.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table42.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 689
 testRunner.And("I enter and save the following data, from the table below", ((string)(null)), table42);
#line 693
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response on secon" +
                    "d record position");
#line 694
 testRunner.And("I take a screenshot 61 of 70");
#line 695
 testRunner.And("I add new log line 3");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table43.AddRow(new string[] {
                        "Log Field 1",
                        "5"});
            table43.AddRow(new string[] {
                        "Log Field 2",
                        "2"});
#line 696
 testRunner.And("I enter and save the following data, from the table below", ((string)(null)), table43);
#line 700
 testRunner.And("I verify \"Log Field 1\" field displays query opened with require response on third" +
                    " record position");
#line 701
 testRunner.And("I take a screenshot 62 of 70");
#line 703
 testRunner.And("I answer the query on \"Log Field 1\" field on first record position");
#line 704
 testRunner.And("I save the form \"Mixed Form\"");
#line 705
 testRunner.And("I answer the query on \"Log Field 1\" field on seond record position");
#line 706
 testRunner.And("I save the form \"Mixed Form\"");
#line 707
 testRunner.And("I answer the query on \"Log Field 1\" field on third record position");
#line 708
 testRunner.And("I save the form \"Mixed Form\"");
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table44.AddRow(new string[] {
                        "Log Field 1",
                        "6"});
#line 710
 testRunner.And("I change the data on \"Log Field 1\" field on first record position, from the table" +
                    " below:", ((string)(null)), table44);
#line 713
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 714
 testRunner.And("I save the form \"Mixed Form\"");
#line 715
 testRunner.And("I take a screenshot 63 of 70");
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table45.AddRow(new string[] {
                        "Log Field 1",
                        "6"});
#line 716
 testRunner.And("I change the data on \"Log Field 1\" field on second record position, from the tabl" +
                    "e below:", ((string)(null)), table45);
#line 719
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 720
 testRunner.And("I save the form \"Mixed Form\"");
#line 721
 testRunner.And("I take a screenshot 64 of 70");
#line hidden
            TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table46.AddRow(new string[] {
                        "Log Field 1",
                        "6"});
#line 722
 testRunner.And("I change the data on \"Log Field 1\" field on third record position, from the table" +
                    " below:", ((string)(null)), table46);
#line 725
 testRunner.And("I close the query on \"Log Field 1\" field");
#line 726
 testRunner.And("I save the form \"Mixed Form\"");
#line 727
 testRunner.And("I take a screenshot 65 of 70");
#line 729
 testRunner.And("I select edit icon on first record position");
#line 730
 testRunner.And("I select checkbox \"Freeze\" on \"Log Field 1\" field on first record position");
#line 731
 testRunner.And("I save the form \"Mixed Form\"");
#line 732
 testRunner.And("I select edit icon on second record position");
#line 733
 testRunner.And("I select checkbox \"Hadrd Lock\" on \"Log Field 1\" field on second record position");
#line 734
 testRunner.And("I save the form \"Mixed Form\"");
#line 735
 testRunner.And("I select link \"Inactivate\"");
#line 736
 testRunner.And("I select \"3\" in dropdown");
#line 737
 testRunner.And("I select \"Inactivate\" button");
#line 738
 testRunner.And("I take a screenshot 66 of 70");
#line hidden
            TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table47.AddRow(new string[] {
                        "Standard 1",
                        "7"});
#line 740
 testRunner.And("I change the data on \"Standard 1\" field from the table below:", ((string)(null)), table47);
#line 743
 testRunner.And("I save the form \"Mixed Form\"");
#line 744
 testRunner.And("I verify new query did fire on \"Log Field 1\" field on first record position");
#line 745
 testRunner.And("I take a screenshot 67 of 70");
#line 746
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field on second record position");
#line 747
 testRunner.And("I take a screenshot 68 of 70");
#line 748
 testRunner.And("I verify new query did not fire on \"Log Field 1\" field on third record position");
#line 749
 testRunner.And("I take a screenshot 69 of 70");
#line 750
 testRunner.When("I run SQL Script \"Query Logging Script\"");
#line hidden
            TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                        "ProjectName",
                        "SiteNumber",
                        "SiteName",
                        "Environment",
                        "SubjectName",
                        "CheckActionInstanceDataPageName",
                        "CheckActionRecordPosition",
                        "CheckActionFieldName",
                        "CheckActionFieldData",
                        "TriggerFieldInstanceName",
                        "TriggerFieldInstanceDatapageName",
                        "TriggerFieldRecordPosition",
                        "TriggerFieldName",
                        "TriggerFieldData",
                        "EditCheckName",
                        "MarkingGroupName",
                        "QueryMessage",
                        "EventTime"});
            table48.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub805",
                        "Mixed Form",
                        "2",
                        "Log Field 1",
                        "18",
                        "Test A Single Edit",
                        "Standard 1",
                        "2",
                        "Standard 1",
                        "7",
                        "Mixed Form Query",
                        "Site",
                        "Query Opened on Log Field 1",
                        "{DateTime}"});
            table48.AddRow(new string[] {
                        "Edit Check Study 8",
                        "80001",
                        "Edit Check Site 8",
                        "PROD",
                        "sub805",
                        "Mixed Form",
                        "3",
                        "Log Field 1",
                        "18",
                        "Test A Single Edit",
                        "Standard 1",
                        "2",
                        "Standard 1",
                        "7",
                        "Mixed Form Query",
                        "Site",
                        "Query Opened on Log Field 1",
                        "{DateTime}"});
#line 751
    testRunner.Then("I should not see the logging data for queries", ((string)(null)), table48);
#line 755
 testRunner.And("I take a screenshot 70 of 70");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
