// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Medidata.RBT.Features.Rave.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DT13637InRave5_6_4InAMixedFormAltCodedValueFromAStandardDSLFieldDoesnTGetPropagatedIntoHiddenDatapointsOnNewly_CreatedRecords_Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "US11306_DT13637_Updated08062012.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DT 13637 In Rave 5.6.4, in a mixed form, AltCodedValue from a standard DSL field " +
                    "doesn\'t get propagated into hidden datapoints on newly-created records.", "As a Rave user\r\nGiven I enter a value for a dynamic searchlist field on a mixed f" +
                    "orm\r\nWhen I view the AltCodedValue for the hidden datapoints\r\nThen I should see " +
                    "the same AltCodedValue for the standard datapoint of the dynamic searchlist fiel" +
                    "d", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "DT 13637 In Rave 5.6.4, in a mixed form, AltCodedValue from a standard DSL field " +
                            "doesn\'t get propagated into hidden datapoints on newly-created records.")))
            {
                Medidata.RBT.Features.Rave.Features.DT13637InRave5_6_4InAMixedFormAltCodedValueFromAStandardDSLFieldDoesnTGetPropagatedIntoHiddenDatapointsOnNewly_CreatedRecords_Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 12
#line 13
    testRunner.Given("I am logged in to Rave with username \"defuser\" and password \"password\"");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TESt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13637 In Rave 5.6.4, in a mixed form, AltCodedValue from a standard DSL field " +
            "doesn\'t get propagated into hidden datapoints on newly-created records.")]
        public virtual void TESt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TESt", ((string[])(null)));
#line 58
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line 59
 testRunner.When("I select Study \"Geneloid_SJ\" and Site \"Site 1\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table1.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table1.AddRow(new string[] {
                        "Subject Number",
                        "{RndNum<num1>(3)}"});
#line 60
 testRunner.When("I create a Subject", ((string)(null)), table1);
#line 65
 testRunner.And("I select Form \"Device Form\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Control Type"});
            table2.AddRow(new string[] {
                        "Device Type",
                        "Device Type 1",
                        "radiobutton"});
            table2.AddRow(new string[] {
                        "Device",
                        "Device 1B",
                        "dynamic search list"});
            table2.AddRow(new string[] {
                        "Devimpdate",
                        "01 Jan 2012",
                        ""});
            table2.AddRow(new string[] {
                        "Devcomments",
                        "N/A",
                        ""});
#line 66
 testRunner.And("I enter data in CRF and save", ((string)(null)), table2);
#line 74
 testRunner.And("I add a new log line");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Control Type"});
            table3.AddRow(new string[] {
                        "Devimpdate",
                        "01 MAR 2012",
                        ""});
            table3.AddRow(new string[] {
                        "Devcomments",
                        "N/A",
                        ""});
#line 75
 testRunner.And("I enter data in CRF and save", ((string)(null)), table3);
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB-DT13637-01 As a Data Manager, when an EDC user enters data for a standard dyna" +
            "mic searchlist field, then I expect to see the AltCodedValue for that field prop" +
            "agated to the hidden datapoints on the log lines.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13637 In Rave 5.6.4, in a mixed form, AltCodedValue from a standard DSL field " +
            "doesn\'t get propagated into hidden datapoints on newly-created records.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("release_2012.1.0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PB-DT13637-01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Draft")]
        public virtual void PB_DT13637_01AsADataManagerWhenAnEDCUserEntersDataForAStandardDynamicSearchlistFieldThenIExpectToSeeTheAltCodedValueForThatFieldPropagatedToTheHiddenDatapointsOnTheLogLines_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB-DT13637-01 As a Data Manager, when an EDC user enters data for a standard dyna" +
                    "mic searchlist field, then I expect to see the AltCodedValue for that field prop" +
                    "agated to the hidden datapoints on the log lines.", new string[] {
                        "release_2012.1.0",
                        "PB-DT13637-01",
                        "Draft"});
#line 83
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line 85
 testRunner.When("I select Study \"Geneloid_SJ\" and Site \"Site 1\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table4.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table4.AddRow(new string[] {
                        "Subject Number",
                        "{RndNum<num1>(3)}"});
#line 86
 testRunner.When("I create a Subject", ((string)(null)), table4);
#line 91
 testRunner.And("I select Form \"Device Form\"");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Control Type"});
            table5.AddRow(new string[] {
                        "Device Type",
                        "Device Type 1",
                        "radiobutton"});
            table5.AddRow(new string[] {
                        "Device",
                        "Device 1B",
                        "dynamic search list"});
            table5.AddRow(new string[] {
                        "Devimpdate",
                        "01 Jan 2012",
                        ""});
            table5.AddRow(new string[] {
                        "Devcomments",
                        "N/A",
                        ""});
#line 92
 testRunner.And("I enter data in CRF and save", ((string)(null)), table5);
#line 100
 testRunner.And("I add a new log line");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Control Type"});
            table6.AddRow(new string[] {
                        "Devimpdate",
                        "01 Mar 2012",
                        ""});
            table6.AddRow(new string[] {
                        "Devcomments",
                        "N/A",
                        ""});
#line 101
 testRunner.And("I enter data in CRF and save", ((string)(null)), table6);
#line 107
 testRunner.And("I take a screenshot");
#line 108
 testRunner.And("I navigate to \"Home\"");
#line 109
 testRunner.And("I navigate to \"Reporter\"");
#line 110
 testRunner.And("I select Report \"Data Listing\"");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Environment"});
            table7.AddRow(new string[] {
                        "Geneloid_SJ",
                        "Prod"});
#line 111
 testRunner.And("I set report parameter \"Study\" with table", ((string)(null)), table7);
#line 115
 testRunner.When("I click button \"Submit Report\"");
#line 116
 testRunner.And("I switch to \"DataListingsReport\" window");
#line 118
 testRunner.And("I choose \"Clinical Views\" from \"Data Source\"");
#line 119
 testRunner.And("I choose \"Device Form (DEF)\" from \"Form\"");
#line 121
 testRunner.And("I click button \"Run\"");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject Name",
                        "Record Position",
                        "DEVICETYPE_RAW",
                        "DEVICETYPE_STD",
                        "DEVICE_RAW",
                        "DEVICE_STD",
                        "DEVICE_ALTCODEDVALUE",
                        "DEVIMPDATE",
                        "DEVCOMMENTS"});
            table8.AddRow(new string[] {
                        "SUBJ101",
                        "1",
                        "Device Type 1",
                        "DVT1",
                        "Device 1A",
                        "DVT1 - DV1A",
                        "DV1A",
                        "01 MAR 2012",
                        "N/A"});
            table8.AddRow(new string[] {
                        "SUBJ101",
                        "2",
                        "Device Type 1",
                        "DVT1",
                        "Device 1A",
                        "DVT1 - DV1A",
                        "DV1A",
                        "01 MAR 2012",
                        "N/A"});
#line 123
 testRunner.And("I verify data", ((string)(null)), table8);
#line 127
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PB-DT13637-02 As a Data Manager, when an EDC user enters data for a standard dyna" +
            "mic searchlist field, then I expect to see the AltCodedValue for that field prop" +
            "agated to the hidden datapoints on the log lines.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DT 13637 In Rave 5.6.4, in a mixed form, AltCodedValue from a standard DSL field " +
            "doesn\'t get propagated into hidden datapoints on newly-created records.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PB-DT13637-02")]
        public virtual void PB_DT13637_02AsADataManagerWhenAnEDCUserEntersDataForAStandardDynamicSearchlistFieldThenIExpectToSeeTheAltCodedValueForThatFieldPropagatedToTheHiddenDatapointsOnTheLogLines_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PB-DT13637-02 As a Data Manager, when an EDC user enters data for a standard dyna" +
                    "mic searchlist field, then I expect to see the AltCodedValue for that field prop" +
                    "agated to the hidden datapoints on the log lines.", new string[] {
                        "PB-DT13637-02"});
#line 130
this.ScenarioSetup(scenarioInfo);
#line 12
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data"});
            table9.AddRow(new string[] {
                        "Subject Initials",
                        "SUB"});
            table9.AddRow(new string[] {
                        "Subject Identifier",
                        "{RndNum<num1>(3)}"});
#line 131
 testRunner.When("I create a Subject", ((string)(null)), table9);
#line 136
 testRunner.And("I select \"Device Form\"");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Data",
                        "Record Position"});
            table10.AddRow(new string[] {
                        "Device Type",
                        "Device Type 1",
                        "0"});
            table10.AddRow(new string[] {
                        "Device",
                        "Device 1A",
                        "0"});
            table10.AddRow(new string[] {
                        "Date Implanted/Re-implanted",
                        "01 Jan 2012",
                        "1"});
            table10.AddRow(new string[] {
                        "Comments",
                        "N/A",
                        "1"});
#line 137
 testRunner.And("I enter data in CRF and save", ((string)(null)), table10);
#line 144
 testRunner.And("I inactivate log line 1");
#line 145
 testRunner.And("I take a screenshot");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value",
                        "Record Position"});
            table11.AddRow(new string[] {
                        "Device",
                        "Device 1B",
                        "0"});
#line 146
 testRunner.And("I enter data in CRF and save", ((string)(null)), table11);
#line 150
 testRunner.And("I take a screenshot");
#line 151
 testRunner.And("I reactivate log line 1");
#line 152
 testRunner.And("I take a screenshot");
#line 153
 testRunner.And("I select \"Home\"");
#line 154
 testRunner.And("I navigate to \"Reporter\"");
#line 155
 testRunner.And("I select \"Data Listing\"");
#line 156
 testRunner.And("I Choose \"Study\"");
#line 157
 testRunner.And("I select \"Geneloid_SJ\"");
#line 158
 testRunner.And("I click button \"Submit Report\"");
#line 159
 testRunner.And("I select Data Source \"Clinical Views\"");
#line 160
 testRunner.And("I select Form \"Device Form\"");
#line 161
 testRunner.And("I click button \"Run\"");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject Name",
                        "Record Position",
                        "DEVICETYPE_RAW",
                        "DEVICETYPE_STD",
                        "DEVICE_RAW",
                        "DEVICE_STD",
                        "DEVICE_ALTCODEDVALUE",
                        "DEVIMPDATE",
                        "DEVCOMMENTS"});
            table12.AddRow(new string[] {
                        "SUBJ101",
                        "1",
                        "Device Type 1",
                        "DVT1",
                        "Device 1B",
                        "DVT1 - DV1B",
                        "DV1B",
                        "01 MAR 2012",
                        "N/A"});
#line 162
 testRunner.And("I verify data", ((string)(null)), table12);
#line 165
 testRunner.And("I take a screenshot");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
